Repository fluent/fluent-bit, pull requests merged in 2018-11, with the labels that each got.

#875 flb_utils: fix out of bounds write on invalid utf-8
  src/flb_utils.c
Labels: troubleshooting

#878 in_tail: Add Exit_On_EOF option to tail input
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.c
  plugins/in_tail/tail_config.h
Labels: waiting-for-user

#806 in_systemd: add strip_underscores configuration
  plugins/in_systemd/systemd.c
  plugins/in_systemd/systemd_config.c
  plugins/in_systemd/systemd_config.h
Labels: enhancement

#874 Switch to distroless as base image for container, add .dockerignore
  .dockerignore
  Dockerfile
Labels: waiting-for-user

#863 in_tail: add Docker mode for recombining log lines split by Docker
  include/fluent-bit/flb_pack.h
  plugins/in_tail/CMakeLists.txt
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.c
  plugins/in_tail/tail_config.h
  plugins/in_tail/tail_dockermode.c
  plugins/in_tail/tail_dockermode.h
  plugins/in_tail/tail_file.c
  plugins/in_tail/tail_file.h
  plugins/in_tail/tail_file_internal.h
  plugins/in_tail/tail_multiline.h
  src/flb_pack.c
Labels: enhancement, fixed, merge-next

#881 parsers: Support CRI-O and containerd
  conf/parsers.conf
Labels: enhancement, waiting-for-user

#897 Switch to dockerhub debian:9 from launcher.gcr.io/debian9
  Dockerfile
Labels: waiting-for-user

#805 in_mem: clean up the buffer handling in proc.c
  plugins/in_mem/proc.c
Labels: merge-next

#898 docker: add missing plugins.conf
  Dockerfile
Labels: waiting-for-user

#918 core: Add 'Match_Regex' option to filter/task/output
  CMakeLists.txt
  include/fluent-bit/flb_filter.h
  include/fluent-bit/flb_output.h
  include/fluent-bit/flb_router.h
  plugins/filter_nest/nest.c
  src/CMakeLists.txt
  src/flb_filter.c
  src/flb_output.c
  src/flb_router.c
  src/flb_task.c
  src/proxy/go/CMakeLists.txt
  tests/runtime/core_engine.c
Labels: waiting-for-user
