Repository fluent/fluent-bit, pull requests merged in 2020-05, with the labels that each got.

#2154 filter_lua: support protected mode (#2148)
  plugins/filter_lua/lua.c
  plugins/filter_lua/lua_config.c
  plugins/filter_lua/lua_config.h
Labels: enhancement, waiting-for-user

#1322 parser: mysql quoted decoder
  include/fluent-bit/flb_parser_decoder.h
  include/fluent-bit/flb_unescape.h
  src/flb_parser_decoder.c
  src/flb_unescape.c
  tests/internal/data/parser/regex.conf
  tests/internal/parser.c
Labels: waiting-for-user

#1439 pack: fixed double's json packing precision
  src/flb_pack.c
Labels: waiting-for-user

#1549 hash: Implement EVICT_OLDER and EVICT_LESS_USED modes in flb_hash
  src/flb_hash.c
  tests/internal/hashtable.c
Labels: waiting-for-user

#1912 out_kafka: add dynamic_topic option
  plugins/out_kafka/kafka.c
  plugins/out_kafka/kafka_config.c
  plugins/out_kafka/kafka_config.h
Labels: waiting-for-user

#1634 Debian build fixes
  debian/control
  debian/td-agent-bit.lintian-overrides
Labels: waiting-for-user

#1558 pack: gelf: add string log level support
  src/flb_pack_gelf.c
Labels: waiting-for-user, work-in-process
