Repository fluent/fluent-bit, pull requests merged in 2021-07, with the labels that each got.

#3711 out_prometheus_exporter: disable http stop on exit
  plugins/out_prometheus_exporter/prom.c
Labels: docs-required

#3670 network: modify flb_net_getaddrinfo error code
  src/flb_network.c
Labels: docs-required

#3714 lib: mbedtls: set compiler flag to c99
  lib/mbedtls-2.26.0/CMakeLists.txt
Labels: docs-required

#3706 aws: add support for credential_process
  CMakeLists.txt
  include/fluent-bit/flb_aws_credentials.h
  src/CMakeLists.txt
  src/aws/flb_aws_credentials_http.c
  src/aws/flb_aws_credentials_log.h
  src/aws/flb_aws_credentials_process.c
  src/aws/flb_aws_credentials_profile.c
  tests/internal/CMakeLists.txt
  tests/internal/aws_credentials_process.c
  tests/internal/aws_credentials_profile.c
  tests/internal/aws_credentials_test_internal.h
  tests/internal/data/aws_credentials/credential_process/aws-credential-process
  tests/internal/data/aws_credentials/shared_config.ini
Labels: docs-required

#3721 in_node_exporter_metrics: add new options 'path.procfs' and 'path.sysfs'
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_config.c
  plugins/in_node_exporter_metrics/ne_cpu_linux.c
  plugins/in_node_exporter_metrics/ne_cpufreq_linux.c
  plugins/in_node_exporter_metrics/ne_diskstats_linux.c
  plugins/in_node_exporter_metrics/ne_meminfo_linux.c
  plugins/in_node_exporter_metrics/ne_utils.c
  plugins/in_node_exporter_metrics/ne_utils.h
Labels: docs-required

#3705 out_kafka: fix avro support
  plugins/out_kafka/kafka.c
  src/flb_avro.c
  tests/internal/avro.c
  tests/internal/data/avro/live-sample.json
  tests/internal/data/avro/multiline.json
Labels: docs-required

#3722 network: remove the c-ares result code masquerading
  src/flb_network.c
Labels: docs-required, ok-to-test

#3724 in_node_exporter_metrics: sanitize meminfo metric names
  plugins/in_node_exporter_metrics/ne_meminfo_linux.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, docs-required, ok-to-test

#3725 lib: cmetrics: v0.1.0
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_encode_msgpack.c
  lib/cmetrics/tests/encoding.c
Labels: docs-required

#3726 in_node_exporter_metrics: add 'uname' collector
  plugins/in_node_exporter_metrics/CMakeLists.txt
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_uname.c
  plugins/in_node_exporter_metrics/ne_uname.h
  plugins/in_node_exporter_metrics/ne_uname_linux.c
Labels: docs-required

#3677 filter_kubernetes: run command to get token to talk to api-server and refresh it if needed
  plugins/filter_kubernetes/CMakeLists.txt
  plugins/filter_kubernetes/kube_conf.c
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kube_meta.c
  plugins/filter_kubernetes/kubernetes.c
Labels: docs-required, ok-to-merge

#3729 out_prometheus_exporter: add destructor callback
  plugins/out_prometheus_exporter/prom_http.c
Labels: docs-required

#3731 workflows: enable sanitize memory/thread tests.
  .github/workflows/unit-tests.yaml
Labels: docs-required

#3733 workflows: add extra job to validate matrix.
  .github/workflows/unit-tests.yaml
Labels: docs-required

#3734 workflows: depend on run-unit-tests-amd64
  .github/workflows/unit-tests.yaml
Labels: docs-required

#3752 general: add docker_compose examples to the repository.
  .github/workflows/unit-tests.yaml
  docker_compose/node-exporter-dashboard/README.md
  docker_compose/node-exporter-dashboard/config/grafana/provisioning/dashboards/dashboard.json
  docker_compose/node-exporter-dashboard/config/grafana/provisioning/dashboards/dashboard.yml
  docker_compose/node-exporter-dashboard/config/grafana/provisioning/datasources/datasource.yml
  docker_compose/node-exporter-dashboard/config/prometheus.yml
  docker_compose/node-exporter-dashboard/docker-compose.yml
Labels: ci, docs-required

#3755 build: fix rpm user file list.
  CMakeLists.txt
Labels: docs-required

#3738 out_s3: fix use-after-free in destructor
  plugins/out_s3/s3.c
Labels: docs-required

#3758 out_s3: fix use-after-free in destructor (1.8 backport)
  plugins/out_s3/s3.c
Labels: docs-required

#3741 http_server: remove unused variables
  src/http_server/api/v1/health.c
Labels: docs-required

#3764 in_node_exporter_metrics: add 'filefd' linux collector
  plugins/in_node_exporter_metrics/CMakeLists.txt
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_filefd_linux.c
  plugins/in_node_exporter_metrics/ne_filefd_linux.h
Labels: docs-required

#3767 in_node_exporter_metrics: fix compiler warnings
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne_netdev_linux.c
Labels: docs-required

#3760 out_splunk: set channel len on init
  plugins/out_splunk/splunk_conf.c
Labels: docs-required

#3771 output: don't return uninitialized variable
  include/fluent-bit/flb_output.h
Labels: docs-required

#3777 lib: added snappy-c
  CMakeLists.txt
  cmake/headers.cmake
  cmake/libraries.cmake
  lib/snappy-fef67ac/CMakeLists.txt
  lib/snappy-fef67ac/LICENSE
  lib/snappy-fef67ac/compat.h
  lib/snappy-fef67ac/snappy-int.h
  lib/snappy-fef67ac/snappy.c
  lib/snappy-fef67ac/snappy.h
Labels: docs-required

#3768 dockerfile: make master_debug abort on HTTP download failure
  dockerfiles/Dockerfile.x86_64-master_debug
Labels: docs-required

#3779 lib: cmetrics: upgrade to v0.1.5
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_encode_msgpack.h
  lib/cmetrics/include/cmetrics/cmt_encode_prometheus_remote_write.h
  lib/cmetrics/include/cmetrics/cmt_version.h
  lib/cmetrics/include/prometheus_remote_write/protobuf-c.h
  lib/cmetrics/include/prometheus_remote_write/remote.pb-c.h
  lib/cmetrics/include/prometheus_remote_write/types.pb-c.h
  lib/cmetrics/src/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_encode_prometheus_remote_write.c
  lib/cmetrics/src/external/LICENSE
  lib/cmetrics/src/external/protobuf-c.c
  lib/cmetrics/src/external/remote.pb-c.c
  lib/cmetrics/src/external/types.pb-c.c
  lib/cmetrics/tests/encoding.c
Labels: docs-required

#3781 dockerfiles: don't pull from tarball on master build
  dockerfiles/Dockerfile.x86_64-master_debug
Labels: docs-required

#3783 out_kafka: upgrade librdkafka path v1.7.0
  plugins/out_kafka/CMakeLists.txt
Labels: docs-required

#3780 snappy: add new helper
  include/fluent-bit/flb_snappy.h
  lib/snappy-fef67ac/CMakeLists.txt
  lib/snappy-fef67ac/compat.h
  lib/snappy-fef67ac/snappy.c
  src/CMakeLists.txt
  src/flb_snappy.c
Labels: docs-required

#3784 out_prometheus_remove_write: add new Prometheus remote write output plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_prometheus_remote_write/CMakeLists.txt
  plugins/out_prometheus_remote_write/remote_write.c
  plugins/out_prometheus_remote_write/remote_write.h
  plugins/out_prometheus_remote_write/remote_write_conf.c
  plugins/out_prometheus_remote_write/remote_write_conf.h
Labels: docs-required

#3787 out_prometheus_exporter: remove unused variable
  plugins/out_prometheus_exporter/prom_http.c
Labels: docs-required

#3788 out_es: estimate bulk size to less reallocation(#3775)
  plugins/out_es/es.c
  plugins/out_es/es_bulk.c
  plugins/out_es/es_bulk.h
Labels: docs-required

#3785 out_loki: Do not retry when loki returns 400.
  plugins/out_loki/loki.c
Labels: docs-required

#3798 out_prometheus_remote_write : Added headers
  plugins/out_prometheus_remote_write/remote_write.c
  plugins/out_prometheus_remote_write/remote_write.h
  plugins/out_prometheus_remote_write/remote_write_conf.c
  plugins/out_prometheus_remote_write/remote_write_conf.h
Labels: docs-required

#3799 in_tail: add new option 'skip_empty_lines=false'
  plugins/filter_multiline/ml.c
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.h
  plugins/in_tail/tail_file.c
Labels: docs-required

#3808 out_prometheus_exporter: support multiple metrics
  plugins/out_prometheus_exporter/prom.c
  plugins/out_prometheus_exporter/prom.h
Labels: docs-required

#3810 signv4: fix NULL dereference
  src/flb_signv4.c
Labels: docs-required

#3809 tests: internal: fuzzers: signv4: free allocated memory.
  tests/internal/fuzzers/signv4_fuzzer.c
Labels: docs-required

#3814 pack_gelf: ensure proper cleanup in case of failure.
  src/flb_pack_gelf.c
Labels: docs-required

#3786 out_s3: fix compiler warnings
  plugins/out_s3/s3.c
Labels: docs-required

#3832 http_client: warn when flb_http_do() fails due to malformed data
  src/flb_http_client.c
Labels: docs-required

#3807 out_s3: added static file path configuration option
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#3804 out_s3: added data ordering preservation feature
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#3805 out_s3: log_key configuration option implemented
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#3668 out_s3: log_key configuration option implemented
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#3842 out_s3: added data ordering preservation feature
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#3850 out_s3: fixed potential segfault on file discard
  plugins/out_s3/s3.c
Labels: docs-required

#3831 http_client: log allocation failures for request headers
  src/flb_http_client.c
Labels: docs-required

#3839 out_loki: delay mp_sbuf->data derefence (#3796)
  plugins/out_loki/loki.c
Labels: docs-required

#3853 lib: fix race between flb_start and flb_destroy
  src/flb_lib.c
Labels: docs-required

#3690 out_s3: added static file path configuration option
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#3855 out_loki: avoid passing mp_sbuf twice
  plugins/out_loki/loki.c
Labels: docs-required

#3836 output_thread: fixed multiple initialization of local_thread_instance
  src/flb_output_thread.c
Labels: docs-required

#3860 out_s3: added file permission fix and flb_errno to read / write file
  plugins/out_s3/s3.c
Labels: docs-required

#3849 out_s3: fixed potential segfault on file discard
  plugins/out_s3/s3.c
Labels: docs-required

#3868 network: fixed cleanup order in UDP timeout handler
  src/flb_network.c
Labels: docs-required

#3880 multiline: always validate stream_id with lru_parser
  src/multiline/flb_ml.c
Labels: docs-required

#3830 regex: log allocation failures in Onigmo
  src/flb_regex.c
Labels: docs-required
