Repository fluent/fluent-bit, pull requests merged in 2021-11, with the labels that each got.

#4151 parser: remove unused list and check its size(#4132)
  src/flb_parser.c
Labels: Stale, backport to v1.8.x

#3215 out_s3: Support MinIO
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: Stale, docs-required

#4302 flb_str: use flb_strndup to implement flb_strdup
  include/fluent-bit/flb_str.h
Labels: docs-required

#4188 out_cloudwatch_logs: auto retry invalid requests
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#4305 mem: fix alloc_size attribute and remove extra ifs
  CMakeLists.txt
  include/fluent-bit/flb_mem.h
Labels: docs-required

#4299 chore: Add clangd files to .gitignore
  .gitignore
Labels: docs-required

#4275 config: fix inconsistent parsing of configuration keys
  src/flb_parser.c
  src/flb_plugin.c
Labels: docs-required

#4324 parsers: add rabbitmq, neo4j and dns custom parsers
  conf/parser_custom.conf
Labels: docs-required

#4295 network: fixed error detection and handling
  include/fluent-bit/flb_network.h
  src/flb_network.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4333 lib: monkey: sync library changes
  lib/monkey/api/test.c
  lib/monkey/include/monkey/mk_http_parser.h
  lib/monkey/mk_core/mk_iov.c
  lib/monkey/mk_core/mk_rconf.c
  lib/monkey/mk_server/mk_http.c
  lib/monkey/plugins/cgi/cgi.c
  lib/monkey/plugins/dirlisting/dirlisting.c
  lib/monkey/plugins/fastcgi/fcgi_handler.c
  lib/monkey/plugins/liana/liana.c
Labels: docs-required

#4303 sha512: use openssl implementation if available
  include/fluent-bit/flb_sha512.h
  src/flb_sha512.c
Labels: docs-required

#4328 out_stackdriver: Add http_request_key config
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: backport to v1.8.x

#4294 network: fixed error detection and handling
  include/fluent-bit/flb_network.h
  src/flb_network.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4345 filter_aws: retrieve metadata on initialization
  plugins/filter_aws/aws.c
Labels: docs-required

#4339 in_forward: fix handling of TCP connections on SIGTERM (#2610)
  plugins/in_forward/fw.c
  plugins/in_forward/fw_conn.c
  plugins/in_forward/fw_conn.h
Labels: backport to v1.8.x

#4347 filter_aws: expose metadata through internal environment context
  plugins/filter_aws/aws.c
Labels: backport to v1.8.x

#4348 out_calyptia: process and append AWS metadata
  plugins/out_calyptia/calyptia.c
Labels: backport to v1.8.x

#3761 ra: fix bison warnings
  src/record_accessor/ra.l
  src/record_accessor/ra.y
Labels: Stale, docs-required

#4354 tests: use more portable variable initialization for 1.8 branch
  tests/internal/aws_client_mock.c
Labels: docs-required, backport to v1.8.x

#4372 tests: internal: fuzzer: extend config fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/config_fuzzer.c
  tests/internal/fuzzers/config_random_fuzzer.c
Labels: docs-required

#4241 workflows: add CIFuzz integration
  .github/workflows/cifuzz.yaml
Labels: Stale, docs-required

#4261 filter_rewrite_tag: add NULL check(#4246)
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#4346 flb_utils_write_str: detect and replace ill-formed utf-8 bytes -> master
  src/flb_utils.c
  tests/internal/utils.c
Labels: docs-required

#4297 flb_utils_write_str: detect and replace ill-formed utf-8 bytes -> 1.8
  src/flb_utils.c
  tests/internal/utils.c
Labels: docs-required

#4277 input_chunk: clarify space limit error.
  src/flb_input_chunk.c
Labels: docs-required
