Repository fluent/fluent-bit, pull requests merged in 2021-12, with the labels that each got.

#4381 workflows: Add PR check for CentOS 7 compilation
  .github/workflows/README.workflows.md
  .github/workflows/pr-compile-check.yaml
  dockerfiles/Dockerfile.centos7
Labels: ci

#4393 workflows: regular CVE scans using Trivy
  .github/workflows/cron-trivy.yaml
Labels: ci, docs-required

#4410 lib: monkey: sync dev changes
  lib/monkey/mk_server/mk_clock.c
  lib/monkey/mk_server/mk_fifo.c
  lib/monkey/mk_server/mk_lib.c
  lib/monkey/mk_server/mk_server.c
Labels: docs-required, draft

#4405 dockerfiles: Added missing dependency for libatomic.so.1
  dockerfiles/Dockerfile.arm32v7
Labels: bug, docs-required

#4408 dockerfiles: resolve ARM64 build issues
  dockerfiles/Dockerfile.arm64v8
Labels: docs-required

#4411 input_chunk: don't pause ingestion if filesystem storage is enabled (#4221)
  src/flb_input_chunk.c
Labels: docs-required

#4409 plugin_proxy: fail on missing FLBPluginRegister symbol
  src/flb_plugin_proxy.c
Labels: docs-required

#4301 random: Use getentropy(3) if available.
  CMakeLists.txt
  src/flb_random.c
Labels: docs-required

#4414 out_es: Fix buffer size when converted_size is equal to 0.
  plugins/out_es/es_bulk.c
Labels: docs-required

#4429 plugins/in_forward: removed unused variables
  plugins/in_forward/fw.c
Labels: docs-required

#4424 workflows: increase stale checks to 90 days for issues
  .github/workflows/pr-stale.yaml
Labels: community-feedback, ci

#4287 tests: runtime: in_proc: modify absent process name(#4274)
  tests/runtime/in_simple_systems.c
Labels: docs-required

#3603 in_forward: increase the buffer size to buffer_max_size
  plugins/in_forward/fw_conn.c
Labels: docs-required

#3824 out_gelf: check NULL context on exit
  plugins/out_gelf/gelf.c
Labels: docs-required

#3888 plugin_proxy: destroy used buffer on exit
  include/fluent-bit/flb_plugin_proxy.h
  src/flb_plugin_proxy.c
  src/proxy/go/go.c
  src/proxy/go/go.h
Labels: docs-required

#3896 ra_key: check subkeys length
  src/flb_ra_key.c
  tests/runtime/out_loki.c
Labels: docs-required

#3953 out_nats: support config map
  plugins/out_nats/nats.c
Labels: docs-required

#3954 out_gelf: support config map
  plugins/out_gelf/gelf.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok, docs-required

#3985 out_datadog: support config map
  plugins/out_datadog/datadog.c
  plugins/out_datadog/datadog.h
  plugins/out_datadog/datadog_conf.c
Labels: docs-required

#4025 filter_type_converter: new filter plugin
  CMakeLists.txt
  include/fluent-bit/flb_typecast.h
  plugins/CMakeLists.txt
  plugins/filter_type_converter/CMakeLists.txt
  plugins/filter_type_converter/type_converter.c
  plugins/filter_type_converter/type_converter.h
  src/CMakeLists.txt
  src/flb_typecast.c
  tests/internal/CMakeLists.txt
  tests/internal/typecast.c
  tests/runtime/CMakeLists.txt
  tests/runtime/filter_type_converter.c
Labels: docs-required

#4154 in_docker: use 64bit api to prevent overflow(#4083)
  plugins/in_docker/docker.c
Labels: docs-required

#4265 http_server: storage: add destructor to prevent leak
  src/http_server/api/v1/storage.c
Labels: docs-required

#4288 filter_rewrite_tag: fix Match aborting issue (#4276)
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#3592 out_skywalking: introduce Apache SkyWalking output plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_skywalking/CMakeLists.txt
  plugins/out_skywalking/skywalking.c
  plugins/out_skywalking/skywalking.h
  tests/runtime/CMakeLists.txt
  tests/runtime/out_skywalking.c
Labels: docs-required

#4436 multiline: cri: allow empty lines (#4284)
  src/multiline/flb_ml_parser_cri.c
Labels: docs-required, backport to v1.8.x

#4434 config: increase coro stack size if it is less than pagesize(#3716)
  src/flb_config.c
Labels: waiting-for-user, docs-required

#4442 workfows: Only add labels when PR opens
  .github/workflows/pr-labels.yaml
Labels: docs-required

#4443 workflows: reduce fuzz calls to just C source changes
  .github/workflows/cifuzz.yaml
Labels: docs-required

#4449 workflows: resolve failures in staging build
  .github/workflows/README.md
  .github/workflows/call-build-packages.yaml
  packaging/update-repos.sh
Labels: ci

#4453 workflows: remove disabled mergebot
  .github/workflows/merge-bot.yaml
Labels: docs-required

#4318 input chunk: correctly calculate the difference when chunks grow in flb_input_chunk_append_raw for total size limit.
  include/fluent-bit/flb_input_chunk.h
  src/flb_input_chunk.c
  tests/internal/input_chunk.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok, docs-required

#4460 workflows: staging build deb repo fix
  .github/dependabot.yml
  .github/workflows/call-build-packages.yaml
  .github/workflows/call-test-packages.yaml
  .github/workflows/staging-build.yaml
  .github/workflows/unit-tests.yaml
  .gitignore
  packaging/testing/smoke/packages/Dockerfile.debian10
  packaging/update-repos.sh
Labels: ci

#4461 1.8: backport fs fix
  include/fluent-bit/flb_input_chunk.h
  src/flb_input_chunk.c
  tests/internal/input_chunk.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4467 input_chunk: warn the user about tag truncation due to limits
  include/fluent-bit/flb_input_chunk.h
  src/flb_input_chunk.c
Labels: docs-required

#4470 workflows: resolve issues with required checks
  .github/workflows/skipped-unit-tests.yaml
  .github/workflows/unit-tests.yaml
  dockerfiles/Dockerfile.centos7
Labels: docs-required

#4476 workflows: debian bullseye build for staging
  .github/workflows/call-build-packages.yaml
  .github/workflows/call-test-packages.yaml
  packaging/README.md
  packaging/build.sh
  packaging/distros/debian/bullseye.arm64v8/Dockerfile
  packaging/distros/debian/bullseye.arm64v8/sources/.empty
  packaging/distros/debian/bullseye/Dockerfile
  packaging/distros/debian/bullseye/sources/.empty
  packaging/distros/raspbian/bullseye/Dockerfile
  packaging/distros/raspbian/bullseye/sources/.empty
  packaging/distros/raspbian/buster/Dockerfile.base
  packaging/testing/smoke/packages/Dockerfile.centos8
  packaging/testing/smoke/packages/Dockerfile.debian11
  packaging/update-repos.sh
Labels: packaging

#4485 workflows: call integration test on staging test
  .github/workflows/call-test-images.yaml
  .github/workflows/integration-build-master.yaml
  .github/workflows/integration-build-pr.yaml
  .github/workflows/integration-run-master.yaml
  .github/workflows/integration-run-pr.yaml
  .github/workflows/staging-test.yaml
Labels: ci, packaging

#4477 workflows: add linting
  .github/actionlint-matcher.json
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/call-test-images.yaml
  .github/workflows/call-test-packages.yaml
  .github/workflows/pr-lint.yaml
  .github/workflows/skipped-unit-tests.yaml
  .github/workflows/staging-build-multiarch-images.yaml
  .github/workflows/staging-release.yaml
  cmake/sanitizers-cmake/cmake/asan-wrapper
  update_version.sh
Labels: ci

#4490 workflows: simplify integration test
  .github/workflows/README.md
  .github/workflows/call-integration-image-build.yaml
  .github/workflows/integration-build-master.yaml
  .github/workflows/integration-build-pr.yaml
  .github/workflows/integration-run-master.yaml
  .github/workflows/integration-run-pr.yaml
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-closed-docker.yaml
  .github/workflows/pr-fuzz.yaml
  .github/workflows/pr-integration-test.yaml
Labels: ok-to-test, ci/integration-docker-ok, ci, ci/integration-test-gcp-ok

#4498 workflows: reusable package build for master and staging
  .github/workflows/build-master-packages.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/staging-build.yaml
Labels: packaging

#4499 workflows: support building from branch
  .github/workflows/build-master-packages.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/staging-build.yaml
Labels: packaging

#4495 workflows: resolve missing version for cleanup
  .github/workflows/pr-closed-docker.yaml
Labels: ci

#4514 packaging: resolve incompatible dependencies in raspbian/buster
  .github/workflows/call-build-packages.yaml
  lib/cmetrics/src/CMakeLists.txt
  packaging/distros/raspbian/buster/Dockerfile
  packaging/distros/raspbian/buster/Dockerfile.base
Labels: packaging

#4522 workflows: resolve staging test failures
  .github/containerscan/allowedlist.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/call-test-packages.yaml
  packaging/testing/smoke/packages/Dockerfile.centos8
  packaging/testing/smoke/packages/Dockerfile.debian11
  packaging/testing/smoke/packages/run-package-tests.sh
  packaging/testing/smoke/packages/test.sh
Labels: docs-required

#4517 out_forward: add missing ra check(#4511)
  plugins/out_forward/forward.c
Labels: docs-required

#4527 packaging: split centos repo config in twain
  .github/workflows/pr-lint.yaml
  packaging/testing/smoke/packages/Dockerfile.centos7
  packaging/testing/smoke/packages/Dockerfile.centos8
  packaging/update-repos.sh
Labels: packaging

#4532 packaging: fix incorrect repo filename
  .github/workflows/pr-lint.yaml
  packaging/testing/smoke/packages/Dockerfile.amazonlinux2
Labels: packaging

#4516 dockerfiles: update for debian11 and multi-arch
  .github/workflows/call-build-images.yaml
  .github/workflows/call-integration-image-build.yaml
  .github/workflows/pr-closed-docker.yaml
  .github/workflows/pr-image-tests.yaml
  .github/workflows/staging-test.yaml
  dockerfiles/Dockerfile.arm32v7
  dockerfiles/Dockerfile.arm64v8
  dockerfiles/Dockerfile.multiarch
  dockerfiles/Dockerfile.multiarch.linuxbuilder
  dockerfiles/Dockerfile.multiarch.linuxrelease
  dockerfiles/Dockerfile.x86_64
  dockerfiles/Dockerfile.x86_64-master
  dockerfiles/Dockerfile.x86_64-master_debug
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok

#4538 storage: don't ingest metrics when storage.metrics is off
  src/flb_storage.c
Labels: docs-required

#4531 windows: cmake: Add version information metadata with version.rc
  cmake/version.rc.in
  cmake/windows-setup.cmake
  src/CMakeLists.txt
Labels: docs-required

#4524 mpack: Implement lua <-> messagepack conversion using mpack
  CMakeLists.txt
  include/fluent-bit/flb_lua.h
  include/fluent-bit/flb_time.h
  plugins/filter_lua/CMakeLists.txt
  plugins/filter_lua/lua.c
  plugins/filter_lua/lua_config.c
  plugins/filter_lua/lua_config.h
  src/flb_lua.c
  src/flb_time.c
  tests/internal/lua.c
Labels: docs-required

#4540 build: require cmake >= 3.0
  CMakeLists.txt
Labels: docs-required

#4539 out_loki: add comment about label key removal
  plugins/out_loki/loki.c
Labels: docs-required

#4483 lib: monkey: sync Apple M1 support and other fixes
  lib/monkey/deps/flb_libco/CMakeLists.txt
  lib/monkey/deps/flb_libco/aarch64.c
  lib/monkey/mk_core/mk_rconf.c
  lib/monkey/mk_server/mk_clock.c
  lib/monkey/mk_server/mk_fifo.c
  lib/monkey/mk_server/mk_lib.c
  lib/monkey/mk_server/mk_server.c
Labels: docs-required

#4482 lib: flb_libco: add Apple M1 support
  lib/flb_libco/CMakeLists.txt
  lib/flb_libco/aarch64.c
Labels: docs-required

#4546 time: fix warning
  src/flb_time.c
Labels: docs-required

#4536 http_server: add missing argument
  src/http_server/flb_hs_utils.c
Labels: docs-required

#4535 time: use flb_time_to_nanosec for unset time check
  plugins/filter_kubernetes/kubernetes.c
  plugins/filter_parser/filter_parser.c
  plugins/in_docker_events/docker_events.c
  plugins/in_exec/in_exec.c
  plugins/in_stdin/in_stdin.c
  plugins/in_syslog/syslog_prot.c
  plugins/in_tail/tail_file.c
  plugins/in_tail/tail_multiline.c
  src/multiline/flb_ml.c
  tests/internal/multiline.c
Labels: docs-required
