Repository fluent/fluent-bit, pull requests merged in 2021-09, with the labels that each got.

#4002 aws: rename struct process stdin,stdout,stderr with _stream suffix
  src/aws/flb_aws_credentials_process.c
Labels: AWS, docs-required

#4053 tests: internal: fuzzers: fix issue in utils fuzzer
  tests/internal/fuzzers/utils_fuzzer.c
Labels: docs-required

#4051 tests: internal: fuzzer: add multiline parser fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/multiline_fuzzer.c
Labels: docs-required

#4068 in_node_exporter_metrics: drop needless assignment
  plugins/in_node_exporter_metrics/ne_vmstat_linux.c
Labels: docs-required

#4067 in_node_exporter_metrics: fix a typo
  plugins/in_node_exporter_metrics/ne_filefd_linux.c
Labels: docs-required

#4066 upstream: fix mutex lock on pending destroy connections
  src/flb_upstream.c
Labels: docs-required

#4058 http_server: metrics: add destructor to prevent leak
  src/http_server/api/v1/metrics.c
Labels: docs-required

#4056 http_server: health: check if hs_health_key is NULL(#3983)
  src/http_server/api/v1/health.c
Labels: docs-required

#4055 filter_nest: change log level (#4005)
  plugins/filter_nest/nest.c
Labels: docs-required

#4047 flb_aws_util: set max response buffer size for the http client
  src/aws/flb_aws_util.c
Labels: docs-required

#4074 out_es: AWS is rebranding to Amazon OpenSearch Service
  plugins/out_es/es.c
Labels: docs-required

#4076 out_kinesis_streams: info => debug for log send statement
  plugins/out_kinesis_firehose/firehose.c
  plugins/out_kinesis_streams/kinesis.c
Labels: docs-required

#4073 out_es: AWS is rebranding to Amazon OpenSearch Service
  plugins/out_es/es.c
Labels: docs-required

#4062 filter_kubernetes: new option 'use_tag_for_meta' to use tag for metadata
  plugins/filter_kubernetes/kube_conf.c
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kube_meta.c
  plugins/filter_kubernetes/kubernetes.c
Labels: docs-required

#4036 in_dummy: optimize message generation.
  plugins/in_dummy/in_dummy.c
  plugins/in_dummy/in_dummy.h
Labels: docs-required

#4081 out_prometheus_exporter: use ins host/port api(#4070)
  plugins/out_prometheus_exporter/prom.c
  plugins/out_prometheus_exporter/prom.h
  plugins/out_prometheus_exporter/prom_http.c
  plugins/out_prometheus_exporter/prom_http.h
Labels: docs-required

#4088 output: initialize network defaults for output instances (#4050)
  src/flb_output.c
Labels: docs-required

#4077 input: pause file storage when going over chunk limit.
  include/fluent-bit/flb_input.h
  src/flb_input.c
  src/flb_input_chunk.c
Labels: backport to v1.8.x

#4095 oauth2: release upstream connection on exit
  src/flb_oauth2.c
Labels: backport to v1.8.x

#4099 config: add scheduler cap and base
  include/fluent-bit/flb_config.h
  src/flb_config.c
  src/flb_scheduler.c
Labels: backport to v1.8.x

#4092 sp: re-structure unit test code
  include/fluent-bit/stream_processor/flb_sp.h
  src/stream_processor/README.md
  src/stream_processor/flb_sp.c
  tests/internal/include/sp_cb_functions.h
  tests/internal/include/sp_helpers.h
  tests/internal/include/sp_invalid_queries.h
  tests/internal/include/sp_select_keys.h
  tests/internal/include/sp_select_subkeys.h
  tests/internal/include/sp_snapshot.h
  tests/internal/include/sp_window.h
  tests/internal/stream_processor.c
Labels: docs-required

#4101 lib: monkey: thread-local-storage fixes
  lib/monkey/CMakeLists.txt
  lib/monkey/include/monkey/mk_config.h
  lib/monkey/include/monkey/mk_http_thread.h
  lib/monkey/include/monkey/mk_thread_libco.h
  lib/monkey/include/monkey/mk_thread_ucontext.h
  lib/monkey/include/monkey/mk_tls.h
  lib/monkey/mk_core/mk_utils.c
  lib/monkey/mk_server/mk_fifo.c
  lib/monkey/mk_server/mk_http_thread.c
  lib/monkey/mk_server/mk_lib.c
  lib/monkey/mk_server/mk_net.c
  lib/monkey/mk_server/mk_scheduler.c
  lib/monkey/mk_server/mk_vhost.c
  lib/monkey/mk_server/monkey.c
Labels: backport to v1.8.x

#4091 out_s3: add back flb_sds_destroy() lost in 8cd50f8 (#4038)
  plugins/out_s3/s3.c
Labels: AWS

#4108 out_s3: add back flb_sds_destroy() lost in 8cd50f8 (#4038)
  plugins/out_s3/s3.c
Labels: docs-required

#4123 upstream: made a few shutdown calls conditional
  src/flb_upstream.c
Labels: backport to v1.8.x

#4125 upstream: flb_upstream_conn busy flag addition
  include/fluent-bit/flb_upstream_conn.h
  src/flb_upstream.c
Labels: backport to v1.8.x

#4122 network: fixed a local resolution corner case
  src/flb_network.c
Labels: backport to v1.8.x
