Repository fluent/fluent-bit, pull requests merged in 2021-05, with the labels that each got.

#3422 parser_decoder: fix memory leak.
  src/flb_parser_decoder.c
Labels: docs-required

#3283 in_tail: make inotify file watch configurable at runtime
  plugins/in_tail/CMakeLists.txt
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.h
  plugins/in_tail/tail_file.c
  plugins/in_tail/tail_fs.h
  plugins/in_tail/tail_fs_inotify.c
  plugins/in_tail/tail_fs_inotify.h
  plugins/in_tail/tail_fs_stat.c
  plugins/in_tail/tail_fs_stat.h
Labels: Stale

#3420 record_accessor: fix stackoverflow
  src/flb_record_accessor.c
Labels: docs-required

#3373 Invert token expiration test.
  src/flb_oauth2.c
Labels: docs-required

#3425 main: fixed help text alignment
  src/fluent-bit.c
Labels: docs-required

#3418 ra_key: fix signed integer overflow
  src/flb_ra_key.c
Labels: docs-required

#3435 in_forward: support config map
  plugins/in_forward/fw.c
  plugins/in_forward/fw_config.c
  plugins/in_forward/fw_conn.h
Labels: docs-required

#3408 out_loki: change log level to suppress 200-205 status log (#3363)
  plugins/out_loki/loki.c
Labels: docs-required

#3378 tests: runtime: filter_lua: add testcode for filter_lua
  tests/runtime/CMakeLists.txt
  tests/runtime/filter_lua.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3453 flb: parse-json: fix double-free
  src/flb_parser_json.c
Labels: docs-required

#3272 http_client: implement NO_PROXY support
  include/fluent-bit/flb_config.h
  include/fluent-bit/flb_str.h
  include/fluent-bit/flb_upstream.h
  src/flb_config.c
  src/flb_upstream.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, docs-required, ok-to-test, waiting-for-user

#3455 oauth2: fix token expires time not updated
  src/flb_oauth2.c
Labels: docs-required

#3460 workflows: add workflow for testing issue 3398.
  .github/workflows/3398.yaml
Labels: ok-to-merge

#3461 workflows: long running depends on docker_build
  .github/workflows/3398.yaml
Labels: docs-required

#3462 workflows: add 3398 dockerfile.
  dockerfiles/Dockerfile.x86_64-3398
Labels: docs-required

#3466 workflows: add grafana outputs to test long runs.
  .github/workflows/3398.yaml
Labels: docs-required

#3069 out_loki: implement drop_single_key
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: docs-required

#3472 input_chunk: only iterate over overlimit output plugins
  src/flb_input_chunk.c
Labels: docs-required

#3342 out_stackdriver: enable custom regex to parse local_resource_id for stackdriver meta labels
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
  tests/runtime/data/stackdriver/stackdriver_test_k8s_resource.h
  tests/runtime/out_stackdriver.c
Labels: docs-required

#3478 src: parser_json: fix double-free.
  src/flb_parser_json.c
Labels: docs-required

#3464 config: support "Log_Level off" to suppress log
  src/flb_config.c
Labels: docs-required

#3480 out_stackdriver: fix invalid read of get_stream() function
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
Labels: docs-required

#3485 workflows: enable gcp disk id.
  .github/workflows/3398.yaml
Labels: docs-required

#3486 workflows: add gcp sa key to long running tests
  .github/workflows/3398.yaml
Labels: docs-required

#3489 out_prometheus_exporter: release resource on exit
  plugins/out_prometheus_exporter/prom.c
  plugins/out_prometheus_exporter/prom_http.c
Labels: docs-required

#3506 in_http: add pipelining support
  plugins/in_http/http_conn.c
Labels: docs-required

#3394 build: fix CMakeLists.txt for systemd and upstart init files
  CMakeLists.txt
  src/CMakeLists.txt
Labels: docs-required

#3482 http_client: use slist function for NO_PROXY parsing
  src/flb_upstream.c
  tests/internal/slist.c
Labels: docs-required

#3508 utils: add underflow boundary checks.
  src/flb_utils.c
Labels: docs-required

#3509 tests: internal: fuzzers: http: fix leak
  tests/internal/fuzzers/http_fuzzer.c
Labels: docs-required

#3510 tests: internal: fuzzers: json_fuzzer: fix leaks.
  tests/internal/fuzzers/flb_json_fuzzer.c
Labels: docs-required

#3513 tests: internal: fuzzer: config: fix upper bound on config file size.
  tests/internal/fuzzers/config_fuzzer.c
Labels: docs-required

#3514 tests: internals: fuzzers: record_ac: clean up fuzzer.
  tests/internal/fuzzers/record_ac_fuzzer.c
Labels: docs-required

#3515 src: gzip: set a max decompression size.
  src/flb_gzip.c
Labels: docs-required

#3517 out_splunk: new option http_buffer_size (default: 2M)
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk.h
Labels: docs-required

#3523 workflows: Update stale bot to exclude enhancement label
  .github/workflows/pr-stale.yaml
Labels: docs-required

#3524 out_stackdriver: drop log entries if http response code - 4xx
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#3490 tail: Fix handling of long lines
  plugins/in_tail/tail_file.c
Labels: docs-required

#3522 unescape: fix casting char to uint32_t on arm inconsistent with x86(#3142)
  src/flb_unescape.c
Labels: docs-required

#3526 tests: runtime: in_tail: add testcase for skip_long_lines
  tests/runtime/data/tail/out/skip_long_lines.out
  tests/runtime/in_tail.c
Labels: docs-required

#3525 in_winstat: add a new plugin to export Windows-specific metrics
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_winstat/CMakeLists.txt
  plugins/in_winstat/winstat.c
Labels: docs-required

#3533 out_stackdriver: move functions to remove warnings
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#3532 http_server: api: metrics: use flb_time for prometheus
  src/http_server/api/v1/metrics.c
Labels: docs-required

#3531 upstream: rename flb_should_proxy_for_host -> flb_upstream_needs_proxy
  include/fluent-bit/flb_upstream.h
Labels: docs-required

#3536 workflows: enable bigquery integration tests.
  .github/workflows/integration-run-master.yaml
  .github/workflows/integration-run-pr.yaml
Labels: ci/integration-docker-ok, docs-required, ok-to-test

#3547 workflows: add 1.7 dockerfile
  dockerfiles/Dockerfile.x86_64-1_7
Labels: docs-required

#3549 workflows: update integration build master
  .github/workflows/integration-build-master.yaml
Labels: docs-required

#3557 network: fix corner case in async dns lookup
  include/fluent-bit/flb_network.h
  src/flb_network.c
Labels: docs-required

#3561 flb: gzip: fix memory leak.
  src/flb_gzip.c
Labels: docs-required

#3577 input: release instance when init failed and fix typo
  src/flb_input.c
Labels: docs-required

#3576 output: release instance when init failed
  src/flb_output.c
Labels: docs-required

#3560 tests: internal: fuzzers: add timeout checks and add license.
  tests/internal/fuzzers/flb_fuzz_header.h
  tests/internal/fuzzers/flb_json_fuzzer.c
  tests/internal/fuzzers/parse_json_fuzzer.c
  tests/internal/fuzzers/parser_fuzzer.c
  tests/internal/fuzzers/utils_fuzzer.c
Labels: docs-required
