Repository fluent/fluent-bit, pull requests merged in 2021-03, with the labels that each got.

#3179 filter_record_modifier: use bias-free words.
  plugins/filter_record_modifier/filter_modifier.c
  plugins/filter_record_modifier/filter_modifier.h
Labels: ci/integration-docker-ok, ci/integration-test-ok, ok-to-test

#3157 in_tail: pass missing argument processed_bytes
  plugins/in_tail/tail_file.c
Labels: waiting-for-user

#3199 ci: workflows: added unit testing workflow. Removed travis-ci.
  .github/workflows/README.workflows.md
  .github/workflows/pr-closed-docker.yaml
  .github/workflows/unit-tests.yaml
  .travis.yml
  appveyor.yml
  ci/appveyor-download
  ci/appveyor-download.ps1
  ci/do-ut
  ci/do-ut.ps1
Labels: ci, ci/integration-docker-ok, ci/integration-test-ok, ok-to-test

#3152 build: support native cross-compilation for ARM64
  CMakeLists.txt
  cmake/linux-arm64.cmake
  cmake/luajit.cmake
  cmake/onigmo.cmake
Labels: ci/integration-docker-ok, ci/integration-test-ok, ok-to-test

#3225 build: fix CMakeLists.txt for libbacktrace
  CMakeLists.txt
  cmake/linux-arm64.cmake
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ci/integration-test-microk8s-ok, ok-to-test

#3231 out_splunk: prioritize http_user/password over splunk_token.
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk_conf.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3291 flb_oauth: add missing code to clear sds string
  src/flb_oauth2.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test
