Repository fluent/fluent-bit, pull requests merged in 2021-04, with the labels that each got.

#3287 build: split install by components.
  CMakeLists.txt
  include/CMakeLists.txt
  src/CMakeLists.txt
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3306 workflow: allow equal and slash
  .github/workflows/check-commit.yaml
Labels: ci

#3317 lib: add option/property checks for input/output/filters.
  examples/out_lib/out_lib.c
  include/fluent-bit/flb_lib.h
  src/flb_engine.c
  src/flb_input.c
  src/flb_lib.c
  tests/runtime/CMakeLists.txt
  tests/runtime/config_map_opts.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3239 tail: added configuration for journal mode in WAL
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.h
  plugins/in_tail/tail_db.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3289 build: fix Dockerfile.arm64v8
  dockerfiles/Dockerfile.arm64v8
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3357 workflows: add mergebot and docs-required label.
  .github/workflows/README.workflows.md
  .github/workflows/mergebot.yaml
  .github/workflows/pr-checks.yaml
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, docs-required, ok-to-merge, ok-to-test

#3367 workflows: update merge-bot.yaml
  .github/workflows/merge-bot.yaml
Labels: docs-required

#3365 lib: fix cleanup function to relase flb_config (#3353)
  src/flb_lib.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-merge, ok-to-test

#3371 workflows: change label/merge-bot to pa token
  .github/workflows/merge-bot.yaml
  .github/workflows/pr-labels.yaml
Labels: docs-required

#3219 Allow 0 as Retry_Limit to disable retrying
  include/fluent-bit/flb_output.h
  src/flb_engine.c
  src/flb_output.c
  src/flb_sosreport.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-merge

#3396 in_tail: initialize mult_parsers list before parsing properties
  plugins/in_tail/tail_multiline.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3375 out_s3: fix memory leak when gzip is on
  plugins/out_s3/s3.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3310 out_cloudwatch_logs: fix memory leak when using cpu or mem input
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#3337 tests: runtime: out_splunk: update testcase
  tests/runtime/out_splunk.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3417 parser: json: fix type confusion bug.
  src/flb_parser_json.c
Labels: docs-required

#3379 out_syslog: correctly select the rfc 3164 for syslog
  plugins/out_syslog/syslog.c
  plugins/out_syslog/syslog_conf.h
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, docs-required, ok-to-test

#3297 in_http: changes for lambda extension logs support
  plugins/in_http/http.c
  plugins/in_http/http.h
  plugins/in_http/http_prot.c
Labels: waiting-for-user

#3344 http_client: fail early when ingesting an invalid HTTP status
  src/flb_http_client.c
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test

#3298 in_http: changes for lambda extension logs support
  plugins/in_http/http.c
  plugins/in_http/http.h
  plugins/in_http/http_prot.c
Labels: waiting-for-user

#3203 ra: remove unnecessary funtion to simplify
  src/flb_record_accessor.c
Labels: Stale, ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-to-test
