Repository fluent/fluent-bit, pull requests merged in 2021-08, with the labels that each got.

#3899 build: add 'fluent-bit' package support
  CMakeLists.txt
Labels: enhancement

#3902 out_s3: added file permission executable fix
  plugins/out_s3/s3.c
Labels: docs-required

#3903 out_s3: added file permission executable fix
  plugins/out_s3/s3.c
Labels: docs-required

#3841 out_s3: fix NULL dereference when upload_id is unset
  plugins/out_s3/s3_multipart.c
Labels: docs-required

#3908 proxy_plugin: Add worker support for proxy plugins
  src/flb_output.c
Labels: docs-required

#3912 out_splunk: if 'event_key' is missing, pack as a normal map
  plugins/out_splunk/splunk.c
Labels: docs-required

#3648 out_cloudwatch: fix integer overflow in timestamps (issue #3640)
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: AWS, docs-required

#3222 out_azure: support using timestamp as timegenerated
  plugins/out_azure/azure.c
  plugins/out_azure/azure.h
  plugins/out_azure/azure_conf.c
Labels: ok-to-test, docs-required

#3925 out_azure: add missing flb_utils.h
  plugins/out_azure/azure_conf.c
Labels: docs-required

#3881 network: add ctype.h header
  src/flb_network.c
Labels: docs-required

#3916 build: Link to libatomic
  CMakeLists.txt
Labels: docs-required

#3932 bin: add SIGFPE handler
  src/fluent-bit.c
Labels: docs-required

#3950 out_calyptia: adjust header
  plugins/out_calyptia/calyptia.h
Labels: docs-required

#3957 out_datadog: do not print api_key in debug logs
  plugins/out_datadog/datadog_conf.c
Labels: docs-required

#3956 out_datadog: do not print api_key in debug logs
  plugins/out_datadog/datadog_conf.c
Labels: docs-required

#3961 http_client: remove ability to see HTTP request for non-dev env
  src/flb_http_client.c
Labels: docs-required

#3869 filter_checklist: new filter to flag records based on matching strings
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/filter_checklist/CMakeLists.txt
  plugins/filter_checklist/checklist.c
  plugins/filter_checklist/checklist.h
Labels: docs-required

#3946 aws: Fix AWS credential refresh to work as expected interval
  src/aws/flb_aws_credentials.c
Labels: docs-required

#3939 multiline: fix CRI time format string
  src/multiline/flb_ml_parser_cri.c
Labels: docs-required

#3936 lib: mbedtls: do not use --std=c99 on Windows
  lib/mbedtls-2.27.0/CMakeLists.txt
Labels: Windows, docs-required

#3937 build: avoid conflicting command options on Visual Studio 2019
  CMakeLists.txt
Labels: Windows, docs-required

#3989 dns: backport change from 1.8.3.
  src/flb_network.c
Labels: docs-required

#3992 utils: fix return value handling of uuid generator
  src/flb_utils.c
Labels: docs-required

#4000 lib: monkey: sync dev changes
  lib/monkey/include/monkey/mk_core/mk_event.h
  lib/monkey/include/monkey/mk_core/mk_event_epoll.h
  lib/monkey/include/monkey/mk_core/mk_event_kqueue.h
  lib/monkey/include/monkey/mk_core/mk_event_libevent.h
  lib/monkey/include/monkey/mk_core/mk_event_select.h
  lib/monkey/mk_core/mk_event.c
  lib/monkey/mk_core/mk_event_epoll.c
  lib/monkey/mk_core/mk_event_kqueue.c
  lib/monkey/mk_core/mk_event_libevent.c
  lib/monkey/mk_core/mk_event_select.c
  lib/monkey/mk_server/CMakeLists.txt
Labels: docs-required

#4001 scheduler: added scheduler tracking to the timer
  include/fluent-bit/flb_scheduler.h
  src/flb_scheduler.c
Labels: docs-required

#4029 signv4: allow url query parameter has no value
  src/flb_signv4.c
Labels: docs-required

#4028 signv4: allow url query parameter has no value to 1.8
  src/flb_signv4.c
Labels: docs-required

#4024 out_s3: don't complete uploads that were never created
  plugins/out_s3/s3.c
Labels: docs-required

#4023 out_s3: don't complete uploads that were never created
  plugins/out_s3/s3.c
Labels: docs-required
