Repository fluent/fluent-bit, pull requests merged in 2022-06, with the labels that each got.

#5439 out_http: Implement "body_key" and "headers_key" options
  plugins/out_http/http.c
  plugins/out_http/http.h
  plugins/out_http/http_conf.c
Labels: docs-required

#5535 out_pgsql: Fix typo specefied -> specified
  plugins/out_pgsql/pgsql.c
Labels: docs-required

#5518 in_opentelemetry: add support for raw traces
  plugins/in_opentelemetry/opentelemetry.c
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok, docs-required

#5550 debian: add missing fluent-bit configs to debian conffiles
  debian/conffiles
Labels: docs-required, ok-package-test

#5569 workflows: switch action to delete images
  .github/workflows/pr-closed-docker.yaml
Labels: docs-required

#5570 workflows: fix version
  .github/workflows/pr-closed-docker.yaml
Labels: docs-required

#5568 conf: adding parser for confluent schema registry
  conf/parsers_kafka.conf
Labels: docs-required

#5577 codeowners: fix issue with non-existent user and error
  CODEOWNERS
Labels: docs-required

#5579 lib: cmetrics: upgrade to v0.3.4
  lib/cmetrics/.github/workflows/build.yaml
  lib/cmetrics/.github/workflows/packages.yaml
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/cpack/macos/welcome.txt.cmakein
  lib/cmetrics/src/cmetrics.c
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_decode_opentelemetry.c
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/src/cmt_encode_influx.c
  lib/cmetrics/src/cmt_encode_msgpack.c
  lib/cmetrics/src/cmt_encode_text.c
  lib/cmetrics/src/cmt_variant.c
  lib/cmetrics/tests/data/issue_fluent_bit_5541.txt
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#5585 dockerfiles: add FLUENT_BIT_VERSION environment variable to containers
  .github/workflows/call-build-images.yaml
  dockerfiles/Dockerfile
  update_version.sh
Labels: ci

#5587 workflows: pin cosign-installer to v1
  .github/workflows/call-build-images.yaml
  .github/workflows/call-test-images.yaml
  .github/workflows/staging-release.yaml
Labels: ci

#5360 config: enable YAML support by default
  .github/workflows/unit-tests.yaml
  CMakeLists.txt
  cmake/windows-setup.cmake
  dockerfiles/Dockerfile.centos7
  src/config_format/flb_cf_fluentbit.c
Labels: ci/integration-docker-ok, ci/integration-test-ok

#5586 workflows: fix release test job
  .github/workflows/staging-release.yaml
  packaging/test-release-packages.sh
Labels: docs-required

#5584 workflows: add source packages to releases
  .github/actions/release-server-sync/action.yaml
  .github/workflows/call-build-linux-packages.yaml
Labels: ci

#4792 throttle: Fixed use after free
  plugins/filter_throttle/throttle.c
  plugins/filter_throttle/throttle.h
Labels: docs-required

#5399 packaging: support for ubuntu 22.04
  .github/actions/generate-package-build-matrix/action.yaml
  .github/workflows/call-test-packages.yaml
  .gitignore
  packaging/README.md
  packaging/distros/ubuntu/Dockerfile
  packaging/test-release-packages.sh
  packaging/testing/smoke/packages/Dockerfile.ubuntu2204
Labels: docs-required

#5597 workflows: fix publish script
  packaging/server/publish-all.sh
Labels: docs-required

#5609 include: fluent-bit: flb_input: fix some typos in comments
  include/fluent-bit/flb_input.h
Labels: docs-required

#5600 workflows: Install 32bit version of openssl libraries via vcpkg
  .github/workflows/call-build-windows.yaml
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/staging-build.yaml
Labels: docs-required

#5626 examples: reduce workload for perf-test
  examples/perf_test/.env
Labels: docs-required, ok-to-performance-test

#5636 ci: perf test improvements
  .github/workflows/pr-perf-test.yaml
  examples/perf_test/docker-compose.yml
  examples/perf_test/scripts/entrypoint.sh
Labels: docs-required

#5641 build: libyaml: Search libyaml with pkg-config and handle homebrew-ed libyaml
  CMakeLists.txt
Labels: docs-required

#5647 tests: runtime: in_syslog: Add missing FLB_HAVE_UNIX_SOCKET clause
  tests/runtime/in_syslog.c
Labels: docs-required

#5648 workflows: fix renamed perf-test call
  .github/workflows/pr-perf-test.yaml
Labels: docs-required

#5635 filter_throttle: add mutex to prevent race issue
  plugins/filter_throttle/throttle.c
  plugins/filter_throttle/throttle.h
Labels: docs-required

#5608 parser: free allocated types
  src/flb_parser.c
Labels: docs-required

#5653 tiger-1.8.15 20220628
  plugins/in_storage_backlog/sb.c
Labels: docs-required

#5660 workflows: update to post comment on perf test PRs
  .github/workflows/pr-perf-test.yaml
Labels: docs-required
