Repository fluent/fluent-bit, pull requests merged in 2022-08, with the labels that each got.

#5744 aws_util: set AWS Fluent Bit user agent based on environment
  include/fluent-bit/flb_aws_util.h
  src/aws/flb_aws_util.c
Labels: docs-required

#5775 aws_util: set AWS Fluent Bit user agent based on environment
  include/fluent-bit/flb_aws_util.h
  src/aws/flb_aws_util.c
Labels: docs-required

#5771 aws_util: use conccurent safe strtok_r
  src/aws/flb_aws_util.c
Labels: AWS

#5772 aws_util: use conccurent safe strtok_r
  src/aws/flb_aws_util.c
Labels: AWS

#5831 in_tail: added event based file ingestion batch limit
  plugins/in_tail/tail.c
  plugins/in_tail/tail.h
  plugins/in_tail/tail_config.h
Labels: docs-required

#5829 in_tail: Fix path_key when the file is rotated
  plugins/in_tail/tail_file.c
  plugins/in_tail/tail_file_internal.h
Labels: docs-required

#5056 go: proxy: plugin: Implement multi-threaded Golang input plugin mechanism
  include/fluent-bit/flb_api.h
  include/fluent-bit/flb_input.h
  include/fluent-bit/flb_output.h
  include/fluent-bit/flb_plugin_proxy.h
  src/flb_api.c
  src/flb_input.c
  src/flb_input_thread.c
  src/flb_output.c
  src/flb_plugin_proxy.c
  src/proxy/go/go.c
  src/proxy/go/go.h
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok, calyptia, ok-to-performance-test

#5739 conf: parser: add istio-envoy-proxy parser
  conf/parsers.conf
Labels: docs-required

#5738 conf: parser: fix envoy access log rubular.com link
  conf/parsers.conf
Labels: docs-required

#5850 lib: monkey: core event kqueue: don't use NOTE_SECONDS on macOS (#5756 backport to 1.9)
  lib/monkey/mk_core/mk_event_kqueue.c
Labels: docs-required

#5855 in_tail: fix path_key when the file is rotated (#5829 backport)
  plugins/in_tail/tail_file.c
  plugins/in_tail/tail_file_internal.h
Labels: docs-required

#5859 tiger: add in_tail batch enhancement
  plugins/in_tail/tail.c
  plugins/in_tail/tail.h
  plugins/in_tail/tail_config.h
Labels: docs-required

#5819 build: CMakeLists.txt Do not use private makefile targets
  CMakeLists.txt
  lib/chunkio/CMakeLists.txt
  lib/cmetrics/CMakeLists.txt
Labels: docs-required

#5844 engine: pass config->ch_event explicitly
  src/flb_engine.c
Labels: docs-required

#5881 cf_fluentbit: report undefined value error(#5880)
  src/config_format/flb_cf_fluentbit.c
  tests/internal/config_format_fluentbit.c
  tests/internal/data/config_format/classic/issue_5880.conf
Labels: docs-required

#5875 tests: runtime: out_lib: add test code for out_lib
  tests/runtime/CMakeLists.txt
  tests/runtime/out_lib.c
Labels: docs-required

#5842 tests: internal: aws_util: remove timezone dependency
  tests/internal/aws_util.c
Labels: docs-required

#5811 in_http: allow multiple json payloads(#5810)
  plugins/in_http/http_prot.c
Labels: docs-required

#5841 aws_util: fix type of extra_user_agent
  include/fluent-bit/flb_aws_util.h
Labels: docs-required

#5840 proxy: use flb_error api
  src/flb_plugin_proxy.c
  src/proxy/go/go.c
Labels: docs-required

#5736 in_kmsg: support prio_level property.
  plugins/in_kmsg/in_kmsg.c
  plugins/in_kmsg/in_kmsg.h
Labels: docs-required

#5730 filter_parser: use string as a default value
  plugins/filter_parser/filter_parser.c
Labels: docs-required

#5720 in_exec: use flb_calloc to fill NULL (#5715)
  plugins/in_exec/in_exec.c
Labels: docs-required

#5645 plugins: New Azure Kusto Output Plugin
  .gitignore
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/out_azure_kusto/CMakeLists.txt
  plugins/out_azure_kusto/azure_kusto.c
  plugins/out_azure_kusto/azure_kusto.h
  plugins/out_azure_kusto/azure_kusto_conf.c
  plugins/out_azure_kusto/azure_kusto_conf.h
  plugins/out_azure_kusto/azure_kusto_ingest.c
  plugins/out_azure_kusto/azure_kusto_ingest.h
  src/flb_upstream_node.c
Labels: docs-required

#5905 plugins: out_azure_kusto: removed deprecated header
  plugins/out_azure_kusto/azure_kusto_ingest.c
Labels: docs-required

#5907 workflows: windows: Use chocolatey's OpenSSL installer for linking OpenSSL (#5780 backport to 1.9)
  .github/workflows/call-build-windows.yaml
Labels: docs-required

#5836 out_stackdriver: add name label to the metrics emitted
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#5837 out_stackdriver: add name label to the metrics emitted
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#5910 openssl: remove deprecated SSL_load_error_strings
  src/tls/openssl.c
Labels: docs-required

#5883 pack: Fix Heap-double-free in flb_pack_state_reset
  src/flb_pack.c
Labels: docs-required

#5923 build: macos: openssl: Search homebrewed OpenSSL installed directory
  cmake/homebrew.cmake
Labels: docs-required

#5927 lib: macos: Call pthread_cancel explicitly to ensure thread termination
  src/flb_lib.c
Labels: docs-required

#5926 test: runtime: filter_stdout: Ensure TLS(thread local storage) initialization on macOS.
  tests/runtime/filter_stdout.c
Labels: docs-required

#5598 out_kafka: add support to force flush when shutdown. (fluent#5593)
  plugins/out_kafka/kafka.c
Labels: docs-required

#5947 docs: remove codebase structure
  .github/workflows/docs-generate.yaml
  README.md
Labels: docs-required

#5953 filter_tensorflow: change flb_info to flb_plg_info inside function
  plugins/filter_tensorflow/tensorflow.c
Labels: docs-required

#5937 multiline: fix flush timeout logic (fixes #5504)
  src/multiline/flb_ml.c
  tests/internal/multiline.c
  tests/runtime/data/tail/parsers_multiline_json.conf
  tests/runtime/filter_multiline.c
  tests/runtime/in_tail.c
Labels: docs-required

#5961 workflows: update unit tests timeout.
  .github/workflows/unit-tests.yaml
Labels: docs-required
