Repository fluent/fluent-bit, pull requests merged in 2022-11, with the labels that each got.

#6315 workflows: windows OCI image release
  .github/workflows/call-build-images.yaml
  .github/workflows/staging-build.yaml
  .github/workflows/staging-release.yaml
Labels: docs-required

#6316 packaging: fix publish script
  packaging/server/publish-all.sh
  packaging/test-release-packages.sh
Labels: packaging

#6336 workflows: update deprecated set output workflows
  .github/actions/generate-package-build-matrix/action.yaml
  .github/actions/release-bucket-sync/action.yaml
  .github/actions/release-server-sync/action.yaml
  .github/workflows/build-master-packages.yaml
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/call-build-macos.yaml
  .github/workflows/call-test-images.yaml
  .github/workflows/call-test-packages.yaml
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/pr-perf-test.yaml
  .github/workflows/release-sync.yaml
  .github/workflows/staging-build.yaml
  .github/workflows/staging-release.yaml
Labels: docs-required

#6332 lib: cmetrics: upgrade to v0.5.5
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_decode_msgpack.h
  lib/cmetrics/src/cmt_counter.c
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_encode_msgpack.c
Labels: docs-required

#6338 lib: monkey: upgrade to 24e68bbf
  lib/monkey/.gitignore
  lib/monkey/CMakeLists.txt
  lib/monkey/include/monkey/mk_config.h
  lib/monkey/include/monkey/mk_core.h
  lib/monkey/include/monkey/mk_core/mk_list.h
  lib/monkey/mk_core/CMakeLists.txt
  lib/monkey/mk_core/mk_event_kqueue.c
  lib/monkey/mk_core/mk_event_libevent.c
  lib/monkey/mk_server/mk_lib.c
  lib/monkey/mk_server/mk_server.c
  lib/monkey/mk_server/monkey.c
Labels: docs-required

#6311 build: wasm: Disable WASM for *BSD
  CMakeLists.txt
Labels: docs-required

#6304 tests: internal: fuzzers: add ctrace fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/ctrace_fuzzer.c
Labels: docs-required

#6321 out_forward: Make forwardable for msgpack payloads of ctraces and cmetrics
  plugins/out_forward/forward.c
  plugins/out_forward/forward.h
Labels: docs-required

#6353 lib: cmetrics: upgrade to v0.5.6
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_decode_msgpack.h
  lib/cmetrics/include/cmetrics/cmt_metric.h
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_decode_opentelemetry.c
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/src/cmt_summary.c
  lib/cmetrics/tests/data/pr_168.txt
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#6346 tests: internal: parser_regex: add test for parser_regex
  tests/internal/CMakeLists.txt
  tests/internal/parser_regex.c
Labels: docs-required

#6299 fluent-bit: fix return type for flb_cf_section_property_add.
  src/fluent-bit.c
Labels: docs-required

#6078 build: Enable LTO for release builds
  CMakeLists.txt
  packaging/distros/ubuntu/Dockerfile
Labels: ci, packaging

#6370 engine: failed/expired retries is an error level event
  src/flb_engine.c
Labels: docs-required

#6371 multiline: do not permanently set ml group time to the first log time.
  src/multiline/flb_ml.c
Labels: docs-required

#6345 tests: internal: parser_ltsv: add test for parser_ltsv
  tests/internal/CMakeLists.txt
  tests/internal/parser_ltsv.c
Labels: docs-required

#6320 tests: internal: parser_json: add test for parser_json
  tests/internal/CMakeLists.txt
  tests/internal/parser_json.c
Labels: docs-required

#6288 upstream: fix the stuck issue happened in Windows Server 2016 and 2019.
  src/flb_upstream.c
Labels: docs-required

#6376 packaging: disable ARM build for AL2022 due to time
  packaging/build-config.json
Labels: docs-required

#6375 wix: windows: Tweak wix installer for fluent-bit 2.0
  cpack/wix/WIX.template.in.cmakein
Labels: docs-required

#6383 chunk-trace: add a warning to enable tracing when it is not enabled.
  src/flb_chunk_trace.c
Labels: docs-required

#6327 filter_ecs: enhancements
  plugins/filter_ecs/ecs.c
  plugins/filter_ecs/ecs.h
Labels: docs-required

#6291 in_tail: fix st_mtime timestamp format
  plugins/in_tail/win32/stat.c
Labels: docs-required

#6302 in_node_exporter_metrics: fix set vmstat metrics as counter metrics
  plugins/in_node_exporter_metrics/ne_vmstat_linux.c
Labels: docs-required

#6268 windows: enable ECS filter
  cmake/windows-setup.cmake
Labels: docs-required

#6238 in_cpu: fix pointer to v_cpuid
  plugins/in_cpu/cpu.c
Labels: docs-required

#6391 workflows: fix typo in windows container releases
  .github/workflows/staging-release.yaml
Labels: docs-required

#6381 multiline: do not permanently set ml group time to the first log time (backported from 2.0).
  src/multiline/flb_ml.c
Labels: docs-required

#6255 trace: use ring buffers from the main thread to the trace pipeline.
  plugins/in_emitter/emitter.c
  src/flb_chunk_trace.c
Labels: docs-required

#6403 upstream_ha: Fixed extra parameters storage
  src/flb_upstream_ha.c
Labels: docs-required

#6232 out_opentelemetry: add gzip compression
  plugins/out_opentelemetry/opentelemetry.c
  plugins/out_opentelemetry/opentelemetry.h
  plugins/out_opentelemetry/opentelemetry_conf.c
Labels: docs-required

#6326 aws: different user agent on windows vs linux
  src/aws/flb_aws_util.c
Labels: docs-required

#6325 aws: different user agent on windows vs linux
  src/aws/flb_aws_util.c
Labels: AWS, docs-required

#6269 windows: enable ECS filter
  cmake/windows-setup.cmake
Labels: docs-required

#5930 out_datadog: fix/add error handling for all flb_sds calls
  plugins/out_datadog/datadog.c
  plugins/out_datadog/datadog_conf.c
  plugins/out_datadog/datadog_remap.c
  plugins/out_datadog/datadog_remap.h
Labels: docs-required

#5929 out_datadog: fix/add error handling for all flb_sds calls
  plugins/out_datadog/datadog.c
  plugins/out_datadog/datadog_conf.c
  plugins/out_datadog/datadog_remap.c
  plugins/out_datadog/datadog_remap.h
Labels: docs-required

#5898 filter_ecs: new filter for AWS ECS Metadata
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/filter_ecs/CMakeLists.txt
  plugins/filter_ecs/ecs.c
  plugins/filter_ecs/ecs.h
  tests/runtime/CMakeLists.txt
  tests/runtime/filter_ecs.c
Labels: AWS

#6405 dockerfiles: fix typo
  packaging/distros/debian/Dockerfile
Labels: packaging

#5770 out_es: fix es bulk buffer overrun
  plugins/out_es/es_bulk.c
Labels: exempt-stale

#6396 out_es: fix es bulk buffer overrun
  plugins/out_es/es_bulk.c
Labels: docs-required

#6425 io: restore connection registration after async io operation
  src/flb_io.c
Labels: docs-required

#6417 out_forward: fix concurrency issue when operating in UDS mode
  plugins/out_forward/forward.c
  plugins/out_forward/forward.h
Labels: docs-required

#6433 tls: restore connection registration after async io operation
  src/tls/flb_tls.c
Labels: docs-required

#6429 workflows: update packaging to remove Ubuntu 18 runners
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/remove-release.yaml
  .github/workflows/staging-release.yaml
Labels: ci

#6428 workflows: update unit test runner OS
  .github/workflows/unit-tests.yaml
Labels: ci

#6424 tests: internal: parser: fix warnings
  tests/internal/parser.c
Labels: docs-required

#6421 tests: internal: parser_logfmt: add test for parser_logfmt
  tests/internal/CMakeLists.txt
  tests/internal/parser_logfmt.c
Labels: docs-required

#6423 tests: runtime: out_tcp: remove unused variables
  tests/runtime/out_tcp.c
Labels: docs-required

#6368 parser: fix time zone offsets being dropped on Windows
  include/fluent-bit/flb_parser.h
  include/fluent-bit/flb_strptime.h
  include/fluent-bit/flb_time.h
  src/flb_parser.c
  src/flb_parser_json.c
  src/flb_parser_logfmt.c
  src/flb_parser_ltsv.c
  src/flb_parser_regex.c
  src/flb_strptime.c
  tests/runtime/filter_parser.c
Labels: docs-required

#6439 out_tcp: new 'raw_message_key' option
  plugins/out_tcp/tcp.c
  plugins/out_tcp/tcp.h
  plugins/out_tcp/tcp_conf.c
Labels: docs-required

#6445 packaging: handle change in location of JSON schema for release
  packaging/server/publish-all.sh
Labels: packaging

#6444 packaging: add missing debian conffiles
  CMakeLists.txt
  cpack/debian/conffiles
Labels: packaging

#6455 packaging: add extra repo creation details
  packaging/server/aptly.conf
  packaging/server/create-aptly-repo.sh
Labels: packaging

#5902 out_s3: add store_dir_limit_size to limit S3 disk usage
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
  plugins/out_s3/s3_store.c
Labels: AWS

#5903 out_s3: add store_dir_limit_size to limit S3 disk usage
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
  plugins/out_s3/s3_store.c
Labels: AWS

#6467 workflows: ensure 1.9 containers do not update latest tag
  .github/workflows/staging-release.yaml
Labels: ci

#6450 out_udp: new output plugin added
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_udp/CMakeLists.txt
  plugins/out_udp/udp.c
  plugins/out_udp/udp.h
  plugins/out_udp/udp_conf.c
  plugins/out_udp/udp_conf.h
Labels: docs-required

#5933 init: systemd: allow to set environment variables from file
  init/systemd.in
Labels: docs-required, packaging

#6481 in_syslog: new raw_message_key option
  plugins/in_syslog/syslog.c
  plugins/in_syslog/syslog.h
  plugins/in_syslog/syslog_prot.c
Labels: docs-required
