Repository fluent/fluent-bit, pull requests merged in 2022-12, with the labels that each got.

#6489 openssl: add SSL_ERROR_SYSCALL case
  src/tls/openssl.c
Labels: docs-required

#6463 parser: fix overflow
  src/flb_parser.c
Labels: docs-required

#6469 proxy: fix memory bugs when use same golang output plugin multiple times
  include/fluent-bit/flb_input.h
  include/fluent-bit/flb_output.h
  include/fluent-bit/flb_plugins.h.in
  src/flb_output.c
  src/flb_plugin_proxy.c
  src/proxy/go/go.c
  src/proxy/go/go.h
Labels: docs-required

#6456 workflows: automatically create release during the release process
  .github/workflows/staging-release.yaml
Labels: ci

#6452 out_kafka: fix segmentation fault issue while produce_message
  plugins/out_kafka/kafka.c
Labels: docs-required

#6440 tests: runtime: in_tail: remove unused var
  tests/runtime/in_tail.c
Labels: docs-required

#6496 build: wamrc: Make buildable with LLVM 15
  CMakeLists.txt
  cmake/FindLibEdit.cmake
Labels: docs-required

#6508 dockerfiles: update systemd to v251.3
  dockerfiles/Dockerfile
Labels: docs-required

#6500 filter_throttle: Fix print_status being partially uninitialized
  plugins/filter_throttle/throttle.c
Labels: docs-required

#6471 build: input_chunk_raw does not depend on FLB_IN_STORAGE_BACKLOG
  src/flb_input_chunk.c
Labels: docs-required

#6529 calyptia: concatenate configuration as raw strings.
  plugins/custom_calyptia/calyptia.c
Labels: docs-required

#6543 opensearch: fix '(null)' index when using record accessor and id_key/generate_id.
  plugins/out_opensearch/opensearch.c
  tests/runtime/out_opensearch.c
Labels: docs-required

#6549 workflows: tweak keyless container signing
  .github/workflows/call-build-images.yaml
  .github/workflows/staging-release.yaml
Labels: docs-required

#6553 calyptia: fix segfault when concatenating custom configuration.
  plugins/custom_calyptia/calyptia.c
  tests/runtime/CMakeLists.txt
  tests/runtime/custom_calyptia_test.c
Labels: docs-required

#6100 parser: logfmt: Allow the logfmt parser to reject messages that have keys without values
  include/fluent-bit/flb_parser.h
  src/flb_parser.c
  src/flb_parser_logfmt.c
  src/multiline/flb_ml_parser_cri.c
  src/multiline/flb_ml_parser_docker.c
  tests/internal/fuzzers/engine_fuzzer.c
  tests/internal/fuzzers/parse_json_fuzzer.c
  tests/internal/fuzzers/parse_logfmt_fuzzer.c
  tests/internal/fuzzers/parse_ltsv_fuzzer.c
  tests/internal/fuzzers/parser_fuzzer.c
  tests/runtime/filter_parser.c
Labels: docs-required

#6561 stream: fixed an condition that caused concurrency issues
  include/fluent-bit/flb_stream.h
Labels: docs-required

#6575 cf_fluentbit: print config file load error
  src/config_format/flb_cf_fluentbit.c
Labels: docs-required

#6572 out_prometheus_exporter: add content-type(#6554)
  plugins/out_prometheus_exporter/prom_http.c
Labels: docs-required

#6568 in_windows_exporter_metrics: cpu: Don't compare float values directly
  plugins/in_windows_exporter_metrics/we_cpu.c
Labels: docs-required

#6550 packaging: provide more options to build packages with
  packaging/build.sh
  packaging/distros/amazonlinux/Dockerfile
  packaging/distros/centos/Dockerfile
  packaging/distros/debian/Dockerfile
  packaging/distros/raspbian/Dockerfile
  packaging/distros/ubuntu/Dockerfile
Labels: packaging

#6546 tests: internal: fuzzers: extend ctrace fuzzer
  tests/internal/fuzzers/ctrace_fuzzer.c
Labels: docs-required

#6394 tests: internal: pack: add test case for FLB_PACK_JSON_DATE*
  tests/internal/pack.c
Labels: docs-required

#6574 out_s3: always use sync IO mode
  plugins/out_s3/s3.c
Labels: docs-required

#6579 workflows: fix missing slash in signing
  .github/workflows/call-build-images.yaml
Labels: docs-required

#6582 in_tail: remove extra fstat() syscall and remove unused function
  plugins/in_tail/tail_file.c
Labels: docs-required

#6395 out_kafka: support iso8601_ns format
  plugins/out_kafka/kafka.c
  plugins/out_kafka/kafka_config.c
  plugins/out_kafka/kafka_config.h
Labels: docs-required

#6453 stackdriver: cache token expiration and use it when using cached tokens
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#6602 lib:cmetrics: upgrade to v0.5.8
  lib/cmetrics/.github/workflows/packages.yaml
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/cmake/headers.cmake
  lib/cmetrics/create-submoduled-tarball.sh
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/tests/data/issue_6534.txt
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#6601 lib: ctraces: ugprade to v0.2.7
  lib/ctraces/CMakeLists.txt
  lib/ctraces/src/ctr_decode_msgpack.c
  lib/ctraces/src/ctr_scope.c
  lib/ctraces/src/ctr_span.c
Labels: docs-required

#6611 CMakeLists: use FLB_DEFINTION for FLB_HAVE_*(#6519)
  CMakeLists.txt
Labels: docs-required

#6605 config: add safety checks in config_exit
  src/flb_config.c
Labels: docs-required

#6606 config: bail if multiline failed initialization
  src/flb_config.c
Labels: docs-required

#6608 config: fix two leaks
  src/flb_config.c
Labels: docs-required

#6609 parser: free time_fmt_full during interim cleanup
  src/flb_parser.c
Labels: docs-required

#6610 parser: fix two leaks
  src/flb_parser.c
Labels: docs-required

#6623 tests: internal: utils: add test case for flb_utils_split
  tests/internal/utils.c
Labels: docs-required

#6617 out_s3: in 2.0 series default to on/true for Preserve_Data_Ordering
  plugins/out_s3/s3.c
Labels: docs-required
