Repository fluent/fluent-bit, pull requests merged in 2022-05, with the labels that each got.

#5379 out_azure: fix typo which generates segv
  plugins/out_azure/azure.c
Labels: docs-required

#5406 workflows: resolve 1.8 container build issue
  .github/workflows/call-build-images.yaml
Labels: ci

#5413 workflows: add container build workflow
  .github/workflows/build-branch-containers.yaml
  .github/workflows/call-build-images.yaml
Labels: ci

#5423 workflows: resolve missing debug source
  .github/workflows/build-branch-containers.yaml
  .github/workflows/call-build-images.yaml
  .github/workflows/cron-unstable-build.yaml
Labels: bug, ci

#5367 cpack: build: msi: Support MSI installer with CPack WiX generator
  CMakeLists.txt
  cpack/wix/WIX.template.in
Labels: docs-required

#5429 in_systemd: fix 'db.sync' property (#5426)
  plugins/in_systemd/systemd.c
Labels: docs-required

#5373 in_systemd: Don't insert rows if flb_sqldb_query fails
  plugins/in_systemd/systemd_db.c
Labels: docs-required

#5390 record_accessor: add append API, flb_ra_append_kv_pair
  include/fluent-bit/flb_ra_key.h
  include/fluent-bit/flb_record_accessor.h
  src/flb_ra_key.c
  src/flb_record_accessor.c
  tests/internal/record_accessor.c
Labels: docs-required

#5444 packaging: add options to parameterise server/key for testing
  .github/workflows/docs-generate.yaml
  CODEOWNERS
  install.sh
  packaging/test-release-packages.sh
  packaging/testing/smoke/packages/Dockerfile.amazonlinux2
  packaging/testing/smoke/packages/Dockerfile.centos7
  packaging/testing/smoke/packages/Dockerfile.centos8
  packaging/testing/smoke/packages/Dockerfile.debian10
  packaging/testing/smoke/packages/Dockerfile.debian11
  packaging/testing/smoke/packages/Dockerfile.ubuntu1804
  packaging/testing/smoke/packages/Dockerfile.ubuntu2004
  packaging/testing/smoke/packages/run-package-tests.sh
Labels: docs-required

#5436 out_stackdriver: Initialize the metadata_server value to NULL
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#5451 workflows: add post-release test job
  .github/workflows/staging-release.yaml
Labels: docs-required

#5461 workflows: correctly replace env vars from generated script.
  install.sh
Labels: docs-required

#5469 fstore: ensure the chunk is up while modifying it
  src/flb_fstore.c
Labels: docs-required

#5470 in_opentelemetry: Fixed the event type so OTel metrics
  plugins/in_opentelemetry/opentelemetry.c
Labels: docs-required

#5484 workflows: ensure we substitute variables
  install.sh
  packaging/test-release-packages.sh
Labels: docs-required

#4487 filter_kubernetes: add option kube_token_ttl (#4352)
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kube_meta.c
  plugins/filter_kubernetes/kubernetes.c
Labels: docs-required

#5494 workflows: unstable ci updates
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-windows.yaml
  .github/workflows/cron-unstable-build.yaml
Labels: docs-required
