Repository fluent/fluent-bit, pull requests merged in 2022-01, with the labels that each got.

#4565 workflows: add release branch PR info
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: ci

#4577 lib: monkey: sync fix for config reader
  lib/monkey/mk_core/mk_rconf.c
Labels: docs-required

#4563 out_cloudwatch_logs: Fix invalid memory access bug #4425
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#4440 metrics: silent gcc warning
  src/flb_metrics.c
Labels: docs-required

#4502 aws: fix error message
  src/aws/flb_aws_credentials_sts.c
Labels: AWS

#4379 in_nginx_metrics: add NGINX Plus metrics
  plugins/in_nginx_exporter_metrics/nginx.c
  plugins/in_nginx_exporter_metrics/nginx.h
  plugins/in_nginx_exporter_metrics/nginx_status_config.h
Labels: docs-required

#4100 openssl: Fix return value from tls_net_read.
  src/tls/flb_tls.c
  src/tls/openssl.c
Labels: docs-required

#4474 upstream: add new option 'net.connect_timeout_log_error' (#4473)
  include/fluent-bit/flb_network.h
  src/flb_upstream.c
Labels: docs-required

#4079 out_es: support write_operation option
  plugins/out_es/es.c
  plugins/out_es/es.h
  plugins/out_es/es_bulk.h
  plugins/out_es/es_conf.c
  tests/runtime/out_elasticsearch.c
Labels: docs-required

#4184 io: support timeout on synchronous calls
  include/fluent-bit/aws/flb_aws_imds.h
  include/fluent-bit/flb_network.h
  src/aws/flb_aws_credentials_ec2.c
  src/aws/flb_aws_imds.c
  src/flb_io.c
  src/flb_network.c
  tests/internal/aws_credentials_ec2.c
Labels: docs-required

#4604 out_cloudwatch_logs: Fix invalid memory access bug #4425 backport to v1.8
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#4567 dockerfiles: backport systemd lib fixes from #3177 to 1.8
  dockerfiles/Dockerfile.arm32v7
  dockerfiles/Dockerfile.arm64v8
  dockerfiles/Dockerfile.x86_64
  dockerfiles/Dockerfile.x86_64-master
  dockerfiles/Dockerfile.x86_64-master_debug
Labels: backport to v1.8.x

#4335 out_file plugin : add option create output directory if does not exist.
  plugins/out_file/file.c
Labels: docs-required

#4601 workflows: release promotion job updates
  .github/actions/release-server-sync/action.yaml
  .github/workflows/remove-release.yaml
  .github/workflows/staging-release.yaml
  packaging/remove-version.sh
  packaging/testing/smoke/packages/local-test-all.sh
  packaging/update-repos.sh
Labels: packaging

#4605 tests: internal: timeout: added coroutine hang test case
  tests/internal/CMakeLists.txt
  tests/internal/timeout.c
Labels: docs-required

#4622 lib: monkey: sync inject enhancement and list fixes
  lib/monkey/include/monkey/mk_core/mk_event.h
  lib/monkey/include/monkey/mk_core/mk_list.h
  lib/monkey/mk_core/mk_event.c
  lib/monkey/mk_core/mk_event_epoll.c
  lib/monkey/mk_core/mk_event_kqueue.c
  lib/monkey/mk_core/mk_event_libevent.c
  lib/monkey/mk_core/mk_event_select.c
Labels: docs-required

#4623 1.8: backport of lib/monkey event injection and list fixes
  lib/monkey/include/monkey/mk_core/mk_event.h
  lib/monkey/include/monkey/mk_core/mk_list.h
  lib/monkey/mk_core/mk_event.c
  lib/monkey/mk_core/mk_event_epoll.c
  lib/monkey/mk_core/mk_event_kqueue.c
  lib/monkey/mk_core/mk_event_libevent.c
  lib/monkey/mk_core/mk_event_select.c
Labels: docs-required

#4637 workflows: fix missing character for debug tag
  .github/workflows/call-build-images.yaml
Labels: packaging

#4638 workflows: restrict concurrency of integration tests
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/staging-test.yaml
Labels: docs-required

#4639 workflows: restrict concurrency of staging/release process
  .github/workflows/staging-build.yaml
  .github/workflows/staging-release.yaml
Labels: packaging

#4590 in_tail: enhance handling of high number of static files (#3947)
  plugins/in_tail/tail.c
  plugins/in_tail/tail.h
  plugins/in_tail/tail_config.h
Labels: docs-required

#4655 plugins: in_exec: don't eat last character of plugin output
  plugins/in_exec/in_exec.c
Labels: docs-required

#4496 plugins: in_exec: don't eat last character of plugin output
  plugins/in_exec/in_exec.c
Labels: backport to v1.8.x

#4665 upstream: moved event injection to the right place
  src/flb_upstream.c
Labels: docs-required

#4663 1.8: backport ra check #4517
  plugins/out_forward/forward.c
Labels: docs-required

#4659 1.8: backport event timeout unit test
  tests/internal/CMakeLists.txt
  tests/internal/timeout.c
Labels: docs-required

#4596 out_splunk: new option 'http_debug_bad_request'
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk.h
  plugins/out_splunk/splunk_conf.c
Labels: docs-required

#4668 1.8: backport #4596
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk.h
  plugins/out_splunk/splunk_conf.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4592 io: support fd based read/write
  include/fluent-bit/flb_io.h
  src/flb_io.c
Labels: docs-required

#4589 tests: runtime: in_tail: remove unused val
  tests/runtime/in_tail.c
Labels: docs-required

#4591 filter_rewrite_tag: set 'keep' before emitting(#4518)
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#4673 io: check connection error only on net_io_read
  src/flb_io.c
Labels: docs-required

#4672 in_forward: clear out_tag before using(#4670)
  plugins/in_forward/fw_prot.c
Labels: docs-required

#4669 filter_rewrite_tag: set 'keep' before emitting(#4518) for 1.8
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#4675 1.8: backport #4672
  plugins/in_forward/fw_prot.c
Labels: docs-required

#4677 out_stackdriver: protect against undefined metadata (#4664)
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#4678 1.8: out_stackdriver: protect against undefined metadata (#4664)
  plugins/out_stackdriver/stackdriver.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4643 dockerfiles: add OCI annotations
  dockerfiles/Dockerfile.arm32v7
  dockerfiles/Dockerfile.arm64v8
  dockerfiles/Dockerfile.multiarch
  dockerfiles/Dockerfile.x86_64
  dockerfiles/Dockerfile.x86_64-debug
Labels: packaging

#4685 workflows: add classic mode docker build test
  .github/workflows/pr-image-tests.yaml
  dockerfiles/Dockerfile.arm64v8
  dockerfiles/Dockerfile.x86_64
  dockerfiles/Dockerfile.x86_64-1_7
  dockerfiles/Dockerfile.x86_64-debug
  dockerfiles/Dockerfile.x86_64-master
  dockerfiles/Dockerfile.x86_64-master_debug
Labels: docs-required

#4679 build: Bundle fluent-bit-win32.conf only in Windows installers
  src/CMakeLists.txt
Labels: docs-required

#4686 dockerfiles: distroless for multiarch
  .github/workflows/pr-image-tests.yaml
  dockerfiles/Dockerfile.multiarch
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4701 in_storage_backlog: do not abort if chunk cannot be processed
  plugins/in_storage_backlog/sb.c
Labels: docs-required

#4702 1.8: in_storage_backlog: do not abort if chunk cannot be processed
  plugins/in_storage_backlog/sb.c
Labels: docs-required

#4704 lib: chunkio: upgrade to v1.1.6
  lib/chunkio/CMakeLists.txt
  lib/chunkio/include/chunkio/cio_file.h
  lib/chunkio/src/cio_file.c
Labels: docs-required
