Repository fluent/fluent-bit, pull requests merged in 2022-04, with the labels that each got.

#5212 filter_parser: mark 'unescape_key' as a deprecated property
  plugins/filter_parser/filter_parser.c
Labels: docs-required

#5078 multiline: cri: Use non-greedy parsing for parsing time
  src/multiline/flb_ml_parser_cri.c
Labels: docs-required

#4947 out_cloudwatch_logs: handle DataAlreadyAcceptedException response
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#4948 out_cloudwatch_logs: handle DataAlreadyAcceptedException response
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#5249 tls: mbedtls: retry read/write
  src/tls/mbedtls.c.in
Labels: docs-required

#5226 out_s3: add storage_class support in multipart upload mode
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
  plugins/out_s3/s3_multipart.c
Labels: docs-required

#5011 out_lib: change windows-setup.cmake to use FLB_OUT_LIB
  CMakeLists.txt
  cmake/windows-setup.cmake
  examples/CMakeLists.txt
  tests/runtime/CMakeLists.txt
Labels: docs-required

#5248 workflows: support 1.8 branch builds plus MacOS (and Windows for staging)
  .github/actions/generate-package-build-matrix/action.yaml
  .github/workflows/README.md
  .github/workflows/build-master-packages.yaml
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/call-build-macos.yaml
  .github/workflows/call-build-windows.yaml
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/pr-windows-build.yaml
  .github/workflows/staging-build.yaml
Labels: ci, packaging

#5262 out_stackdriver: fix wrong check of connection
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#5268 workflows: resolve packaging release issues
  .github/workflows/call-build-windows.yaml
  packaging/update-repos.sh
Labels: ci

#5261 dockerfiles: Add a dockerfile for windows for 1.8
  dockerfiles/Dockerfile.windows
  dockerfiles/README.md
Labels: packaging

#5227 in_exec: fix using interval from config map
  plugins/in_exec/in_exec.c
Labels: docs-required

#5247 build: cpack: Create macOS installer
  CMakeLists.txt
  conf/fluent-bit-macos.conf
  cpack/macos/fluent-bit.plist.cmakein
  cpack/macos/welcome.txt.cmakein
  src/CMakeLists.txt
Labels: docs-required

#5266 in_storage_backlog: skip corrupted chunks
  plugins/in_storage_backlog/sb.c
Labels: docs-required

#5280 workflows: Install building dependencies on macOS
  .github/workflows/call-build-macos.yaml
Labels: docs-required

#5281 workflows: move unstable releases to separate repo
  .github/workflows/cron-unstable-build.yaml
Labels: docs-required

#5258 workflows: handle 1.8 container builds and image tagging by major version
  .github/workflows/call-build-images.yaml
Labels: docs-required

#5270 workflows: windows release artefacts
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-macos.yaml
  .github/workflows/call-build-windows.yaml
  .github/workflows/staging-build.yaml
  packaging/server/publish-all.sh
  packaging/test-release-packages.sh
  packaging/windows-checksums.sh
Labels: docs-required

#5290 workflows: resolve refactoring conflicts
  .github/workflows/call-build-images.yaml
Labels: docs-required

#5297 workflows: refactor S3 sync to common action and add checks
  .github/actions/sync-to-bucket/action.yaml
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/call-build-macos.yaml
  .github/workflows/call-build-windows.yaml
  .github/workflows/staging-build.yaml
Labels: docs-required

#5288 build: macos: Split macOS specific cmake rules into cmake/macos-setup.cmake
  CMakeLists.txt
  cmake/macos-setup.cmake
Labels: docs-required

#5306 packaging: update smoke tests to verify inline LUA
  packaging/testing/smoke/container/fluent-bit.conf
  packaging/testing/smoke/container/fluent-bit.yaml
Labels: docs-required

#5307 ci: add codebase visualisation
  .github/workflows/docs-generate.yaml
  README.md
Labels: docs-required

#5321 lib: cmetrics: upgrade to v0.3.1
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_prometheus.c
Labels: docs-required

#5322 in_prometheus_scrape: log call format string issue fixed
  plugins/in_prometheus_scrape/prom_scrape.c
Labels: docs-required

#5319 filter_nightfall: add input instance to filter callback
  plugins/filter_nightfall/nightfall.c
Labels: docs-required

#5318 tests: runtime: filter_lua: add test code for 'code'
  tests/runtime/filter_lua.c
Labels: docs-required

#5317 tests: runtime: in_forward: add test for in_forward
  tests/runtime/CMakeLists.txt
  tests/runtime/in_forward.c
Labels: docs-required

#5316 filter_grep: check if flb_strndup returns NULL
  plugins/filter_grep/grep.c
Labels: docs-required

#5315 filter_nest: check if flb_strndup returns NULL
  plugins/filter_nest/nest.c
Labels: docs-required

#5269 csv: Implement CSV support library
  include/fluent-bit/flb_csv.h
  src/CMakeLists.txt
  src/flb_csv.c
  src/flb_file.c
  tests/internal/CMakeLists.txt
  tests/internal/csv.c
Labels: docs-required

#5264 filter_nest: fix wildcard config to allow multiple entries
  plugins/filter_nest/nest.c
Labels: docs-required

#5273 tests: runtime: filter_checklist: add test code
  tests/runtime/CMakeLists.txt
  tests/runtime/filter_checklist.c
Labels: docs-required

#4827 out_cloudwatch_logs: Only create log group if it does not already exist
  plugins/out_cloudwatch_logs/cloudwatch_api.c
  plugins/out_cloudwatch_logs/cloudwatch_api.h
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
Labels: docs-required

#5176 out_stackdriver: add static labels defined in configuration
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
  tests/runtime/out_stackdriver.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok, docs-required

#3198 out_stackdriver: Ensure URL encoding for the OAuth2 request, and send to the more modern endpoint.
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok

#5285 filter_multiline: Add Fluentd Log Driver Partial Message Support
  plugins/filter_multiline/CMakeLists.txt
  plugins/filter_multiline/ml.c
  plugins/filter_multiline/ml.h
  plugins/filter_multiline/ml_concat.c
  plugins/filter_multiline/ml_concat.h
  tests/runtime/filter_multiline.c
Labels: docs-required

#5340 workflows: prevent re-trigger of generation workflow on its own changes
  .github/workflows/docs-generate.yaml
Labels: ci

#5348 codeowners: update in_docker owner
  CODEOWNERS
Labels: docs-required

#5351 input: close event channel on destroy
  src/flb_input.c
Labels: docs-required

#5353 tests: runtime: in_forward: use socket wrapper
  tests/runtime/in_forward.c
Labels: docs-required

#5354 tests: runtime: in_statsd: add test code
  tests/runtime/CMakeLists.txt
  tests/runtime/in_statsd.c
Labels: docs-required

#5102 parser: fix null dereference
  src/flb_parser.c
Labels: docs-required

#4054 strptime: typecast to avoid signed overflow
  src/flb_strptime.c
Labels: Stale, docs-required

#5100 output: fix potential NULL deref
  src/flb_output.c
Labels: docs-required

#5190 in_docker: add missing include/exclude property
  plugins/in_docker/docker.c
Labels: docs-required

#5271 filter_lua: add return for discarding all records (#5251)
  plugins/filter_lua/lua.c
  tests/runtime/filter_lua.c
Labels: docs-required

#5189 in_docker: fix error handling if some resources not found
  plugins/in_docker/docker.c
Labels: docs-required

#3835 ra: support flb_ra_update_kv_pair
  include/fluent-bit/flb_ra_key.h
  include/fluent-bit/flb_record_accessor.h
  src/flb_ra_key.c
  src/flb_record_accessor.c
  tests/internal/record_accessor.c
Labels: waiting-for-user

#5122 filter_record_modifier: add error check for flb_strndup(#5103)
  plugins/filter_record_modifier/filter_modifier.c
Labels: docs-required

#5130 in_opentelemetry: add missing header
  plugins/in_opentelemetry/http_conn.h
Labels: docs-required

#5368 Add terraform to integration tests CI.
  .github/workflows/call-integration-test.yaml
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/staging-test.yaml
Labels: docs-required

#5369 workflows: fix integration tests secrets vars
  .github/workflows/call-integration-test.yaml
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/staging-test.yaml
Labels: docs-required

#5370 workflows: fix integration tests secrets vars
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/staging-test.yaml
Labels: docs-required

#5372 workflows: rename parameter to terraform_api_token
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/staging-test.yaml
Labels: docs-required
