Repository fluent/fluent-bit, pull requests merged in 2022-09, with the labels that each got.

#5969 flb_network: Fix argument glitch when detection of unix socket support is failed
  src/flb_network.c
Labels: docs-required

#5970 workflows: fix integration test zone for GKE
  .github/workflows/call-run-integration-test.yaml
Labels: docs-required

#5976 scheduler: fixed an issue with the way in which timers were disabled
  src/flb_scheduler.c
Labels: docs-required

#5975 pack: Fix oss-fuzz crash
  src/flb_pack.c
Labels: docs-required

#5985 tests: internal: aws_util: Handle difference of strftime format handling
  tests/internal/aws_util.c
Labels: docs-required

#5982 1.9.8: pack backport fixes
  src/flb_pack.c
Labels: docs-required

#5986 tests: internal: fuzzers: fix index error
  tests/internal/fuzzers/multiline_fuzzer.c
Labels: docs-required

#5952 log: add flb_*_is_truncated functions to check if log will be truncated
  include/fluent-bit/flb_log.h
  src/flb_log.c
  tests/runtime/CMakeLists.txt
  tests/runtime/core_log.c
Labels: docs-required

#5988 strptime: fix signed overflow
  src/flb_strptime.c
Labels: docs-required

#5945 README: add requirements section
  README.md
Labels: docs-required

#5922 tests: runtime: in_fluentbit_metrics: add test code
  tests/runtime/CMakeLists.txt
  tests/runtime/in_fluentbit_metrics.c
Labels: docs-required

#5994 revert: "tests: macos fixes, mostly TLS initialization stuff" (#5980)
  lib/monkey/include/monkey/mk_core/mk_utils.h
  plugins/in_dummy_thread/in_dummy_thread.c
  src/flb_config.c
  src/flb_downstream.c
  src/flb_upstream.c
  tests/internal/config_format_fluentbit.c
  tests/internal/flb_event_loop.c
  tests/internal/flb_time.c
  tests/internal/fstore.c
  tests/internal/input_chunk.c
  tests/internal/metrics.c
  tests/internal/pack.c
  tests/internal/record_accessor.c
  tests/internal/signv4.c
  tests/internal/stream_processor.c
  tests/internal/utils.c
  tests/runtime/config_map_opts.c
  tests/runtime/flb_tests_runtime.h.in
  tests/runtime/in_syslog.c
  tests/runtime/out_file.c
  tests/runtime/out_plot.c
  tests/runtime_shell/in_http_tls_expect.sh
  tests/runtime_shell/in_syslog_tcp_plaintext_expect.sh
  tests/runtime_shell/in_syslog_tcp_tls_expect.sh
  tests/runtime_shell/in_syslog_udp_plaintext_expect.sh
Labels: docs-required

#5997 ra_key: handle error case
  src/flb_ra_key.c
Labels: docs-required

#6006 plugin: out_file: macos: Fix incorrect behavior for creating directories with mkdir option
  plugins/out_file/file.c
Labels: docs-required

#6013 workflows: add override to allow partial staging build
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/staging-build.yaml
Labels: ci

#6028 core: rename macro __FILENAME__ as __FLB_FILENAME__
  CMakeLists.txt
  include/fluent-bit/flb_custom_plugin.h
  include/fluent-bit/flb_filter_plugin.h
  include/fluent-bit/flb_input_plugin.h
  include/fluent-bit/flb_log.h
  include/fluent-bit/flb_output_plugin.h
Labels: docs-required

#6032 lib: cmetrics: upgrade to v0.3.7
  lib/cmetrics/.github/workflows/build.yaml
  lib/cmetrics/.github/workflows/packages.yaml
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_decode_prometheus.h
  lib/cmetrics/include/cmetrics/cmt_log.h
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/src/cmt_decode_prometheus.y
  lib/cmetrics/tests/data/issue_fluent_bit_6021.txt
  lib/cmetrics/tests/decoding.c
  lib/cmetrics/tests/encoding.c
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#6033 lib: cmetrics: upgrade to v0.3.7
  lib/cmetrics/.github/workflows/build.yaml
  lib/cmetrics/.github/workflows/packages.yaml
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_decode_prometheus.h
  lib/cmetrics/include/cmetrics/cmt_log.h
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/src/cmt_decode_prometheus.y
  lib/cmetrics/tests/data/issue_fluent_bit_6021.txt
  lib/cmetrics/tests/decoding.c
  lib/cmetrics/tests/encoding.c
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#5731 pack: Fix read Stack-buffer-overflow READ in msgpack_sbuffer_write
  src/flb_pack.c
Labels: docs-required

#6038 parser: fix double-free
  src/flb_parser.c
Labels: docs-required

#6045 scheduler: set the `timer_fd` field in `schedule_request_now`
  src/flb_scheduler.c
Labels: docs-required

#6048 tests: runtime_shell: spread the ports so they don't collide
  tests/runtime_shell/in_http_tls_expect.sh
  tests/runtime_shell/in_syslog_tcp_plaintext_expect.sh
  tests/runtime_shell/in_syslog_tcp_tls_expect.sh
  tests/runtime_shell/in_syslog_udp_plaintext_expect.sh
  tests/runtime_shell/in_syslog_uds_dgram_plaintext_expect.sh
Labels: docs-required

#6039 packaging: provide centos 9 stream builds
  .github/actions/generate-package-build-matrix/action.yaml
  codebase-structure.svg
  dockerfiles/Dockerfile
  install.sh
  packaging/build-config.json
  packaging/distros/centos/Dockerfile
  packaging/local-build-all.sh
  packaging/test-release-packages.sh
  packaging/testing/smoke/container/container-smoke-test.sh
  packaging/testing/smoke/packages/Dockerfile.centos9
  packaging/testing/smoke/packages/test.sh
Labels: docs-required, packaging

#6004 developers: add code analysis tooling
  DEVELOPER_GUIDE.md
  run_code_analysis.sh
Labels: docs-required

#6046 packaging: add initial build support for Amazon Linux 2022
  packaging/distros/amazonlinux/Dockerfile
Labels: docs-required, packaging

#5073 bin: use EXIT_SUCCESS macro consistently
  src/fluent-bit.c
Labels: Stale, docs-required

#3087 Set Time_Keep On for cri parser (fix #3085)
  conf/parsers.conf
Labels: Stale

#6054 scripts: add netcat to code analysis helper script
  run_code_analysis.sh
Labels: docs-required

#5458 out_es: resolve domain name not found issue in cloud_id as it contains a port.
  plugins/out_es/es.h
  plugins/out_es/es_conf.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok

#6053 tests: core_chunk_trace: Enable chunk trace correctly
  tests/runtime/core_chunk_trace.c
Labels: docs-required

#6037 tests: internal: fuzzer: limit input size
  tests/internal/fuzzers/pack_json_state_fuzzer.c
Labels: docs-required

#6067 out_syslog: support preset configuration
  plugins/out_syslog/syslog.c
  plugins/out_syslog/syslog_conf.c
  plugins/out_syslog/syslog_conf.h
  tests/runtime/out_syslog.c
Labels: docs-required

#6072 workflows: fix dockerhub update workflow
  .github/workflows/update-dockerhub.yaml
  dockerfiles/dockerhub-description.md
Labels: ci

#6070 out_opentelemetry: fix conflicts in opentelemetry_common file
  plugins/out_opentelemetry/opentelemetry_common.pb-c.c
Labels: docs-required

#6106 lib: cfl: upgrade to v0.1.7
  lib/cfl/.github/actionlint-matcher.json
  lib/cfl/.github/workflows/build.yaml
  lib/cfl/.github/workflows/lint.yaml
  lib/cfl/.github/workflows/packages.yaml
  lib/cfl/CMakeLists.txt
  lib/cfl/include/cfl/cfl_sds.h
  lib/cfl/src/cfl_array.c
  lib/cfl/src/cfl_sds.c
  lib/cfl/tests/CMakeLists.txt
  lib/cfl/tests/sds.c
Labels: docs-required

#6092 metrics: storage: expose storage metrics by default as internal metrics
  include/fluent-bit/flb_input.h
  include/fluent-bit/flb_storage.h
  src/flb_config.c
  src/flb_input.c
  src/flb_metrics_exporter.c
  src/flb_storage.c
Labels: docs-required

#6117 config/yaml: make the name property explicit and unnest properties.
  src/config_format/flb_cf_yaml.c
  tests/internal/data/config_format/yaml/test/dummy_pipeline.yaml
Labels: docs-required

#6127 smoke-tests: update smoke test for new YAML format.
  packaging/testing/smoke/container/fluent-bit.yaml
Labels: docs-required
