Repository fluent/fluent-bit, pull requests merged in 2022-07, with the labels that each got.

#5638 filter_multiline: use flb_time API to get timestamp in millisecond
  plugins/filter_multiline/ml_concat.c
Labels: docs-required

#5672 workflows: fix incorrect label running
  .github/workflows/pr-perf-test.yaml
Labels: docs-required

#5127 exec: fix name of oneshot parameter
  plugins/in_exec/in_exec.c
Labels: docs-required

#5683 build: Fix building error for c-ares library on macOS
  CMakeLists.txt
Labels: docs-required

#5101 record_accessor: fix possible null-deref
  src/flb_record_accessor.c
Labels: docs-required

#5602 tests: internal: fuzzers: fix index error
  tests/internal/fuzzers/multiline_fuzzer.c
Labels: docs-required

#5605 input: return error code from cb_collect
  src/flb_input.c
Labels: docs-required

#5639 in_netif: add missing return type
  plugins/in_netif/in_netif.c
Labels: docs-required

#5456 tests: runtime: in_tail: add some test cases
  tests/runtime/in_tail.c
Labels: docs-required

#5129 filter_modify: add error check for flb_strndup(#5103)
  plugins/filter_modify/modify.c
Labels: Stale, docs-required

#4715 out_forward: support 'unix_path'
  plugins/out_forward/forward.c
  plugins/out_forward/forward.h
Labels: Stale, docs-required

#5291 filter_kubernetes: Add ability to change kubelet_host
  plugins/filter_kubernetes/kube_conf.c
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kubernetes.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok

#5688 s3: update S3 PutObjectSize to 1GB
  plugins/out_s3/s3.h
Labels: docs-required

#5694 tests: runtime: revert upstream tests
  tests/internal/CMakeLists.txt
  tests/internal/upstream.c
Labels: docs-required

#5696 workflows: resolve AWS sync issue due to client upgrade on runners
  .github/workflows/staging-release.yaml
Labels: ci

#5698 workflows: resolve AWS sync issue due to client upgrade on runners
  .github/actions/release-server-sync/action.yaml
Labels: docs-required

#5701 filter_expect: use flb_free instead of free
  plugins/filter_expect/expect.c
Labels: docs-required

#5655 in_tail: Add FreeBSD support
  CMakeLists.txt
  plugins/in_tail/tail_file.c
Labels: docs-required

#5677 out_stackdriver: removed unused variables
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#5742 input_thread: pause coll_fd when read pipe is closed
  src/flb_input_thread.c
Labels: docs-required

#5741 utils: use fclose when fstat failed(#4762)
  src/flb_utils.c
Labels: docs-required

#5758 workflows: resolve linting issue with unit tests
  .github/workflows/unit-tests.yaml
Labels: docs-required

#5637 out_s3: Add gzip compression support for multipart uploads
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#5780 workflows: windows: Use chocolatey's OpenSSL installer for linking OpenSSL
  .github/workflows/call-build-windows.yaml
Labels: ci, Windows, packaging, calyptia-lts

#5776 out_s3: Add gzip compression support for multipart uploads
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
Labels: docs-required

#5785 packaging: updates for Ubuntu Jammy
  .github/workflows/1.7.yaml
  .github/workflows/1.8.yaml
  .github/workflows/call-build-macos.yaml
  .github/workflows/staging-release.yaml
  packaging/server/aptly.conf
  packaging/server/publish-all.sh
  packaging/sync-releases-to-bucket.sh
  packaging/testing/smoke/packages/Dockerfile.ubuntu2204
  packaging/update-repos.sh
Labels: ci, packaging

#5695 out_cloudwatch_logs: skip counting empty events
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: AWS

#5789 out_cloudwatch_logs: skip counting empty events
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#5557 out_es: add option to compress payload
  plugins/out_es/es.c
  plugins/out_es/es.h
  plugins/out_es/es_conf.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok

#5804 workflows: update to call fluent-bit-ci int tests
  .github/workflows/call-integration-test.yaml
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
Labels: docs-required

#5805 workflows: fix branch for fluent-bit-ci calls
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
Labels: ci

#5806 workflows: fix workflow name for fluent-bit-ci calls
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
Labels: ci

#5807 workflows: add missing secret for int tests
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
Labels: docs-required

#5808 workflows: update for in-repo call
  .github/workflows/call-run-integration-test.yaml
  .github/workflows/master-integration-test.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/staging-test.yaml
Labels: ci
