Repository fluent/fluent-bit, pull requests merged in 2022-03, with the labels that each got.

#4941 out_plot: refactor to use config_map.
  plugins/out_plot/plot.c
Labels: docs-required

#4932 in_exec: refactor to use config_map.
  plugins/in_exec/in_exec.c
  plugins/in_exec/in_exec.h
Labels: docs-required

#4931 in_serial: refactor to use config_map.
  plugins/in_serial/in_serial.c
  plugins/in_serial/in_serial_config.c
  plugins/in_serial/in_serial_config.h
Labels: docs-required

#4929 in_tcp: refactor to use config_map.
  plugins/in_tcp/tcp.c
  plugins/in_tcp/tcp.h
  plugins/in_tcp/tcp_config.c
  plugins/in_tcp/tcp_conn.h
Labels: docs-required

#4925 in_dummy_thread: configmap support.
  plugins/in_dummy_thread/in_dummy_thread.c
Labels: docs-required

#4921 in_systemd: update to use config_map.
  plugins/in_systemd/systemd.c
  plugins/in_systemd/systemd_config.c
  plugins/in_systemd/systemd_config.h
Labels: docs-required

#4879 signv4: fix NULL dereference
  src/flb_signv4.c
Labels: docs-required

#4914 output_thread: backport sig 0xdeadbeef write 4 bytes, not 8 on 32bit machine
  src/flb_output_thread.c
Labels: docs-required

#4916 output_thread: master add 0xdeadbeef cast to avoid compiler warning
  src/flb_output_thread.c
Labels: docs-required

#4826 out_cloudwatch_logs: Only create log group if it does not already exist
  plugins/out_cloudwatch_logs/cloudwatch_api.c
  plugins/out_cloudwatch_logs/cloudwatch_api.h
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
Labels: docs-required

#4962 appveyor: backport updates to build td-agent-bit
  appveyor.yml
Labels: docs-required

#4963 workflows: initial Windows CI
  .github/workflows/pr-image-tests.yaml
  .github/workflows/windows-build.yaml
  dockerfiles/Dockerfile.windows
  dockerfiles/Dockerfile.windows.devel
Labels: ci, Windows, packaging

#4973 1.8: container definition removal
  dockerfiles/Dockerfile.arm32v7
  dockerfiles/Dockerfile.arm64v8
  dockerfiles/Dockerfile.windows
  dockerfiles/Dockerfile.windows.devel
  dockerfiles/Dockerfile.x86_64
  dockerfiles/Dockerfile.x86_64-1_7
  dockerfiles/Dockerfile.x86_64-master
  dockerfiles/Dockerfile.x86_64-master_debug
  dockerfiles/README.dockerfiles-extra.md
  dockerfiles/README.md
  dockerfiles/conf/fluent-bit.conf
  dockerfiles/conf/parsers.conf
  dockerfiles/conf/parsers_ambassador.conf
  dockerfiles/conf/parsers_cinder.conf
  dockerfiles/conf/parsers_extra.conf
  dockerfiles/conf/parsers_java.conf
  dockerfiles/conf/parsers_mult.conf
  dockerfiles/conf/parsers_openstack.conf
  dockerfiles/conf/plugins.conf
  dockerfiles/hooks/README.md
  dockerfiles/hooks/post_checkout
  dockerfiles/hooks/pre_build
Labels: backport to v1.8.x

#4975 workflows: remove Win container build for PRs
  .github/workflows/windows-build.yaml
Labels: docs-required

#4977 workflows: fix 1.8 integration test
  .github/workflows/1.8.yaml
Labels: ci

#4979 dockerfiles:remove container duplicate conf
  conf/parsers_mult.conf
  dockerfiles/conf/fluent-bit.conf
  dockerfiles/conf/parsers.conf
  dockerfiles/conf/parsers_ambassador.conf
  dockerfiles/conf/parsers_cinder.conf
  dockerfiles/conf/parsers_extra.conf
  dockerfiles/conf/parsers_java.conf
  dockerfiles/conf/parsers_openstack.conf
  dockerfiles/conf/plugins.conf
  dockerfiles/hooks/README.md
  dockerfiles/hooks/post_checkout
  dockerfiles/hooks/pre_build
Labels: docs-required

#4974 out_prometheus_remove_write: reduce log noise for happy path
  plugins/out_prometheus_remote_write/remote_write.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok, ok-package-test

#4978 tests: internal: fuzzers: utils: add hash routines
  tests/internal/fuzzers/utils_fuzzer.c
Labels: docs-required

#4967 tests: internal: fuzzers: extend json fuzzer
  tests/internal/fuzzers/flb_json_fuzzer.c
Labels: docs-required

#4988 lib: monkey: fix priority initialization for kqueue backend
  lib/monkey/mk_core/mk_event_kqueue.c
Labels: docs-required

#4982 in_stdin: use FLB_CONFIG_MAP_SIZE for the buffer_size parameter.
  plugins/in_stdin/in_stdin.c
  plugins/in_stdin/in_stdin.h
Labels: docs-required

#4981 in_syslog: use FLB_CONFIG_MAP_SIZE for the buffer size parameter.
  plugins/in_syslog/syslog.c
  plugins/in_syslog/syslog.h
  plugins/in_syslog/syslog_conf.c
Labels: docs-required

#4951 out_kafka: refactor to use configmap.
  plugins/out_kafka/kafka.c
  plugins/out_kafka/kafka_config.c
  plugins/out_kafka/kafka_config.h
Labels: docs-required

#4936 filter_nest: support config map
  plugins/filter_nest/nest.c
Labels: waiting-for-user

#4908 in_systemd: add 'lowercase' option
  plugins/in_systemd/systemd.c
  plugins/in_systemd/systemd_config.c
  plugins/in_systemd/systemd_config.h
Labels: waiting-for-user

#4956 upstream: avoid dns timeout null event injection
  src/flb_upstream.c
Labels: docs-required

#5001 workflows: support ref for checkout
  .github/workflows/build-master-packages.yaml
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/staging-build.yaml
Labels: ci

#4994 multiline: fix format string NULL-deref
  src/multiline/flb_ml.c
Labels: docs-required

#5005 codeowners: update to include packaging directory
  CODEOWNERS
Labels: docs-required

#5000 workflows: switch to SHA rather than ref
  .github/workflows/pr-integration-test.yaml
Labels: ci/integration-docker-ok, ci/integration-test-gcp-ok

#5020 cmake: add support for jemalloc page size config
  CMakeLists.txt
  packaging/distros/centos/Dockerfile
Labels: bug, ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok, packaging

#5019 filter_geoip2: refactor to use config_map.
  plugins/filter_geoip2/geoip2.c
  plugins/filter_geoip2/geoip2.h
Labels: docs-required

#5013 filter_throttle: refactor to use config_map.
  plugins/filter_throttle/throttle.c
  plugins/filter_throttle/throttle.h
Labels: docs-required

#5012 filter_stdout: add and parse empty config_map.
  plugins/filter_stdout/stdout.c
Labels: docs-required

#4953 out_counter: add empty configmap.
  plugins/out_counter/counter.c
Labels: waiting-for-user

#4984 out_td: refactor to use config_map.
  plugins/out_td/td.c
  plugins/out_td/td_config.c
  plugins/out_td/td_config.h
Labels: waiting-for-user

#4924 in_dummy: refactor to use config_map.
  plugins/in_dummy/in_dummy.c
  plugins/in_dummy/in_dummy.h
  tests/runtime/in_simple_systems.c
Labels: waiting-for-user

#4952 out_retry: refactor to use configmap.
  plugins/out_retry/retry.c
Labels: docs-required

#5026 workflows: add support to trigger a package build for a specific target
  .github/workflows/build-master-packages.yaml
Labels: docs-required

#4996 out_kafka: fix broken configuration
  plugins/out_kafka/kafka.c
Labels: docs-required

#5027 packaging: fix jemalloc override processing
  CMakeLists.txt
  dockerfiles/Dockerfile.centos7
  packaging/build.sh
  packaging/distros/amazonlinux/Dockerfile
  packaging/distros/centos/Dockerfile
  packaging/distros/debian/Dockerfile
  packaging/distros/raspbian/Dockerfile
  packaging/distros/ubuntu/Dockerfile
Labels: bug, packaging

#5025 cmake: backport jemalloc changes
  CMakeLists.txt
Labels: packaging, backport to v1.8.x

#4993 tests: internal: fuzzers: update multiline logic
  tests/internal/fuzzers/multiline_fuzzer.c
Labels: docs-required

#5031 in_tail: on file rotation, remove entry from hash tables
  plugins/in_tail/tail_file.c
Labels: docs-required

#5032 in_tail: on file rotation, remove entry from hash tables
  plugins/in_tail/tail_file.c
Labels: docs-required

#5039 workflows: add some info on release process
  .github/workflows/README.md
Labels: docs-required

#5047 in_statsd: refactor to use config_map.
  plugins/in_statsd/statsd.c
Labels: docs-required

#5046 in_collected: refactor to use config_map.
  plugins/in_collectd/in_collectd.c
  plugins/in_collectd/in_collectd.h
Labels: docs-required

#5044 out_stackdriver: refactor to use config_map
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#5030 out_bigquery: refactor to use config_map.
  plugins/out_bigquery/bigquery.c
  plugins/out_bigquery/bigquery_conf.c
Labels: docs-required

#4992 in_systemd: backport 'lowercase' option
  plugins/in_systemd/systemd.c
  plugins/in_systemd/systemd_config.c
  plugins/in_systemd/systemd_config.h
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#4561 tls: improve TLS handshake error message
  src/tls/openssl.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#5061 lib: cmetrics: upgrade to v0.3.0
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_array.h
  lib/cmetrics/include/cmetrics/cmt_encode_opentelemetry.h
  lib/cmetrics/include/cmetrics/cmt_summary.h
  lib/cmetrics/src/cmt_array.c
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_decode_opentelemetry.c
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/src/cmt_encode_opentelemetry.c
  lib/cmetrics/src/cmt_encode_prometheus.c
  lib/cmetrics/src/cmt_encode_prometheus_remote_write.c
  lib/cmetrics/src/cmt_histogram.c
  lib/cmetrics/src/cmt_opts.c
  lib/cmetrics/tests/CMakeLists.txt
  lib/cmetrics/tests/decoding.c
  lib/cmetrics/tests/encoding.c
  lib/cmetrics/tests/histogram.c
  lib/cmetrics/tests/issues.c
  lib/cmetrics/tests/null_label.c
  lib/cmetrics/tests/prometheus_parser.c
  lib/cmetrics/tests/summary.c
Labels: docs-required

#5060 ci: update the yaml configuration file for the smoke test.
  packaging/testing/smoke/container/fluent-bit.yaml
Labels: docs-required

#5034 plugins: in_opentelemetry: initial commit
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/in_opentelemetry/CMakeLists.txt
  plugins/in_opentelemetry/http_conn.c
  plugins/in_opentelemetry/http_conn.h
  plugins/in_opentelemetry/opentelemetry.c
  plugins/in_opentelemetry/opentelemetry.h
  plugins/in_opentelemetry/opentelemetry_config.c
  plugins/in_opentelemetry/opentelemetry_config.h
  plugins/in_opentelemetry/opentelemetry_prot.c
  plugins/in_opentelemetry/opentelemetry_prot.h
Labels: docs-required, draft

#5063 in_proc: fix possible free before allocation.
  plugins/in_proc/in_proc.c
Labels: docs-required

#5069 packaging: add publish script
  packaging/server/publish-all.sh
Labels: docs-required

#5050 packaging: build from source rather than tar
  .github/workflows/build-master-packages.yaml
  .github/workflows/call-build-packages.yaml
  packaging/build.sh
  packaging/distros/amazonlinux/Dockerfile
  packaging/distros/centos/Dockerfile
  packaging/distros/debian/Dockerfile
  packaging/distros/raspbian/Dockerfile
  packaging/distros/ubuntu/Dockerfile
  packaging/local-build-all.sh
Labels: docs-required

#5076 dockerfiles: add extra debug tools
  dockerfiles/Dockerfile
Labels: packaging

#5079 install: support Rocky and Alma Linux
  install.sh
Labels: docs-required

#5080 packaging: add updates for server publishing
  packaging/server/README.md
  packaging/server/aptly.conf
  packaging/server/publish-all.sh
Labels: docs-required

#5086 aws: check AWS EC2 IMDSv2 client error
  src/aws/flb_aws_imds.c
Labels: docs-required

#4689 mem: add chance of failing flb_malloc when fuzzing
  include/fluent-bit/flb_mem.h
  tests/internal/fuzzers/flb_fuzz_header.h
  tests/internal/fuzzers/utils_fuzzer.c
Labels: docs-required

#5099 packaging: add raspbian/bullseye and option to skip signing
  .github/workflows/call-build-packages.yaml
  .github/workflows/staging-release.yaml
  packaging/remove-version.sh
  packaging/update-repos.sh
Labels: docs-required

#5112 workflows: unstable build updates
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/staging-release.yaml
  packaging/update-repos.sh
Labels: docs-required

#5107 filter_nightfall: capitalize flag in CMakeLists
  CMakeLists.txt
Labels: fixed, ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok

#5096 build: macos: Handle w/o patch version returning case
  cmake/luajit.cmake
Labels: docs-required

#5113 packaging: fix path
  packaging/update-repos.sh
Labels: docs-required

#5116 workflows: align compile check with fuzz triggers
  .github/workflows/pr-compile-check.yaml
  .github/workflows/pr-fuzz.yaml
  .github/workflows/unit-tests.yaml
Labels: docs-required

#5135 workflows: degrade to standard token if no PAT
  .github/workflows/cron-scorecards-analysis.yaml
Labels: docs-required

#5117 workflows: unstable builds for supported branches
  .github/actions/generate-package-build-matrix/action.yaml
  .github/workflows/README.md
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/staging-build.yaml
  dockerfiles/Dockerfile
  packaging/update-repos.sh
Labels: docs-required

#5133 packaging: add repo signing check to install script
  install.sh
  packaging/testing/smoke/packages/Dockerfile.amazonlinux2
  packaging/testing/smoke/packages/Dockerfile.centos7
  packaging/testing/smoke/packages/Dockerfile.centos8
  packaging/testing/smoke/packages/Dockerfile.debian10
  packaging/testing/smoke/packages/Dockerfile.debian11
  packaging/testing/smoke/packages/Dockerfile.ubuntu1804
  packaging/testing/smoke/packages/Dockerfile.ubuntu2004
  packaging/testing/smoke/packages/local-test-all.sh
  packaging/testing/smoke/packages/run-package-tests.sh
Labels: packaging

#5119 filter_nightfall: fix for loop variable syntax
  plugins/filter_nightfall/nightfall.c
  plugins/filter_nightfall/nightfall_api.c
Labels: docs-required

#5124 config_map: add check if flb_env_var_translate failed
  src/flb_config_map.c
Labels: docs-required

#5139 workflows: disable staging build on every push
  .github/workflows/staging-build.yaml
Labels: docs-required

#5151 dockerfile: remove missing package ltrace for other architectures
  dockerfiles/Dockerfile
Labels: docs-required

#5142 workflows: resolve staging build issue
  .github/workflows/call-build-packages.yaml
  packaging/server/README.md
  packaging/server/publish-all.sh
Labels: docs-required

#5155 workflows: resolve schema name failure
  .github/workflows/call-build-images.yaml
Labels: docs-required

#5159 task: fixed wrong assumed type for data in flb_task_retry_count
  src/flb_task.c
Labels: docs-required

#5158 task: fixed wrong assumed type for data in flb_task_retry_count
  src/flb_task.c
Labels: docs-required

#5161 workflows: refactor schema generation for staging
  .github/workflows/staging-build.yaml
  dockerfiles/Dockerfile
Labels: docs-required

#5175 out_opensearch: fix double free on index header (#5132)
  plugins/out_opensearch/opensearch.c
Labels: docs-required

#5179 filter_kubernetes: fix leak on journal mode when excluding records
  plugins/filter_kubernetes/kube_property.c
  plugins/filter_kubernetes/kubernetes.c
Labels: docs-required

#5182 ci: update codeowners
  CODEOWNERS
Labels: docs-required

#5125 out_kafka: fix broken config map(#5097)
  plugins/out_kafka/kafka.c
  plugins/out_kafka/kafka_config.c
Labels: docs-required

#5201 input: remove dummy debug message
  src/flb_input.c
Labels: docs-required

#5193 out_websocket: add missing json_date_ properties to config_map
  plugins/out_websocket/websocket.c
  plugins/out_websocket/websocket_conf.c
Labels: docs-required

#5202 version: move version info to header file
  include/fluent-bit/flb_version.h.in
  src/fluent-bit.c
Labels: docs-required

#5197 workflows: increase stale ops limit
  .github/workflows/cron-stale.yaml
Labels: docs-required
