Repository fluent/fluent-bit, pull requests merged in 2022-10, with the labels that each got.

#6135 lib/monkey: sync with upstream.
  lib/monkey/include/monkey/mk_core/mk_event.h
  lib/monkey/include/monkey/mk_core/mk_list.h
  lib/monkey/include/monkey/mk_core/mk_utils.h
  lib/monkey/mk_core/mk_event.c
  lib/monkey/mk_core/mk_event_epoll.c
  lib/monkey/mk_core/mk_event_kqueue.c
  lib/monkey/mk_core/mk_event_libevent.c
  lib/monkey/mk_core/mk_event_select.c
  lib/monkey/mk_core/mk_rconf.c
  lib/monkey/mk_core/mk_string.c
  lib/monkey/mk_server/mk_lib.c
  lib/monkey/mk_server/mk_mimetype.c
  lib/monkey/mk_server/mk_stream.c
Labels: docs-required

#6134 tests/filter_stdout: fix SIGSEGV by not calling flb_stop without flb_start
  tests/runtime/filter_stdout.c
Labels: docs-required

#6145 trace: update docker build for example with new compile flag.
  examples/tracing/docker-compose.yml
Labels: docs-required

#6136 out_loki: enable processing multiple tasks in loki output plugin.
  plugins/out_loki/loki.c
Labels: docs-required

#6123 help: show implicit options for input net plugins.
  src/flb_help.c
Labels: docs-required

#6131 metrics: add warn message when 'title' was truncated
  src/flb_metrics.c
Labels: docs-required

#6126 dockerfiles: enable Tap in official containers
  dockerfiles/Dockerfile
Labels: docs-required

#6147 tests: internal: fuzzers: engine_fuzzer: fix build
  tests/internal/fuzzers/engine_fuzzer.c
Labels: docs-required

#6150 lib: ctraces: upgrade to v0.2.2
  lib/ctraces/CMakeLists.txt
  lib/ctraces/src/ctr_decode_opentelemetry.c
Labels: docs-required

#6156 in_opentelemetry: updated decoder interface
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#6159 lib: cfl: update to v0.1.8
  lib/cfl/.github/workflows/packages.yaml
  lib/cfl/CMakeLists.txt
  lib/cfl/include/cfl/cfl_list.h
Labels: docs-required

#6166 lib: ctraces: upgrade to v0.2.3
  lib/ctraces/CMakeLists.txt
  lib/ctraces/include/ctraces/ctr_decode_msgpack.h
  lib/ctraces/include/ctraces/ctr_mpack_utils.h
  lib/ctraces/include/ctraces/ctr_mpack_utils_defs.h
  lib/ctraces/include/ctraces/ctr_variant_utils.h
  lib/ctraces/src/CMakeLists.txt
  lib/ctraces/src/ctr_decode_msgpack.c
  lib/ctraces/src/ctr_encode_msgpack.c
  lib/ctraces/src/ctr_id.c
  lib/ctraces/src/ctr_mpack_utils.c
  lib/ctraces/tests/CMakeLists.txt
  lib/ctraces/tests/decoding.c
Labels: docs-required

#6170 lib: ctraces: upgrade to v0.2.4
  lib/ctraces/CMakeLists.txt
  lib/ctraces/src/ctr_decode_msgpack.c
  lib/ctraces/tests/decoding.c
Labels: docs-required

#6173 config: fix property values being truncated.
  src/config_format/flb_config_format.c
  src/fluent-bit.c
Labels: docs-required

#6182 packaging: handle 1.9 package builds for fluent-bit defaults
  .github/workflows/call-build-linux-packages.yaml
  packaging/build.sh
Labels: docs-required

#6183 packaging: update raspbian container and pin cmake
  packaging/distros/raspbian/Dockerfile
Labels: packaging, backport to v1.9.x

#6153 parser: refine exit path
  src/flb_parser.c
Labels: docs-required

#6154 strptime: fix integer boundary
  src/flb_strptime.c
Labels: docs-required

#6152 env: add size check before copying
  src/flb_env.c
Labels: docs-required

#6185 dockerfiles: add OpenSSL to Windows container
  dockerfiles/Dockerfile.windows
Labels: packaging

#6186 packaging: update to provide AL 2022 as an official target
  packaging/build-config.json
  packaging/server/README.md
  packaging/server/publish-all.sh
  packaging/testing/smoke/packages/Dockerfile.amazonlinux2022
  packaging/update-repos.sh
Labels: docs-required

#6199 in_tail: Fix 32 bit support in file hash logic
  plugins/in_tail/tail_file.c
Labels: docs-required

#6210 out_forward: release buf when no connection available and time_as_integer is true(#6082)
  plugins/out_forward/forward.c
Labels: backport to v1.9.x

#6212 out_forward: 1.9 release buf when no connection available and time_as_integer is true(#6082)
  plugins/out_forward/forward.c
Labels: docs-required

#6211 out_tcp: check connection first (#6208)
  plugins/out_tcp/tcp.c
Labels: docs-required

#6176 plugins: in_winevtlog: adds ability to ignore channels missing in Windows Event Log
  plugins/in_winevtlog/in_winevtlog.c
  plugins/in_winevtlog/winevtlog.c
  plugins/in_winevtlog/winevtlog.h
Labels: docs-required

#6114 pack: add 'epoch_ms' format based on jeongki-kim's commit
  include/fluent-bit/flb_pack.h
  include/fluent-bit/flb_time.h
  src/flb_pack.c
  src/flb_time.c
Labels: docs-required

#6099 logfmt: bare keys get "true" as value, not "nil"
  src/flb_parser_logfmt.c
Labels: docs-required

#6213 config_format: fluentbit: set config file number limit and check recursion(#5998)
  src/config_format/flb_cf_fluentbit.c
  tests/internal/config_format_fluentbit.c
  tests/internal/data/config_format/classic/recursion.conf
Labels: docs-required

#6224 packaging: handle parameters separate from command for word splitting
  packaging/server/publish-all.sh
  packaging/update-repos.sh
Labels: ci, packaging

#6235 input: added missing mandatory TLS parameter detection and reporting.
  src/flb_input.c
Labels: docs-required

#6249 out_loki: get tenant_id before removing keys(#6207)
  plugins/out_loki/loki.c
Labels: docs-required

#6239 fluent-bit: fix command line parsing with new config format API.
  src/fluent-bit.c
Labels: docs-required

#6189 workflows: add 1.8 branch container build
  .github/workflows/build-legacy-branch.yaml
Labels: ci

#4359 logfmt: don't omit last item if it does not have a value
  src/flb_parser_logfmt.c
Labels: docs-required

#3450 filter: add total processing volume metrics
  include/fluent-bit/flb_filter.h
  src/flb_filter.c
Labels: docs-required

#6103 Add functionality to the modify filter to move fields to the start or end
  plugins/filter_modify/modify.c
  plugins/filter_modify/modify.h
Labels: docs-required

#6233 lib: cmetrics: upgrade to v0.5.3 (Splunk HEC)
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_encode_splunk_hec.h
  lib/cmetrics/src/CMakeLists.txt
  lib/cmetrics/src/cmt_encode_splunk_hec.c
  lib/cmetrics/tests/encoding.c
Labels: docs-required

#6247 example: wasm: Fix typos
  examples/filter_rust/README.md
  examples/filter_rust_clib/README.md
Labels: docs-required

#6243 in_tail: Fix multiline + Path_Key emitting empty logs
  plugins/in_tail/tail_file.c
Labels: docs-required

#6244 in_tail: Fix multiline + Path_Key emitting empty logs (1.9)
  plugins/in_tail/tail_file.c
Labels: docs-required

#5928 in_opentelemetry: add proto files for logs
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#5899 filter_ecs: new filter for AWS ECS Metadata
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/filter_aws/aws.c
  plugins/filter_ecs/CMakeLists.txt
  plugins/filter_ecs/ecs.c
  plugins/filter_ecs/ecs.h
  tests/runtime/CMakeLists.txt
  tests/runtime/filter_ecs.c
Labels: AWS

#6270 dummy: up the sleep time in the tests so they pass.
  tests/runtime/in_simple_systems.c
Labels: docs-required

#6264 connection: added cast to remove warning
  src/flb_connection.c
Labels: docs-required

#6266 chunk_trace: minor fixes when tracing with rewrite_tag filters.
  src/flb_chunk_trace.c
  src/flb_filter.c
  src/http_server/api/v1/trace.c
Labels: docs-required

#6271 dockerfiles: Fix to work correctly for Windows container
  dockerfiles/Dockerfile.windows
Labels: docs-required

#6274 workflows: update test release packages to update curl
  packaging/test-release-packages.sh
Labels: docs-required

#6286 opentelemetry: fixed uri sanitizer issue
  plugins/out_opentelemetry/opentelemetry_conf.c
Labels: docs-required

#6298 out_forward: Put chunk key as the first key of the option map
  plugins/out_forward/forward_format.c
Labels: docs-required

#6292 in_winevtlog: Fix ignoring non-existent channel handling
  plugins/in_winevtlog/winevtlog.c
Labels: docs-required

#6318 tests: runtime: out_forward: Follow option order for fluent_signal
  tests/runtime/out_forward.c
Labels: docs-required

#6305 tests: internal: fuzzers: add base64 fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/base64_fuzzer.c
Labels: docs-required
