Repository fluent/fluent-bit, pull requests merged in 2022-02, with the labels that each got.

#4729 1.8: pack: enhance memory allocation strategy for large JSON payloads
  src/flb_pack.c
Labels: docs-required

#4731 pack: ensure minimum allocation is 256 bytes (unit test)
  src/flb_pack.c
Labels: docs-required

#4725 file: add new utility module
  include/fluent-bit/flb_file.h
  src/CMakeLists.txt
  src/flb_file.c
  tests/internal/CMakeLists.txt
  tests/internal/data/file/empty_file.txt
  tests/internal/data/file/text_file.txt
  tests/internal/file.c
Labels: docs-required

#4721 workflows: add scorecards analysis
  .github/workflows/scorecards-analysis.yaml
Labels: docs-required

#4739 workflows: remove Azure action usage
  .github/containerscan/allowedlist.yaml
  .github/workflows/call-build-images.yaml
  .github/workflows/pr-image-tests.yaml
  .github/workflows/staging-build.yaml
Labels: packaging

#4740 installation: add script to install in one liner
  .github/workflows/skipped-unit-tests.yaml
  .github/workflows/unit-tests.yaml
  install.sh
Labels: packaging

#4753 out_stackdriver: Use correct env variable for custom service accounts
  plugins/out_stackdriver/stackdriver_conf.c
Labels: ok-to-test

#4767 workflows: PR fork permission tweaks and other updates
  .github/workflows/README.md
  .github/workflows/call-build-packages.yaml
  .github/workflows/pr-image-tests.yaml
  .github/workflows/pr-integration-test.yaml
  .github/workflows/remove-release.yaml
  .github/workflows/staging-build.yaml
  .github/workflows/staging-release.yaml
Labels: ci, ok-container-test

#4772 packaging: resolve CentOS 8 mirror issues
  .github/workflows/staging-build.yaml
  packaging/distros/centos/Dockerfile
  packaging/local-build-all.sh
Labels: packaging

#4773 packaging: update ARM64 mirrors for CentOS 8
  .github/workflows/staging-build.yaml
  .github/workflows/staging-release.yaml
  packaging/distros/centos/Dockerfile
Labels: packaging

#4741 workflows: lint reusable target branch
  .github/workflows/pr-lint.yaml
Labels: ci

#4797 lib: cmetrics: upgrade to v0.2.3 - OTel Metrics support
  lib/cmetrics/.github/dependabot.yml
  lib/cmetrics/.github/workflows/packages.yaml
  lib/cmetrics/.gitignore
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmetrics.h
  lib/cmetrics/include/cmetrics/cmt_counter.h
  lib/cmetrics/include/cmetrics/cmt_encode_opentelemetry.h
  lib/cmetrics/include/cmetrics/cmt_map.h
  lib/cmetrics/include/opentelemetry/common.pb-c.h
  lib/cmetrics/include/opentelemetry/metrics.pb-c.h
  lib/cmetrics/include/opentelemetry/metrics_service.pb-c.h
  lib/cmetrics/include/opentelemetry/resource.pb-c.h
  lib/cmetrics/include/protobuf-c/protobuf-c.h
  lib/cmetrics/src/CMakeLists.txt
  lib/cmetrics/src/cmt_counter.c
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_encode_opentelemetry.c
  lib/cmetrics/src/cmt_gauge.c
  lib/cmetrics/src/cmt_map.c
  lib/cmetrics/src/cmt_time.c
  lib/cmetrics/src/cmt_untyped.c
  lib/cmetrics/src/external/opentelemetry_common.pb-c.c
  lib/cmetrics/src/external/opentelemetry_metrics.pb-c.c
  lib/cmetrics/src/external/opentelemetry_metrics_service.pb-c.c
  lib/cmetrics/src/external/opentelemetry_resource.pb-c.c
  lib/cmetrics/tests/encoding.c
Labels: docs-required

#4794 workflows: update to handle nightly builds
  .github/workflows/README.md
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-packages.yaml
  .github/workflows/pr-package-tests.yaml
  .github/workflows/scorecards-analysis.yaml
  .github/workflows/staging-build.yaml
  packaging/build.sh
  packaging/distros/amazonlinux/Dockerfile
  packaging/distros/centos/Dockerfile
  packaging/distros/debian/Dockerfile
  packaging/distros/raspbian/Dockerfile
  packaging/distros/ubuntu/Dockerfile
  packaging/local-build-all.sh
  packaging/testing/smoke/packages/Dockerfile.amazonlinux2
  packaging/testing/smoke/packages/Dockerfile.centos7
  packaging/testing/smoke/packages/Dockerfile.centos8
  packaging/update-repos.sh
Labels: ci, packaging

#4751 tls: Load system certificates on Windows
  src/tls/openssl.c
Labels: docs-required

#4752 tls: Load system certificates on Windows
  src/tls/openssl.c
Labels: docs-required, backport to v1.8.x

#4803 plugins: out_opentelemetry: initial commit
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_opentelemetry/CMakeLists.txt
  plugins/out_opentelemetry/opentelemetry.c
  plugins/out_opentelemetry/opentelemetry.h
  plugins/out_opentelemetry/opentelemetry_conf.c
  plugins/out_opentelemetry/opentelemetry_conf.h
Labels: docs-required

#4770 out_stackdriver: check for proper http request key
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver_http_request.c
  plugins/out_stackdriver/stackdriver_http_request.h
Labels: docs-required

#4282 out_bigquery: support AWS auth via GCP Workload Identity Federation
  plugins/out_bigquery/bigquery.c
  plugins/out_bigquery/bigquery.h
  plugins/out_bigquery/bigquery_conf.c
Labels: ok-to-test

#4804 in_systemd: skip broken entry
  plugins/in_systemd/systemd.c
Labels: docs-required

#4779 out_stackdriver: add new metric 'fluentbit_stackdriver_requests_total' (#2698)
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: ok-to-test, ci/integration-docker-ok

#4782 1.8: out_stackdriver: add new metric 'fluentbit_stackdriver_requests_total' (#2698)
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#4802 1.8: filter_rewrite_tag: fix Match aborting issue (#4276)
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#4646 Revert: support native cross-compilation for ARM64
  CMakeLists.txt
  cmake/linux-arm64.cmake
  cmake/luajit.cmake
  cmake/onigmo.cmake
Labels: docs-required

#4809 packaging: fix RPM check for fluent bit
  packaging/testing/smoke/packages/test.sh
Labels: docs-required

#4812 packaging: fix syntax error in AL2 test
  packaging/testing/smoke/packages/Dockerfile.amazonlinux2
Labels: packaging

#4815 workflows: various updates
  .github/workflows/cron-scorecards-analysis.yaml
  .github/workflows/cron-stale.yaml
Labels: ci, dependencies

#4807 out_opensearch: initial implementation of OpenSearch output plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_opensearch/CMakeLists.txt
  plugins/out_opensearch/opensearch.c
  plugins/out_opensearch/opensearch.h
  plugins/out_opensearch/os_conf.c
  plugins/out_opensearch/os_conf.h
  tests/runtime/CMakeLists.txt
  tests/runtime/out_opensearch.c
Labels: docs-required

#4819 out_prometheus_exporter: add new option 'add_timestamp', disabled by default
  plugins/out_prometheus_exporter/prom.c
  plugins/out_prometheus_exporter/prom.h
Labels: backport to v1.8.x

#4820 1.8: out_prometheus_exporter: add new option 'add_timestamp', disabled by default
  plugins/out_prometheus_exporter/prom.c
  plugins/out_prometheus_exporter/prom.h
Labels: docs-required

#4810 bin: fix wrong host header when using proxy
  src/flb_http_client.c
Labels: docs-required

#4816 1.8: bin: fix wrong host header when using proxy
  src/flb_http_client.c
Labels: docs-required, backport to v1.8.x

#4813 out_stackdriver: check for proper http request key
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver_http_request.c
  plugins/out_stackdriver/stackdriver_http_request.h
Labels: docs-required

#4391 in_windows_exporter_metrics: initial version
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/in_windows_exporter_metrics/CMakeLists.txt
  plugins/in_windows_exporter_metrics/we.c
  plugins/in_windows_exporter_metrics/we.h
  plugins/in_windows_exporter_metrics/we_config.c
  plugins/in_windows_exporter_metrics/we_config.h
  plugins/in_windows_exporter_metrics/we_cpu.c
  plugins/in_windows_exporter_metrics/we_cpu.h
  plugins/in_windows_exporter_metrics/we_metric.c
  plugins/in_windows_exporter_metrics/we_metric.h
  plugins/in_windows_exporter_metrics/we_perflib.c
  plugins/in_windows_exporter_metrics/we_perflib.h
  plugins/in_windows_exporter_metrics/we_util.c
  plugins/in_windows_exporter_metrics/we_util.h
  plugins/in_windows_exporter_metrics/we_wmi.c
  plugins/in_windows_exporter_metrics/we_wmi.h
Labels: Windows, docs-required, draft

#4831 build: allow defined but empty FLB_NIGHTLY_BUILD
  CMakeLists.txt
Labels: docs-required

#4835 workflows: disable ossf on-push event
  .github/workflows/cron-scorecards-analysis.yaml
Labels: docs-required

#4814 workflows: yaml build support
  dockerfiles/Dockerfile.arm32v7
  dockerfiles/Dockerfile.arm64v8
  dockerfiles/Dockerfile.multiarch
  dockerfiles/Dockerfile.x86_64
  dockerfiles/Dockerfile.x86_64-debug
  dockerfiles/Dockerfile.x86_64-master
  dockerfiles/Dockerfile.x86_64-master_debug
  packaging/distros/amazonlinux/Dockerfile
  packaging/distros/centos/Dockerfile
  packaging/distros/debian/Dockerfile
  packaging/distros/raspbian/Dockerfile
  packaging/distros/ubuntu/Dockerfile
  packaging/local-build-all.sh
  packaging/testing/smoke/container/container-smoke-test.sh
  packaging/testing/smoke/container/fluent-bit.yaml
  packaging/testing/smoke/packages/Dockerfile.centos7
  packaging/testing/smoke/packages/Dockerfile.ubuntu2004
Labels: packaging, ci/container-test-ok

#4179 winevtlog: Implement winevtlog plugin
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_winevtlog/CMakeLists.txt
  plugins/in_winevtlog/in_winevtlog.c
  plugins/in_winevtlog/pack.c
  plugins/in_winevtlog/winevtlog.c
  plugins/in_winevtlog/winevtlog.h
Labels: Windows, docs-required

#4832 build: luajit: macos: Handle macOS Monterey
  cmake/luajit.cmake
Labels: docs-required

#4811 pack: added java_sql_timestamp, a format string used by amazon athena
  DEVELOPER_GUIDE.md
  include/fluent-bit/flb_pack.h
  plugins/out_http/http.c
  plugins/out_null/null.c
  plugins/out_s3/s3.c
  plugins/out_stdout/stdout.c
  plugins/out_tcp/tcp.c
  src/flb_pack.c
Labels: docs-required

#4822 1.8: pack: added java_sql_timestamp, a format string used by amazon athena
  include/fluent-bit/flb_pack.h
  src/flb_pack.c
Labels: docs-required

#4846 filter_expect: exit with 255 on failure
  src/flb_lib.c
  src/fluent-bit.c
Labels: backport to v1.8.x

#4850 output_thread: fix type cast that caused issues in win32
  src/flb_output_thread.c
Labels: docs-required

#4851 output_thread: fix type cast that caused issues in win32
  src/flb_output_thread.c
Labels: docs-required

#4852 parser: initialize multiline parser_ctx to NULL
  src/flb_parser.c
Labels: docs-required

#4854 packaging: fix container smoke test
  packaging/testing/smoke/container/container-smoke-test.sh
Labels: docs-required

#4843 build: luajit: macos: implement more stable MACOSX_DEPLOYMENT_TARGET
  cmake/luajit.cmake
Labels: docs-required

#4859 dockerfiles: add status handling for distroless packages
  dockerfiles/Dockerfile.multiarch
Labels: docs-required

#4861 workflows: unstable release protection
  .github/workflows/staging-release.yaml
Labels: docs-required

#4865 workflows: fix release env usage
  .github/workflows/staging-release.yaml
Labels: docs-required

#4874 filter_parser: support config map
  plugins/filter_parser/filter_parser.c
  plugins/filter_parser/filter_parser.h
Labels: docs-required

#4870 filter_record_modifier: support config map
  plugins/filter_record_modifier/filter_modifier.c
  plugins/filter_record_modifier/filter_modifier.h
Labels: docs-required

#4871 filter_type_converter: support config map
  plugins/filter_type_converter/type_converter.c
  plugins/filter_type_converter/type_converter.h
Labels: docs-required

#4872 filter_grep: support config map
  plugins/filter_grep/grep.c
  plugins/filter_grep/grep.h
Labels: docs-required

#4868 config: fix memory leak
  src/flb_config.c
Labels: docs-required

#4867 tests: internal: fuzzer: fix leak in record_ac_fuzzer
  tests/internal/fuzzers/record_ac_fuzzer.c
Labels: docs-required

#4876 workflows: staging updates for 1.9
  .github/workflows/staging-build.yaml
  .github/workflows/staging-release.yaml
  .github/workflows/staging-test.yaml
Labels: ci

#4880 workflows: ensure we do not deploy on every push
  .github/workflows/staging-build.yaml
Labels: docs-required

#4881 lib: monkey: sync channel release addition
  lib/monkey/include/monkey/mk_stream.h
  lib/monkey/mk_server/mk_stream.c
Labels: docs-required

#4882 lib: monkey: sync channel release addition
  lib/monkey/include/monkey/mk_stream.h
  lib/monkey/mk_server/mk_stream.c
Labels: docs-required

#4887 lib: monkey: sync capacity improvement
  lib/monkey/mk_server/mk_scheduler.c
Labels: docs-required

#4886 lib: monkey: sync capacity improvement
  lib/monkey/mk_server/mk_scheduler.c
Labels: docs-required

#4891 out_opentelemetry: set default uri to /v1/metrics
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#4889 plugins: in_http: memory leak correction
  plugins/in_http/http_conn.c
Labels: docs-required

#4883 multiline: fix leak
  src/multiline/flb_ml_parser.c
Labels: docs-required

#4885 multiline: fix leak
  src/multiline/flb_ml.c
Labels: docs-required

#4890 plugins: in_http: memory leak correction
  plugins/in_http/http_conn.c
Labels: docs-required

#4878 tests: internal: fuzzers: fix compiler warnings
  tests/internal/fuzzers/multiline_fuzzer.c
  tests/internal/fuzzers/strp_fuzzer.c
  tests/internal/fuzzers/utils_fuzzer.c
Labels: docs-required

#4913 output_thread: sig 0xdeadbeef write 4 bytes, not 8 on 32bit machine
  src/flb_output_thread.c
Labels: docs-required

#4898 in_cpu: configmap support.
  plugins/in_cpu/cpu.c
  plugins/in_cpu/cpu.h
Labels: docs-required

#4899 in_disk: configmap support.
  plugins/in_disk/in_disk.c
  plugins/in_disk/in_disk.h
Labels: docs-required

#4900 in_mem: configmap support.
  plugins/in_mem/mem.c
  plugins/in_mem/mem.h
Labels: docs-required

#4901 in_thermal: configmap support.
  plugins/in_thermal/in_thermal.c
  plugins/in_thermal/in_thermal.h
Labels: docs-required

#4902 in_proc: add support for configmap.
  plugins/in_proc/in_proc.c
  plugins/in_proc/in_proc.h
Labels: docs-required

#4904 in_random: add support for configmap.
  plugins/in_random/random.c
Labels: docs-required

#4909 filter_modify: support config_map
  plugins/filter_modify/modify.c
Labels: docs-required

#4903 in_head: add support for configmap.
  plugins/in_head/in_head.c
  plugins/in_head/in_head.h
Labels: docs-required

#4906 in_netif: update to use config_map.
  plugins/in_netif/in_netif.c
  plugins/in_netif/in_netif.h
Labels: docs-required

#4907 in_health: add support for configmap.
  plugins/in_health/health.c
Labels: docs-required

#4919 build: enforce for Flex 2 and Bison 3 as a minimum
  CMakeLists.txt
Labels: docs-required

#4926 out_azure: add config map support
  plugins/out_azure/azure.c
  plugins/out_azure/azure_conf.c
Labels: docs-required

#4922 in_stdin: refactor to use config_map.
  plugins/in_stdin/in_stdin.c
  plugins/in_stdin/in_stdin.h
Labels: docs-required

#4923 in_docker: update to use config_map.
  plugins/in_docker/docker.c
  plugins/in_docker/docker.h
Labels: docs-required

#4930 lib: cmetrics: upgrade DEV v0.3.0 (2e315e3)
  lib/cmetrics/CMakeLists.txt
Labels: docs-required

#4938 tests: internal: fuzzers: fix compiler warnings
  tests/internal/fuzzers/config_fuzzer.c
  tests/internal/fuzzers/msgpack_to_gelf_fuzzer.c
Labels: docs-required

#4937 tests: internal: fuzzer: add filter_stdout fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/filter_stdout_fuzzer.c
Labels: docs-required

#4942 dockerfiles: ensure certificates included
  dockerfiles/Dockerfile
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-gcp-ok
