Repository fluent/fluent-bit, pull requests merged in 2023-05, with the labels that each got.

#7295 in_podman_metrics: Added image label
  plugins/in_podman_metrics/podman_metrics.c
  plugins/in_podman_metrics/podman_metrics.h
  plugins/in_podman_metrics/podman_metrics_config.h
  tests/runtime/data/podman/reversed/18446744073709551615/net/dev
  tests/runtime/data/podman/reversed/config.json
  tests/runtime/data/podman/reversed/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/data/podman/reversed/memory/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.usage_in_bytes
  tests/runtime/in_podman_metrics.c
Labels: docs-required

#7287 mp: updated the format check to accept the new format released with 2.1
  src/flb_mp.c
Labels: docs-required, ok-package-test

#7293 filter_parser: fix timestamp and metadata to be properly copied
  plugins/filter_parser/filter_parser.c
Labels: docs-required

#7302 out_vivo_exporter: updated the code to use the log event decoder
  plugins/out_vivo_exporter/vivo.c
  plugins/out_vivo_exporter/vivo_http.c
Labels: docs-required

#7303 output_thread: added event memory intialization
  src/flb_output_thread.c
Labels: docs-required

#7253 lib: snappy: don't require c++
  lib/snappy-fef67ac/CMakeLists.txt
Labels: docs-required

#6387 utils: parse quotes when splitting strings
  include/fluent-bit/flb_utils.h
  plugins/filter_modify/modify.c
  src/flb_utils.c
  tests/internal/utils.c
  tests/runtime/filter_modify.c
Labels: docs-required

#7309 dockerfiles: update libldap to v2.5-0
  dockerfiles/Dockerfile
Labels: packaging

#7305 filter_lua: fix buffer size calculation(#7304)
  plugins/filter_lua/lua.c
Labels: docs-required

#7311 filter_rewrite_tag: emit using decoder parameters
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#7289 filter: remove unused variable
  src/flb_filter.c
Labels: docs-required

#7292 in_otel: do not send content-length at 204(#7231)
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#7318 out_prometheus_remote_write: added configurable compression method
  plugins/out_prometheus_remote_write/remote_write.c
  plugins/out_prometheus_remote_write/remote_write.h
Labels: docs-required

#7326 out_prometheus_remote_write: added missing header inclusion
  plugins/out_prometheus_remote_write/remote_write.c
Labels: docs-required, ok-package-test

#7323 parser_json: keep time key when parsing fails
  src/flb_parser_json.c
  tests/internal/parser_json.c
Labels: docs-required

#7328 Backport keep time key
  src/flb_parser_json.c
  tests/internal/parser_json.c
Labels: docs-required

#7319 in_node_exporter_metrics: added a systemd metrics collector
  CMakeLists.txt
  plugins/in_node_exporter_metrics/CMakeLists.txt
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_systemd.c
  plugins/in_node_exporter_metrics/ne_systemd.h
Labels: docs-required, ok-package-test

#7332 record_accessor: allow single char for flb_ra_translate(#7330)
  src/flb_record_accessor.c
  tests/internal/record_accessor.c
Labels: docs-required

#7341 backport PR 7332
  src/flb_record_accessor.c
  tests/internal/record_accessor.c
Labels: docs-required

#7359 in_kafka: use log encoder
  plugins/in_kafka/in_kafka.c
  src/flb_log_event_encoder_primitives.c
Labels: docs-required

#7369 in_elasticsearch: Refer the plugin provided tag [2.0 backport]
  include/fluent-bit/flb_input.h
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
  src/flb_input.c
  tests/runtime/in_elasticsearch.c
Labels: docs-required

#7370 filter_geoip2: Guard for insifficient data error for fully decoded case
  plugins/filter_geoip2/geoip2.c
Labels: docs-required

#7360 in_elasticsearch: Refer the plugin provided tag
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
  tests/runtime/in_elasticsearch.c
Labels: docs-required

#7377 PR template: add valgrind instructions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs-required

#7373 build: in_syslog: Enable in_syslog plugin on Windows
  cmake/windows-setup.cmake
  plugins/in_syslog/syslog_conf.c
  plugins/in_syslog/syslog_server.c
Labels: docs-required, ok-package-test

#7378 filter_modify: fix clean up function for cond/rule(#7368)
  plugins/filter_modify/modify.c
  src/flb_regex.c
  tests/runtime/filter_modify.c
Labels: docs-required

#7382 in_opentelemetry: fix record structure
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#7385 dockerfiles: revert update ldap dependencies from 7309
  .github/workflows/pr-image-tests.yaml
  dockerfiles/Dockerfile
Labels: packaging

#7389 out_stackdriver: process spanId special field
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  tests/runtime/data/stackdriver/stackdriver_test_span_id.h
  tests/runtime/out_stackdriver.c
Labels: docs-required

#7251 in_elasticsearch: release buffer on error case [2.0 backport]
  plugins/in_elasticsearch/in_elasticsearch.c
  plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
Labels: docs-required

#7395 in_windows_exporter_metrics: Fill the empty string when l2/l3 cache is not defined case
  plugins/in_windows_exporter_metrics/we_wmi.c
Labels: docs-required

#7407 in_http: fix parser memory reinitialization
  cmake/windows-setup.cmake
  plugins/in_http/http_conn.c
Labels: docs-required

#7408 in_http: fix parser memory reinitialization [2.0 backport]
  cmake/windows-setup.cmake
  plugins/in_http/http_conn.c
Labels: docs-required

#7398 lib: ctraces: upgrade to v0.3.1
  lib/ctraces/CMakeLists.txt
  lib/ctraces/include/ctraces/ctr_mpack_utils_defs.h
Labels: docs-required

#7413 out_opentelemetry: add proper error handling in case msgpack decode f…
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#7415 out_opentelemetry: fix error handling for failed msgpack decoding
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#7410 in_node_exporter_metrics: Make ignoring mount points and filesystem types of regular expressions to be configurable
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_filesystem_linux.c
Labels: docs-required

#7396 processor: input: output: organize initialization sequence for processor
  src/flb_input.c
  src/flb_output.c
  src/flb_processor.c
Labels: docs-required

#7381 out_opensearch: Add gzip compression
  plugins/out_opensearch/opensearch.c
  plugins/out_opensearch/opensearch.h
  plugins/out_opensearch/os_conf.c
Labels: docs-required

#7401 core: compression abstraction layer addition
  include/fluent-bit/flb_compression.h
  include/fluent-bit/flb_gzip.h
  src/CMakeLists.txt
  src/flb_compression.c
  src/flb_gzip.c
Labels: docs-required

#7422 tiger: output event handling improvements
  src/flb_engine.c
Labels: docs-required

#7421 tiger: chunk size limit addition
  include/fluent-bit/flb_config.h
  include/fluent-bit/flb_storage.h
  src/flb_config.c
  src/flb_input_chunk.c
  src/flb_storage.c
Labels: docs-required

#7423 tiger: chunk rollover workaround
  include/fluent-bit/flb_engine_dispatch.h
  include/fluent-bit/flb_output.h
  src/flb_engine.c
  src/flb_engine_dispatch.c
Labels: docs-required

#7431 out_opentelemetry: fix memory leak
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#7430 out_opentelemetry: fix memory leak
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#7425 out_opentelemetry: flush multiple traces from one chunk
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#7424 out_opentelemetry: flush multiple traces from one chunk
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#7418 TLS: using dot trimmed tcp_host/proxied_host for vhost
  include/fluent-bit/flb_str.h
  src/tls/flb_tls.c
Labels: docs-required

#7419 in_node_exporter_metrics: Prevent to duplicate sysfs path for collecting metrics
  plugins/in_node_exporter_metrics/ne_utils.c
Labels: docs-required

#7441 in_tail: teardown and memory initialization fixes
  plugins/in_tail/tail.c
  plugins/in_tail/tail_file.c
Labels: docs-required

#7443 in_tail: added cleanup / initialization in the pending collector
  plugins/in_tail/tail.c
Labels: docs-required

#7444 processor: added cleanup / initialization in the processor loop
  src/flb_processor.c
Labels: docs-required

#7448 processor: added limited concurrency support
  include/fluent-bit/flb_processor.h
  src/flb_processor.c
Labels: docs-required

#7446 multiline: make the multiline core use the appropriate scheduler
  src/multiline/flb_ml.c
  tests/internal/multiline.c
Labels: docs-required

#7445 multiline: make the multiline core use the appropriate scheduler
  src/multiline/flb_ml.c
  tests/internal/multiline.c
Labels: docs-required

#7450 in_emitter: added automatic threading detection workaround
  plugins/in_emitter/emitter.c
Labels: docs-required

#7442 filter_lua: remove unused variables
  plugins/filter_lua/lua.c
Labels: docs-required

#7452 workflows: fix typo in increment version
  .github/workflows/staging-release.yaml
Labels: docs-required

#7454 lib: monkey: upgrade to 13a4ccd3
  lib/monkey/include/monkey/mk_api.h
  lib/monkey/include/monkey/mk_clock.h
  lib/monkey/include/monkey/mk_config.h
  lib/monkey/include/monkey/mk_plugin.h
  lib/monkey/include/monkey/mk_plugin_net.h
  lib/monkey/include/monkey/mk_scheduler.h
  lib/monkey/include/monkey/mk_static_plugins.h.in
  lib/monkey/mk_core/mk_event_epoll.c
  lib/monkey/mk_core/mk_event_kqueue.c
  lib/monkey/mk_core/mk_event_libevent.c
  lib/monkey/mk_core/mk_event_select.c
  lib/monkey/mk_core/mk_string.c
  lib/monkey/mk_server/mk_clock.c
  lib/monkey/mk_server/mk_fifo.c
  lib/monkey/mk_server/mk_header.c
  lib/monkey/mk_server/mk_http.c
  lib/monkey/mk_server/mk_net.c
  lib/monkey/mk_server/mk_plugin.c
  lib/monkey/mk_server/mk_scheduler.c
  lib/monkey/mk_server/mk_server.c
  lib/monkey/mk_server/monkey.c
  lib/monkey/plugins/CMakeLists.txt
  lib/monkey/plugins/dirlisting/dirlisting.c
  lib/monkey/plugins/liana/liana.c
  lib/monkey/plugins/logger/logger.c
  lib/monkey/plugins/mandril/mandril.c
Labels: docs-required

#7462 compression: added buffer adjust step to get available size
  src/flb_compression.c
Labels: docs-required

#7474 workflows: add sanity check on release
  .github/workflows/staging-release.yaml
Labels: docs-required

#7476 workflows: ensure we have access to bucket name
  .github/workflows/staging-release.yaml
Labels: docs-required

#7484 workflows: fix hash outputs
  .github/workflows/staging-release.yaml
Labels: ci

#7501 in_windows_exporter_metrics: Fix wrong metrics type of free megabytes [backport 2.0]
  plugins/in_windows_exporter_metrics/we_logical_disk.c
Labels: docs-required
