Repository fluent/fluent-bit, pull requests merged in 2023-03, with the labels that each got.

#6880 development: add devcontainer support
  .devcontainer/devcontainer.json
  CODEOWNERS
  DEVELOPER_GUIDE.md
  dockerfiles/Dockerfile
Labels: docs-required

#6808 out_stackdriver: cache token expiration and use it when using cached tokens
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#6834 out_loki: add missing flb_sds_cat for float value
  plugins/out_loki/loki.c
  tests/runtime/out_loki.c
Labels: docs-required

#6935 out_opentelemetry: fixed bugs that caused issue 6899
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#6936 out_opentelemetry: fixed bugs that caused issue 6899
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#6923 out_s3: added missing structure instance in s3_retry_warn calls
  plugins/out_s3/s3.c
Labels: docs-required

#6926 out_loki: use flb_sds_pointer to propagate updated pointer.
  plugins/out_loki/loki.c
Labels: docs-required

#6941 out_loki: add missing flb_sds_cat for float value
  plugins/out_loki/loki.c
  tests/runtime/out_loki.c
Labels: docs-required

#6931 out_loki: fixed race condition / toctou reported in issue 6911
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: ok-to-test, ci/integration-docker-ok, docs-required, draft

#6946 out_loki: pr 6931 backport
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: docs-required

#6952 in_systemd: check return value of sd_journal_add_*(#6951)
  plugins/in_systemd/systemd_config.c
Labels: docs-required

#6537 out_stackdriver: add metric for retried logs
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#6966 in_tail: fix buffer size estimate to support all inotify events
  plugins/in_tail/tail_fs_inotify.c
Labels: docs-required

#6959 packaging: add missing variable
  packaging/update-repos.sh
Labels: packaging

#6979 codeowners: add patrick-stephens to cmake approvers
  CODEOWNERS
Labels: docs-required

#6990 out_s3: backport of PR 6988
  plugins/out_s3/s3.c
  plugins/out_s3/s3.h
  src/aws/flb_aws_util.c
Labels: docs-required

#6994 output: backport of PR 6992
  src/flb_output.c
Labels: docs-required

#6992 output_upstream: set FLB_IO_TCP_KA flag when net.keepalive is true.
  src/flb_output.c
Labels: docs-required

#7018 in_winevtlog: fix missing break
  plugins/in_winevtlog/pack.c
Labels: docs-required

#6875 out_pgsql: pass connection options to postgresql client
  plugins/out_pgsql/pgsql.c
  plugins/out_pgsql/pgsql.h
  plugins/out_pgsql/pgsql_connections.c
Labels: docs-required

#6674 filter_log_to_metrics: Add new filter plugin to generate metrics from logs
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/filter_log_to_metrics/CMakeLists.txt
  plugins/filter_log_to_metrics/log_to_metrics.c
  plugins/filter_log_to_metrics/log_to_metrics.h
  tests/runtime/CMakeLists.txt
  tests/runtime/filter_log_to_metrics.c
Labels: docs-required, ok-package-test

#7040 in_prom_scrape: add buffer_size parameter
  plugins/in_prometheus_scrape/prom_scrape.c
  plugins/in_prometheus_scrape/prom_scrape.h
Labels: docs-required

#6930 tests: internal: fuzzers: record_ac: make malloc failable
  tests/internal/fuzzers/record_ac_fuzzer.c
Labels: docs-required

#7004 sp: release name and exec after using
  src/stream_processor/flb_sp.c
Labels: docs-required

#7003 parser: fix warning that pass size_t as a field precision specifier
  src/flb_parser.c
Labels: docs-required

#7049 packaging: fix missing source packages
  packaging/update-source-packages.sh
Labels: packaging

#7062 out_vivo_exporter: add new option 'http_cors_allow_origin' for CORS handling
  plugins/out_vivo_exporter/vivo.c
  plugins/out_vivo_exporter/vivo.h
  plugins/out_vivo_exporter/vivo_http.c
Labels: docs-required

#7060 in_event_type: add support for interval_sec and interval_nsec options
  plugins/in_event_type/event_type.c
Labels: docs-required

#6879 tests: internal: log: make cache_basic_tmeout more stable
  tests/internal/log.c
Labels: docs-required

#7070 out_vivo_exporter: expose access control headers
  plugins/out_vivo_exporter/vivo_http.c
Labels: docs-required

#7068 tests: runtime: filter_log_to_metrics: fix warning
  tests/runtime/filter_log_to_metrics.c
Labels: docs-required

#7069 tests: runtime: filter_lua: remove warning
  tests/runtime/filter_lua.c
Labels: docs-required

#7072 tests: runtime: filter_nest: fix warning
  tests/runtime/filter_nest.c
Labels: docs-required

#7073 plugin: in_systemd: fix warning
  plugins/in_systemd/systemd_config.c
Labels: docs-required

#7058 pipeline: outputs: azure_kuto: fix upstream node creation
  plugins/out_azure_kusto/azure_kusto_conf.c
Labels: docs-required

#7039 tests: runtime: filter_wasm: make more stable
  tests/runtime/filter_wasm.c
Labels: docs-required

#7021 utils: add plugins_file not found error case
  src/flb_utils.c
Labels: docs-required

#7074 lib: cmetrics: upgrade to v0.5.9
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_cat.c
  lib/cmetrics/tests/cat.c
Labels: docs-required

#7076 lib: flb_libo: upgrade to 4bd9260
  lib/flb_libco/CMakeLists.txt
  lib/flb_libco/libco.c
  lib/flb_libco/ppc64le.c
Labels: docs-required

#6996 tail: always use file->orig_name for the `path_key` even when file is rotated
  plugins/in_tail/tail_file.c
Labels: docs-required, ok-to-merge

#7057 tail: always use file->orig_name for the path_key even when file is rotated.
  plugins/in_tail/tail_file.c
Labels: docs-required

#6932 in_http: added support for custom headers upon successful ingestion
  plugins/in_http/http.c
  plugins/in_http/http.h
  plugins/in_http/http_config.c
  plugins/in_http/http_prot.c
Labels: docs-required
