Repository fluent/fluent-bit, pull requests merged in 2023-06, with the labels that each got.

#7519 in_kubernetes_events: merge in pending fixes and enhancements.
  plugins/in_kubernetes_events/kubernetes_events.c
  plugins/in_kubernetes_events/kubernetes_events.h
  plugins/in_kubernetes_events/kubernetes_events_conf.c
  plugins/in_kubernetes_events/kubernetes_events_sql.h
Labels: docs-required

#7527 packaging: support ARM64 AL2023 builds via Actuated runners
  .github/actionlint.yml
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/pr-package-tests.yaml
  packaging/build-config.json
Labels: docs-required, ok-package-test

#7530 ci: documentation
  .github/workflows/README.md
  .github/workflows/remove-release.yaml
  .github/workflows/resources/auto-build-test-workflow.png
  .github/workflows/resources/release-approval-per-job.png
  .github/workflows/resources/release-approval.png
  .github/workflows/resources/release-from-staging-workflow-incorrect-version.png
  .github/workflows/resources/release-from-staging-workflow.png
  .github/workflows/resources/release-version-failure.png
  packaging/README.md
  packaging/appveyor-download.sh
  packaging/build.sh
  packaging/server/README.md
  packaging/server/aptly.conf
  packaging/server/create-aptly-repo.sh
  packaging/server/publish-all.sh
  packaging/server/publish-manual.sh
  packaging/skopeo-sync.sh
  packaging/sync-releases-to-bucket.sh
  packaging/test-release-packages.sh
  packaging/testing/README.md
  packaging/update-apt-repo.sh
  packaging/update-source-packages.sh
  packaging/update-yum-repo.sh
  packaging/windows-checksums.sh
Labels: ci

#7531 workflows: minor updates
  .github/workflows/README.md
Labels: docs-required

#7535 in_kubernetes_events: fix error when lastTimestamp is missing.
  plugins/in_kubernetes_events/kubernetes_events.c
Labels: docs-required

#7438 out_stackdriver: process traceSampled special field
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  tests/runtime/data/stackdriver/stackdriver_test_trace_sampled.h
  tests/runtime/out_stackdriver.c
Labels: docs-required

#7533 workflows: ensure we install AWS dependencies
  .github/workflows/call-build-linux-packages.yaml
Labels: ci

#7544 out_stackdriver: process traceSampled special field
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  tests/runtime/data/stackdriver/stackdriver_test_trace_sampled.h
  tests/runtime/out_stackdriver.c
Labels: docs-required

#7529 in_node_exporter_metrics: textfile: Plug unhandled NULL case
  plugins/in_node_exporter_metrics/ne_textfile_linux.c
Labels: docs-required

#7495 in_windows_exporter_metrics: Fix wrong metrics type of free megabytes
  plugins/in_windows_exporter_metrics/we_logical_disk.c
Labels: docs-required

#7207 plugins: exec: exit fluent-bit after oneshot and propagate exit code
  CMakeLists.txt
  cmake/platform_feature_checks.cmake
  plugins/in_exec/in_exec.c
  plugins/in_exec/in_exec.h
  plugins/in_exec/in_exec_win32_compat.h
Labels: docs-required, ok-package-test

#7514 in_node_exporter_metrics: update systemd metrics regardless their states
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_systemd.c
Labels: docs-required

#7155 out_azure_logs_ingestion: Implementing Azure Logs Ingestion (with DCR, DCE) output plugin
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_azure_logs_ingestion/CMakeLists.txt
  plugins/out_azure_logs_ingestion/azure_logs_ingestion.c
  plugins/out_azure_logs_ingestion/azure_logs_ingestion.h
  plugins/out_azure_logs_ingestion/azure_logs_ingestion_conf.c
  plugins/out_azure_logs_ingestion/azure_logs_ingestion_conf.h
Labels: docs-required, ok-package-test

#7565 lib: cmetrics: upgrade to v0.6.2
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_encode_opentelemetry.c
Labels: docs-required

#7159 out_cloudwatch_logs: fix logic in free-ing log streams on shutdown
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
  plugins/out_cloudwatch_logs/cloudwatch_logs.h
Labels: docs-required

#7160 out_cloudwatch_logs: fix logic in free-ing log streams on shutdown
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
  plugins/out_cloudwatch_logs/cloudwatch_logs.h
Labels: docs-required

#7357 aws: sts_credentials: make STS response parsing less brittle by checking for the full XML end node
  src/aws/flb_aws_credentials_sts.c
Labels: docs-required

#7393 out_s3: fix wrong decrementing of INDEX when UploadPart fails
  plugins/out_s3/s3.c
Labels: docs-required

#7358 aws: sts_credentials: make STS response parsing less brittle by checking for the full XML end node
  src/aws/flb_aws_credentials_sts.c
Labels: docs-required

#7394 out_s3: fix wrong decrementing of INDEX when UploadPart fails
  plugins/out_s3/s3.c
Labels: docs-required

#7588 ci: set a version for Chocolatey
  .github/workflows/pr-image-tests.yaml
  dockerfiles/Dockerfile.windows
Labels: Windows, packaging

#7594 ci: set a version for Chocolatey (#7588) - 2.0 backport
  .github/workflows/pr-image-tests.yaml
  dockerfiles/Dockerfile.windows
Labels: docs-required

#7586 upstream: new property to limit the amount of active TCP connections
  include/fluent-bit/flb_network.h
  src/flb_upstream.c
Labels: docs-required

#7576 downstream: fixed the event loop registration detection mechanism
  src/flb_downstream.c
Labels: docs-required

#7603 workflows: fix the version used for updating PRs
  .github/workflows/staging-release.yaml
Labels: ci

#7631 workflows: fix up OpenSSF Scorecard workflow
  .github/workflows/cron-scorecards-analysis.yaml
Labels: ci

#7585 log_event_decoder: use flb_free
  src/flb_log_event_decoder.c
Labels: docs-required
