Repository fluent/fluent-bit, pull requests merged in 2023-07, with the labels that each got.

#7637 log_event_decoder: fix wrong api name
  include/fluent-bit/flb_log_event_decoder.h
Labels: docs-required

#7489 tests: runtime: in_otel: add test code
  tests/runtime/CMakeLists.txt
  tests/runtime/in_opentelemetry.c
Labels: docs-required

#7640 out_gelf: fix releasing function handling
  plugins/out_gelf/gelf.c
Labels: docs-required

#7639 out_syslog: check error after flb_log_event_decoder_next
  plugins/out_syslog/syslog.c
Labels: docs-required

#7557 in_kubernetes_events: increase interval to 500 milliseconds.
  plugins/in_kubernetes_events/kubernetes_events.h
Labels: docs-required

#7560 in_kubernetes_events: allow listening to a single namespace.
  plugins/in_kubernetes_events/kubernetes_events.c
  plugins/in_kubernetes_events/kubernetes_events.h
  plugins/in_kubernetes_events/kubernetes_events_conf.h
Labels: docs-required

#7567 in_kubernetes_events: allow setting kube_token_file as empty for use with kubectl proxy.
  plugins/in_kubernetes_events/kubernetes_events.c
Labels: docs-required

#7532 in_kubernetes_events: call destructor when init failed
  plugins/in_kubernetes_events/kubernetes_events_conf.c
Labels: docs-required

#7622 build: Install config_format headers
  include/CMakeLists.txt
Labels: docs-required

#7628 filter_rewrite_tag: fix potential NULL dereference
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#7349 in_splunk: Implement Splunk HEC input plugin
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_splunk/CMakeLists.txt
  plugins/in_splunk/splunk.c
  plugins/in_splunk/splunk.h
  plugins/in_splunk/splunk_config.c
  plugins/in_splunk/splunk_config.h
  plugins/in_splunk/splunk_conn.c
  plugins/in_splunk/splunk_conn.h
  plugins/in_splunk/splunk_prot.c
  plugins/in_splunk/splunk_prot.h
  tests/runtime/CMakeLists.txt
  tests/runtime/in_splunk.c
Labels: docs-required

#7464 utils: plugin: freeing properly for duplicated string shared properties
  include/fluent-bit/flb_utils.h
  src/flb_custom.c
  src/flb_filter.c
  src/flb_input.c
  src/flb_output.c
  src/flb_utils.c
Labels: docs-required

#7579 in_elasticsearch: provide version parameter for configurable server version
  plugins/in_elasticsearch/in_elasticsearch.c
  plugins/in_elasticsearch/in_elasticsearch.h
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.h
  tests/runtime/in_elasticsearch.c
Labels: docs-required

#7602 in_node_exporter_metrics: handle not as error when missing cpu_throttle_metrics
  plugins/in_node_exporter_metrics/ne_cpu_linux.c
Labels: docs-required

#7504 in_podman_metrics: Fixed reading undefined PID
  plugins/in_podman_metrics/podman_metrics_config.h
  plugins/in_podman_metrics/podman_metrics_data.c
  tests/runtime/data/podman/cgroupv2/42/net/dev
  tests/runtime/data/podman/cgroupv2/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/containers/cgroup.procs
  tests/runtime/data/podman/cgroupv2/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/data/podman/garbage/42/net/dev
  tests/runtime/data/podman/no_sysfs/42/net/dev
  tests/runtime/data/podman/regular/42/net/dev
  tests/runtime/data/podman/regular/systemd/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/cgroup.procs
  tests/runtime/data/podman/reversed/42/net/dev
  tests/runtime/data/podman/reversed/systemd/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/cgroup.procs
  tests/runtime/in_podman_metrics.c
Labels: docs-required

#7642 lib: cmetrics: upgrade to v0.6.3
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_opentelemetry.c
Labels: docs-required

#7575 downstream: fixed the event loop registration detection mechanism
  src/flb_downstream.c
Labels: docs-required

#7517 in_kubernetes_filter: fix leak on exception
  plugins/filter_kubernetes/kube_meta.c
Labels: docs-required

#7630 workflows: enable sarif output for CIFuzz
  .github/workflows/pr-fuzz.yaml
Labels: ci

#7626 in_exec_wasi: fix possible NULL deref
  plugins/in_exec_wasi/in_exec_wasi.c
Labels: docs-required

#7685 backport: aws: imds: set length when initializing token to dummy value
  src/aws/flb_aws_imds.c
Labels: docs-required

#7680 upstream: fix logic to restrict number of connections
  src/flb_upstream.c
Labels: docs-required

#7232 out_chronicle: Implement Google Chronicle output plugin
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/out_chronicle/CMakeLists.txt
  plugins/out_chronicle/chronicle.c
  plugins/out_chronicle/chronicle.h
  plugins/out_chronicle/chronicle_conf.c
  plugins/out_chronicle/chronicle_conf.h
Labels: docs-required, ok-package-test

#7101 out_stackdriver: support gzip compression
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#7693 CODEOWNERS: Add codeowners for out_stackdriver
  CODEOWNERS
Labels: docs-required

#7692 codeowners: add pwhelan for calyptia and calyptia fleet.
  CODEOWNERS
Labels: docs-required

#7705 downstream: remove not used variable
  src/flb_downstream.c
Labels: docs-required

#7700 fix typo in CMakeLists.txt
  CMakeLists.txt
Labels: docs-required

#7675 build: test: Fix an invalid constant for filter_rewrite_tag
  tests/runtime/CMakeLists.txt
Labels: docs-required

#7719 build: Install OpenSSL with chocolatey only for x64
  .github/workflows/call-build-windows.yaml
Labels: ci, ok-package-test

#7717 calyptia_fleet: fix non existent plugin name.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#6960 in_http: add support for form/url_encoded payloads.
  plugins/in_http/http_prot.c
Labels: docs-required, exempt-stale

#7731 lib: monkey: upgrade to v1.7.1 (fix warnings)
  lib/monkey/CMakeLists.txt
  lib/monkey/include/monkey/mk_config.h
  lib/monkey/include/monkey/mk_mimetype.h
  lib/monkey/include/monkey/mk_plugin.h
  lib/monkey/include/monkey/mk_server.h
  lib/monkey/include/monkey/monkey.h
  lib/monkey/mk_bin/mk_signals.h
  lib/monkey/mk_server/mk_server.c
Labels: docs-required

#6726 trace: add new command line options for enabling tracing at startup.
  include/fluent-bit/flb_lib.h
  src/flb_chunk_trace.c
  src/flb_lib.c
  src/fluent-bit.c
  src/http_server/api/v1/trace.c
Labels: docs-required

#7734 chunk_traces: update the help for '--enable-chunk-trace'.
  src/fluent-bit.c
Labels: docs-required

#7651 in_syslog: Provide appending source address parameter
  plugins/in_syslog/syslog.c
  plugins/in_syslog/syslog.h
  plugins/in_syslog/syslog_conn.c
  plugins/in_syslog/syslog_prot.c
  plugins/in_syslog/syslog_prot.h
  tests/runtime/in_syslog.c
Labels: docs-required

#7735 fluent-bit: remove cleanup code from flb_signal_exit
  src/fluent-bit.c
Labels: docs-required

#7766 workflows: disable provenance for legacy format images
  .github/workflows/build-legacy-branch.yaml
  .github/workflows/call-build-images.yaml
  .github/workflows/call-integration-image-build.yaml
  .github/workflows/pr-compile-check.yaml
  .github/workflows/pr-image-tests.yaml
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok, ci

#7767 workflows: add extra push of arch-specfic images
  .github/workflows/staging-release.yaml
Labels: ci

#7764 workflows: windows: Use vcpkg to install dependencies
  .github/workflows/call-build-windows.yaml
Labels: docs-required
