Repository fluent/fluent-bit, pull requests merged in 2023-08, with the labels that each got.

#7773 workflows: windows: Implement cache mechanism for source packages of vcpkg
  .github/workflows/call-build-windows.yaml
Labels: ci, ok-package-test

#7780 workflow: windows: Make more rigid handling for caches
  .github/workflows/call-build-windows.yaml
Labels: ok-to-test, ci/integration-docker-ok, docs-required, ok-package-test

#7794 ci: add codeowner celalettin1286
  CODEOWNERS
Labels: docs-required

#7768 config_format: fix possible heap overflow
  src/config_format/flb_config_format.c
Labels: docs-required

#7744 tests: fuzzers: utils_fuzzer: extend
  tests/internal/fuzzers/utils_fuzzer.c
Labels: docs-required

#7745 tests: internal: fuzzers: cmetrics_fuzzer: extend
  tests/internal/fuzzers/cmetrics_decode_fuzz.c
Labels: docs-required

#7746 tests: internal: fuzzers: add input fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/input_fuzzer.c
Labels: docs-required

#7806 flb_utils: remove false positive error 'file not found'.
  src/flb_utils.c
Labels: docs-required

#7774 aws: macos: prevent buffer overflow on address sanitier
  src/aws/flb_aws_util.c
Labels: docs-required

#7812 input: send resume signal to the input thread event loop if plugin is threaded
  include/fluent-bit/flb_input_thread.h
  src/flb_input.c
  src/flb_input_chunk.c
  src/flb_input_thread.c
Labels: docs-required

#7783 config: throw an error if a configuration property is not applied.
  src/flb_config.c
Labels: docs-required

#7817 in_windows_exporter_metrics: Implement WMI based memory and paging_file metrics
  plugins/in_windows_exporter_metrics/CMakeLists.txt
  plugins/in_windows_exporter_metrics/we.c
  plugins/in_windows_exporter_metrics/we.h
  plugins/in_windows_exporter_metrics/we_wmi_memory.c
  plugins/in_windows_exporter_metrics/we_wmi_memory.h
  plugins/in_windows_exporter_metrics/we_wmi_paging_file.c
  plugins/in_windows_exporter_metrics/we_wmi_paging_file.h
Labels: docs-required

#7661 yaml/v2: use stack based parser.
  include/fluent-bit/flb_processor.h
  src/config_format/flb_cf_yaml.c
  src/config_format/flb_config_format.c
  src/flb_processor.c
  tests/internal/config_format_yaml.c
  tests/internal/data/config_format/yaml/fluent-bit.yaml
  tests/internal/data/config_format/yaml/parsers/parsers-conf.yaml
  tests/internal/data/config_format/yaml/parsers/parsers.conf
  tests/internal/data/config_format/yaml/pipelines/slist/even.yaml
  tests/internal/data/config_format/yaml/pipelines/slist/odd.yaml
  tests/internal/processor.c
Labels: docs-required

#7816 tests: internal: fuzzers: add config yaml fuzzer
  CMakeLists.txt
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/config_yaml_fuzzer.c
Labels: docs-required

#7819 tests: internal: fuzzers: add mp fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/flb_mp_fuzzer.c
Labels: docs-required

#7809 emitter_create: exit and destroy instance on fail
  plugins/filter_multiline/ml.c
  plugins/filter_rewrite_tag/rewrite_tag.c
Labels: docs-required

#7808 out_kinesis_streams: remove dead stores
  plugins/out_kinesis_streams/kinesis_api.c
Labels: docs-required

#7848 in_winevtlog: Support XML query parameter for filtering events
  plugins/in_winevtlog/in_winevtlog.c
  plugins/in_winevtlog/winevtlog.c
  plugins/in_winevtlog/winevtlog.h
Labels: docs-required

#7810 in_exec_wasi: fix possible file descriptor leak
  plugins/in_exec_wasi/in_exec_wasi.c
Labels: docs-required

#7857 yaml/v2: suppress debug messages.
  src/config_format/flb_cf_yaml.c
Labels: docs-required

#7884 out_splunk: release flb_ra_translate result buffer on failure
  plugins/out_splunk/splunk.c
Labels: docs-required

#7885 out_splunk: release flb_ra_translate result buffer on failure
  plugins/out_splunk/splunk.c
Labels: docs-required

#7877 config_format: yaml: fix null dereference
  src/config_format/flb_cf_yaml.c
Labels: docs-required

#7876 in_node_exporter_metrics: Fix registering callback for systemd metrics
  plugins/in_node_exporter_metrics/ne.c
Labels: docs-required

#7860 in_windows_exporter_metrics: Implement WMI based process metrics
  plugins/in_windows_exporter_metrics/CMakeLists.txt
  plugins/in_windows_exporter_metrics/we.c
  plugins/in_windows_exporter_metrics/we.h
  plugins/in_windows_exporter_metrics/we_config.c
  plugins/in_windows_exporter_metrics/we_wmi_process.c
  plugins/in_windows_exporter_metrics/we_wmi_process.h
Labels: docs-required

#7673 in_udp: Add a capability to inject source IP
  plugins/in_udp/udp.c
  plugins/in_udp/udp.h
  plugins/in_udp/udp_conn.c
  plugins/in_udp/udp_conn.h
  tests/runtime/CMakeLists.txt
  tests/runtime/in_udp.c
Labels: docs-required

#7669 in_lib: fix error handling after flb_log_event_decoder_next
  plugins/in_lib/in_lib.c
Labels: docs-required
