Repository fluent/fluent-bit, pull requests merged in 2023-09, with the labels that each got.

#7873 in_nginx_exporter_metrics: add missing release function
  plugins/in_nginx_exporter_metrics/nginx.c
Labels: docs-required

#7837 utils: suppress errno when file is empty but readable.
  src/flb_utils.c
Labels: docs-required

#7791 fleet: correctly register fleet agent.
  plugins/custom_calyptia/calyptia.c
Labels: docs-required

#7847 input: apply back pressure if input threaded plugin is paused
  src/flb_input_chunk.c
Labels: docs-required

#7869 tests: internal: stream_processor: fix when test path is too long.
  tests/internal/stream_processor.c
Labels: docs-required

#7907 tests: internal: log_event_decoder: add test for log_event_decoder
  tests/internal/CMakeLists.txt
  tests/internal/log_event_decoder.c
Labels: docs-required

#7897 out_forward: add new 'add_option' configuration property
  plugins/out_forward/forward.c
  plugins/out_forward/forward.h
  plugins/out_forward/forward_format.c
Labels: docs-required

#7949 out_loki: add compress option for gzip
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: docs-required

#7951 lib: monkey: upgrade to v1.7.2
  lib/monkey/CMakeLists.txt
  lib/monkey/mk_core/external/winpthreads.c
Labels: docs-required

#7932 processor: replace tab with white space
  src/flb_processor.c
Labels: docs-required

#7952 out_http: Fix bug where post_all_requests() always returns a value less than 0
  plugins/out_http/http.c
Labels: docs-required

#7830 feat: oci logging analytics output plugin implementation
  CMakeLists.txt
  plugins/CMakeLists.txt
  plugins/out_oracle_log_analytics/CMakeLists.txt
  plugins/out_oracle_log_analytics/oci_logan.c
  plugins/out_oracle_log_analytics/oci_logan.h
  plugins/out_oracle_log_analytics/oci_logan_conf.c
  plugins/out_oracle_log_analytics/oci_logan_conf.h
Labels: docs-required, ok-package-test

#7931 engine: add sleep to output logs on init
  src/flb_engine.c
Labels: docs-required

#7962 scheduler: use calloc instead of malloc
  src/flb_scheduler.c
Labels: docs-required

#7922 plugin_proxy: Handle no ingestion case
  src/flb_plugin_proxy.c
Labels: docs-required

#7901 input_chunk: Use flb_plg_debug instead of normal printf
  src/flb_input_chunk.c
Labels: docs-required

#7739 filter_log_to_metrics: Add setting "label"
  plugins/filter_log_to_metrics/log_to_metrics.c
  plugins/filter_log_to_metrics/log_to_metrics.h
  tests/runtime/filter_log_to_metrics.c
Labels: docs-required

#7663 out_azure: improvement: add table prefix support for Azure Log Analytics plugin
  plugins/out_azure/azure.c
  plugins/out_azure/azure.h
  plugins/out_azure/azure_conf.c
Labels: docs-required, ok-package-test

#7629 out_logdna: remove unused store
  plugins/out_logdna/logdna.c
Labels: docs-required

#7624 out_azure_logs_ingestion: fix NULL dereference
  plugins/out_azure_logs_ingestion/azure_logs_ingestion.c
Labels: docs-required

#6465 tests: internal: fuzzers: add fstore fuzzer
  tests/internal/fuzzers/CMakeLists.txt
  tests/internal/fuzzers/fstore_fuzzer.c
Labels: Stale, docs-required

#7646 log_evnet_encoder: fix typo
  src/flb_log_event_encoder.c
Labels: docs-required

#7247 in_systemd: init last_tag to fix valgrind warning
  plugins/in_systemd/systemd.c
Labels: docs-required

#6064 out_es: check if host contains port number
  plugins/out_es/es_conf.c
Labels: enhancement, Stale, docs-required

#7762 tests: internal: input_chunk: Use the different storage.path per tests
  tests/internal/input_chunk.c
Labels: docs-required

#7974 tests: fuzzers: fix fstore div-by-zero
  tests/internal/fuzzers/fstore_fuzzer.c
Labels: docs-required

#7975 tests: internal: stream_processor: fixed memory leak
  tests/internal/stream_processor.c
Labels: docs-required

#7977 tests: fuzzers: fix possible NULL deref
  tests/internal/fuzzers/fstore_fuzzer.c
Labels: docs-required
