Repository fluent/fluent-bit, pull requests merged in 2023-10, with the labels that each got.

#7986 bin: windows: Restore Ctrl-C behavior on windows
  src/fluent-bit.c
Labels: docs-required

#7998 bin: windows: restore ctrl c behavior on windows [backport 2.1]
  src/fluent-bit.c
Labels: docs-required, ok-package-test

#7999 documentation: update users graphic
  documentation/fluentbit_users.png
Labels: docs-required

#6896 out_syslog: when using a message key, avoid prefixing raw messages
  plugins/out_syslog/syslog.c
Labels: docs-required

#7970 flb_utils: add code to get the machine-id on windows machines.
  src/flb_utils.c
Labels: docs-required

#7984 http_server: v2: reload: windows: Enable hot reloading
  src/http_server/api/v2/reload.c
Labels: docs-required

#7992 tests: internal: log_event_encoder: add test code
  tests/internal/CMakeLists.txt
  tests/internal/log_event_encoder.c
Labels: docs-required

#8040 out_loki: add new option 'uri' to customize HTTP URI endpoint
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: docs-required

#8020 version: happy new year 2023
  include/fluent-bit/flb_version.h.in
Labels: docs-required

#7880 in_node_exporter_metrics: implement processes metrics
  plugins/in_node_exporter_metrics/CMakeLists.txt
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_processes.c
  plugins/in_node_exporter_metrics/ne_processes.h
  plugins/in_node_exporter_metrics/ne_processes_linux.c
Labels: docs-required

#8048 node_exporter_metrics: Fix macOS build
  plugins/in_node_exporter_metrics/ne_processes.h
Labels: docs-required

#8019 in_node_exporter_metrics: fix referencing wrong interval between cpu and cpufreq
  plugins/in_node_exporter_metrics/ne.c
Labels: docs-required

#8015 in_forward: fix checking return value of cmt_decode_msgpack_create(#8000)
  plugins/in_forward/fw_prot.c
Labels: docs-required

#7973 cloudwatch_logs: remove sequence tokens from API calls
  plugins/out_cloudwatch_logs/cloudwatch_api.c
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
  plugins/out_cloudwatch_logs/cloudwatch_logs.h
  src/aws/flb_aws_util.c
Labels: docs-required

#8044 input: Add ingestion_paused metrics to confirm whether an input plugin is paused or not
  include/fluent-bit/flb_input.h
  src/flb_input.c
Labels: docs-required

#8041 fluent-bit: modify hot reload handler
  src/fluent-bit.c
Labels: docs-required

#8065 lib: cmetrics: upgrade to v0.6.4
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_msgpack.c
Labels: docs-required

#8070 workflows: update Actuated sizes [backport to 2.1]
  .github/actionlint.yml
  .github/workflows/call-build-linux-packages.yaml
Labels: docs-required

#8069 workflows: update Actuated sizes and use CNCF runners
  .github/actionlint.yml
  .github/workflows/call-build-linux-packages.yaml
Labels: docs-required, ok-package-test

#7978 custom_calyptia: free machine_id when it is automatically set.
  plugins/custom_calyptia/calyptia.c
Labels: docs-required

#8087 in_docker: Implement a capability for cgroups V2
  plugins/in_docker/CMakeLists.txt
  plugins/in_docker/cgroup_v2.c
  plugins/in_docker/docker.c
  plugins/in_docker/docker.h
Labels: docs-required

#8089 custom_calyptia: correctly set fleet_id for out_calyptia when fleet_name is set.
  plugins/custom_calyptia/calyptia.c
Labels: docs-required

#8090 in_calyptia_fleet: remove unused event_fd configuration property.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#8091 in_calyptia_fleet: add old configuration file to checks.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#8074 reload: add missing flb_cf_destroy [backport 2.1]
  src/flb_reload.c
Labels: docs-required

#8113 workflows: update to handle 2.2 releases
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/README.md
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/staging-release.yaml
  .github/workflows/unit-tests.yaml
Labels: ci
