Repository fluent/fluent-bit, pull requests merged in 2023-01, with the labels that each got.

#6552 tail: add a progress check interval to catch files that fall behind.
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.h
  plugins/in_tail/tail_fs_inotify.c
Labels: docs-required

#6594 out_stackdriver: Revert "stackdriver: cache token expiration and use it when using cached tokens"
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#6615 packaging: fix server publishing for Debian Bookworm
  packaging/server/create-aptly-repo.sh
  packaging/server/publish-all.sh
Labels: docs-required

#6678 packaging: more changes for switchover
  .github/workflows/staging-release.yaml
  install.sh
  packaging/appveyor-download.sh
  packaging/test-release-packages.sh
  packaging/update-source-packages.sh
Labels: packaging

#6653 config_format: fix memory leak
  src/config_format/flb_config_format.c
Labels: docs-required

#6654 aws: fix freeing arbitrary memory
  src/aws/flb_aws_credentials.c
Labels: docs-required

#6673 input: compare max_chunks_up to total_chunks_up not total_chunks.
  src/flb_input_chunk.c
Labels: docs-required

#6680 install: Base RELEASE_KEY default off RELEASE_URL which will have a default
  install.sh
Labels: docs-required

#6686 install: resolve various niggles
  .github/workflows/pr-install-script.yaml
  install.sh
  packaging/test-release-packages.sh
Labels: packaging

#6693 install: specify version to install script
  install.sh
  packaging/test-release-packages.sh
Labels: packaging

#6655 signv4: handle error case
  src/flb_signv4.c
Labels: docs-required

#6707 lib: onigmo: Upgrade fluent/onigmo
  lib/onigmo/.gitignore
  lib/onigmo/.travis.yml
  lib/onigmo/doc/UnicodeProps.txt
  lib/onigmo/enc/unicode/casefold.h
  lib/onigmo/enc/unicode/name2ctype.h
  lib/onigmo/onigmo.h
  lib/onigmo/regcomp.c
  lib/onigmo/regenc.c
  lib/onigmo/regenc.h
  lib/onigmo/regexec.c
  lib/onigmo/regint.h
  lib/onigmo/regparse.c
  lib/onigmo/tool/Makefile
  lib/onigmo/tool/case-folding.rb
  lib/onigmo/tool/download-ucd.sh
  lib/onigmo/tool/update-doc.py
Labels: docs-required

#6716 signv4: clean up if failed split string
  src/flb_signv4.c
Labels: docs-required

#6734 packaging: enable kafka SASL mechanisms support for Debian and Ubuntu
  packaging/distros/debian/Dockerfile
  packaging/distros/ubuntu/Dockerfile
Labels: packaging, ok-package-test

#6739 packaging: add pkg-config dependency for the Raspbian builds
  packaging/distros/raspbian/Dockerfile
Labels: ok-package-test

#6738 in_forward: fixed memory leak when sending ACK
  plugins/in_forward/fw_prot.c
Labels: docs-required

#6744 packaging: librdkafka SASL_SCRAM and GZIP support on all targets
  packaging/distros/amazonlinux/Dockerfile
  packaging/distros/centos/Dockerfile
  packaging/distros/ubuntu/Dockerfile
Labels: packaging, ok-package-test

#6742 tls: add missing mutex unlock
  src/tls/openssl.c
Labels: docs-required

#6740 in_node_exporter_metrics: initial commit of the filesystem collector
  plugins/in_node_exporter_metrics/CMakeLists.txt
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_filesystem.c
  plugins/in_node_exporter_metrics/ne_filesystem.h
  plugins/in_node_exporter_metrics/ne_filesystem_linux.c
Labels: docs-required

#6736 lib: monkey: Upgrade to b096cd6063b5d058caac53bade70c851f8672038
  lib/monkey/mk_core/external/winpthreads.c
Labels: docs-required

#6328 flb_aws_util: added function flb_aws_strftime_precision for time output
  include/fluent-bit/flb_aws_util.h
  plugins/out_kinesis_firehose/firehose_api.c
  plugins/out_kinesis_streams/kinesis_api.c
  src/aws/flb_aws_util.c
Labels: docs-required

#6434 out_s3: updated for getting upload time from timestamp.
  plugins/out_s3/s3.c
  plugins/out_s3/s3_store.c
  plugins/out_s3/s3_store.h
Labels: docs-required

#6749 out_opentelemetry: fix memory leak and invalid free
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#6729 upstream: fixed memory leaks in configuration
  include/fluent-bit/flb_upstream_node.h
  src/flb_upstream_ha.c
  src/flb_upstream_node.c
Labels: docs-required

#6714 input_chunk: use total_chunks_up in overlimit warn message
  src/flb_input_chunk.c
Labels: docs-required

#6713 aws_util: refreshing creds is an info level event
  src/aws/flb_aws_util.c
Labels: docs-required

#6697 network: test: internal: Prevent Infinite loop for no IPv6 environment
  tests/internal/network.c
Labels: docs-required

#6719 input_chunk: info level instead of debug for chunk removal msg
  src/flb_input_chunk.c
Labels: docs-required

#6750 out_datadog: fix buffer resize logic (#6750)
  plugins/out_datadog/datadog.c
Labels: docs-required

#6657 tests: internal: log: make cache_basic_timeout more stable
  tests/internal/log.c
Labels: docs-required

#6752 lib: monkey: upgrade to 6f9be603
  lib/monkey/mk_server/mk_fifo.c
Labels: docs-required

#6755 CMakeLists.txt: only require a C compiler
  CMakeLists.txt
Labels: docs-required, ok-package-test
