Repository fluent/fluent-bit, pull requests merged in 2023-04, with the labels that each got.

#7097 lib: cmetrics: upgrade to v0.6.0
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_encode_msgpack.c
Labels: docs-required, ok-package-test

#7098 lib: cmetrics: upgrade to v0.6.0
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_cat.c
  lib/cmetrics/src/cmt_decode_msgpack.c
  lib/cmetrics/src/cmt_encode_msgpack.c
  lib/cmetrics/tests/cat.c
Labels: docs-required

#7103 lib: ctraces: upgrade to v0.3.0
  lib/ctraces/CMakeLists.txt
  lib/ctraces/include/ctraces/ctr_id.h
  lib/ctraces/src/ctr_decode_msgpack.c
  lib/ctraces/src/ctr_encode_msgpack.c
  lib/ctraces/src/ctr_id.c
Labels: docs-required

#7110 packaging: AL2023 backport support
  .github/actions/generate-package-build-matrix/action.yaml
  .github/workflows/build-legacy-branch.yaml
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-linux-packages.yaml
  .github/workflows/call-build-macos.yaml
  .github/workflows/call-build-windows.yaml
  .github/workflows/call-integration-image-build.yaml
  .github/workflows/cron-scorecards-analysis.yaml
  .github/workflows/cron-stale.yaml
  .github/workflows/cron-unstable-build.yaml
  .github/workflows/pr-compile-check.yaml
  .github/workflows/pr-image-tests.yaml
  .github/workflows/pr-windows-build.yaml
  .github/workflows/staging-release.yaml
  .github/workflows/unit-tests.yaml
  dockerfiles/Dockerfile
  packaging/build-config.json
  packaging/distros/amazonlinux/Dockerfile
  packaging/test-release-packages.sh
  packaging/update-apt-repo.sh
  packaging/update-repos.sh
  packaging/update-source-packages.sh
  packaging/update-yum-repo.sh
Labels: docs-required, packaging

#7118 lib: cfl: upgrade to v0.2.1
  lib/cfl/CMakeLists.txt
  lib/cfl/src/cfl_array.c
Labels: docs-required

#7125 workflows: fix automation for release
  .github/workflows/staging-release.yaml
  packaging/test-release-packages.sh
  packaging/update-apt-repo.sh
Labels: ci

#7131 lib: cmetrics: upgrade to v0.6.1
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_atomic_msvc.c
Labels: docs-required

#7132 lib: cmetrics: upgrade to v0.6.1
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_atomic_msvc.c
Labels: docs-required

#7137 aws: fixed the typo in the line that defined random_data
  src/aws/flb_aws_credentials_sts.c
Labels: docs-required

#7138 aws: fixed the typo in the line that defined random_data
  src/aws/flb_aws_credentials_sts.c
Labels: docs-required

#7030 node_exporter_metrics: textfile: Implement textfile metrics on node_exporter
  plugins/in_node_exporter_metrics/CMakeLists.txt
  plugins/in_node_exporter_metrics/ne.c
  plugins/in_node_exporter_metrics/ne.h
  plugins/in_node_exporter_metrics/ne_textfile.c
  plugins/in_node_exporter_metrics/ne_textfile.h
  plugins/in_node_exporter_metrics/ne_textfile_linux.c
Labels: docs-required

#7139 input_chunk: changed order of operations when flushing a chunk
  src/flb_input_chunk.c
Labels: docs-required

#7140 input_chunk: changed order of operations when flushing a chunk
  src/flb_input_chunk.c
Labels: docs-required

#7100 out_forward: fix warning
  plugins/out_forward/forward.c
Labels: docs-required

#6997 tail: always use file->orig_name for the `path_key` even when file is rotated.
  plugins/in_tail/tail_file.c
Labels: docs-required

#7099 tests: runtime: filter_parser: make more stable
  tests/runtime/filter_parser.c
Labels: docs-required

#6658 in_docker: prepare to support cgroup v2
  plugins/in_docker/CMakeLists.txt
  plugins/in_docker/cgroup_v1.c
  plugins/in_docker/docker.c
  plugins/in_docker/docker.h
Labels: docs-required

#6833 trace: remove unused variable
  src/http_server/api/v1/trace.c
Labels: docs-required

#6788 out_syslog: add allow_longer_sd_id property
  plugins/out_syslog/syslog.c
  plugins/out_syslog/syslog_conf.c
  plugins/out_syslog/syslog_conf.h
  tests/runtime/out_syslog.c
Labels: docs-required

#7102 input: use pthread_key to handle flb_libco_in_params
  include/fluent-bit/flb_input.h
  src/flb_input.c
Labels: docs-required

#7144 filter_grep: remove unused val
  plugins/filter_grep/grep.c
Labels: docs-required

#6845 upstream: remove keepalive close event on cleanup
  src/flb_upstream.c
Labels: docs-required

#7167 lib: monkey: upgrade to 798fde05
  lib/monkey/include/monkey/mk_cache_tls.h
  lib/monkey/include/monkey/mk_scheduler_tls.h
  lib/monkey/include/monkey/mk_server_tls.h
  lib/monkey/include/monkey/mk_tls.h
  lib/monkey/include/monkey/mk_vhost_tls.h
  lib/monkey/mk_core/mk_event_libevent.c
Labels: docs-required

#7163 lib: monkey: upgrade to 798fde05
  lib/monkey/include/monkey/mk_cache_tls.h
  lib/monkey/include/monkey/mk_scheduler_tls.h
  lib/monkey/include/monkey/mk_server_tls.h
  lib/monkey/include/monkey/mk_tls.h
  lib/monkey/include/monkey/mk_vhost_tls.h
  lib/monkey/mk_core/mk_event_libevent.c
Labels: docs-required

#6944 workflows: add GKE auth plugin
  .github/workflows/call-run-integration-test.yaml
Labels: ok-to-test, ci/integration-docker-ok, docs-required

#7142 tests: runtime: filter_modify: fix warning
  tests/runtime/filter_modify.c
Labels: docs-required

#7083 out_cloudwatch_logs: support tls verify and port options
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
Labels: docs-required

#6818 core: sync scheduler resolve multi task user issue
  src/flb_output.c
Labels: docs-required

#7179 in_calyptia_fleet: initial implementation of calyptia fleet management.
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_calyptia_fleet/CMakeLists.txt
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
  src/flb_lib.c
Labels: docs-required

#7172 CODEOWNERS: add PettitWesley as code owner for AWS filter tests
  CODEOWNERS
Labels: docs-required

#7020 filter_wasm: skip log on NULL or empty WASM return
  plugins/filter_wasm/filter_wasm.c
  src/wasm/flb_wasm.c
Labels: docs-required

#6986 out_prometheus_remote_write: add aws sigv4 authentication
  plugins/out_prometheus_remote_write/remote_write.c
  plugins/out_prometheus_remote_write/remote_write.h
  plugins/out_prometheus_remote_write/remote_write_conf.c
Labels: docs-required

#6939 in_elasticsearch: release buffer on error case
  plugins/in_elasticsearch/in_elasticsearch.c
  plugins/in_elasticsearch/in_elasticsearch_bulk_conn.c
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
Labels: docs-required

#7186 filter: fix implicit util function on filter
  src/flb_filter.c
Labels: docs-required

#7187 workflows: enable macos unit test failures
  .github/workflows/unit-tests.yaml
Labels: ci

#7188 engine: Ensure TLS initialization for evl only once
  src/flb_engine.c
Labels: docs-required, ok-package-test

#7190 engine: Ensure TLS initialization for evl only once [2.0 backport]
  src/flb_engine.c
Labels: docs-required

#6814 out_opensearch: support logstash_prefix_separator
  plugins/out_es/es.c
  plugins/out_es/es.h
  plugins/out_opensearch/opensearch.c
  plugins/out_opensearch/opensearch.h
  tests/runtime/out_elasticsearch.c
  tests/runtime/out_opensearch.c
Labels: docs-required

#7193 packaging: handle systemd service detection
  src/CMakeLists.txt
Labels: packaging, ok-package-test

#7204 bin: config: reload: Enable hot reloading via config file
  include/fluent-bit/flb_config.h
  src/flb_config.c
  src/flb_reload.c
  src/fluent-bit.c
Labels: docs-required

#7210 tls: openssl: add missing return in SSL_ERROR_SYSCALL case
  src/tls/openssl.c
Labels: docs-required

#7211 tls: openssl: add missing return in SSL_ERROR_SYSCALL case
  src/tls/openssl.c
Labels: docs-required

#7202 out_opensearch: remove unused variables
  plugins/out_opensearch/opensearch.c
Labels: docs-required

#7195 in_calyptia_fleet: fixes found when connecting to production.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#7223 ci: 2.1 Windows release not synced
  packaging/update-source-packages.sh
Labels: ci

#5732 in_podman_metrics: Initial plugin implementation
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_podman_metrics/CMakeLists.txt
  plugins/in_podman_metrics/podman_metrics.c
  plugins/in_podman_metrics/podman_metrics.h
  plugins/in_podman_metrics/podman_metrics_config.h
  plugins/in_podman_metrics/podman_metrics_data.c
  plugins/in_podman_metrics/podman_metrics_data.h
  tests/runtime/CMakeLists.txt
  tests/runtime/data/podman/garbage/18446744073709551615/net/dev
  tests/runtime/data/podman/garbage/config.json
  tests/runtime/data/podman/garbage/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/data/podman/garbage/memory/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.usage_in_bytes
  tests/runtime/data/podman/garbage_config/config.json
  tests/runtime/data/podman/no_config/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/data/podman/no_config/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.usage_in_bytes
  tests/runtime/data/podman/no_config/memory/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.usage_in_bytes
  tests/runtime/data/podman/no_proc/config.json
  tests/runtime/data/podman/no_proc/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/data/podman/no_proc/memory/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.usage_in_bytes
  tests/runtime/data/podman/no_sysfs/18446744073709551615/net/dev
  tests/runtime/data/podman/no_sysfs/config.json
  tests/runtime/data/podman/regular/18446744073709551615/net/dev
  tests/runtime/data/podman/regular/config.json
  tests/runtime/data/podman/regular/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/data/podman/regular/memory/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.usage_in_bytes
  tests/runtime/in_podman_metrics.c
Labels: docs-required, ok-package-test

#7238 ci: ensure 2.1 series is pushed as latest container
  .github/workflows/staging-release.yaml
Labels: docs-required

#7196 developer guide: add -DFLB_VALGRIND=on to valgrind section
  DEVELOPER_GUIDE.md
Labels: docs-required

#7249 out_forward: added missing code to drop metadata by default
  plugins/out_forward/forward.c
  plugins/out_forward/forward_format.c
  plugins/out_forward/forward_format.h
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok, docs-required

#7242 in_opentelemetry: fix warning
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#7261 time: fixed printf format string in flb_time_pop_from_mpack
  src/flb_time.c
Labels: docs-required

#7262 time: fixed printf format string in flb_time_pop_from_mpack
  src/flb_time.c
Labels: docs-required

#7267 in_podman_metrics: Fixed unit tests on cgroupsv2
  plugins/in_podman_metrics/podman_metrics.c
  plugins/in_podman_metrics/podman_metrics_config.h
  plugins/in_podman_metrics/podman_metrics_data.c
  plugins/in_podman_metrics/podman_metrics_data.h
  tests/runtime/data/podman/cgroupv2/18446744073709551615/net/dev
  tests/runtime/data/podman/cgroupv2/cgroup.controllers
  tests/runtime/data/podman/cgroupv2/config.json
  tests/runtime/data/podman/cgroupv2/memory/libpod-8a19d6058bfbe88cd0548eba9047d94c70161f5d74b545c7504b2f27491686d9/memory.current
  tests/runtime/in_podman_metrics.c
Labels: docs-required

#7256 macos: test: out_exit: Plug invalid evl context case
  tests/runtime/out_exit.c
Labels: docs-required

#7260 lib: cfl: upgrade to v0.2.3
  lib/cfl/src/cfl_sds.c
Labels: docs-required

#7254 sp: CMakeLists.txt: don't require c++
  src/stream_processor/CMakeLists.txt
Labels: docs-required

#7275 packaging: handle multiple AppVeyor builds for downloading
  packaging/appveyor-download.sh
Labels: ci

#7277 workflows: updates for automated PR creation
  .github/workflows/staging-release.yaml
  CMakeLists.txt
  dockerfiles/Dockerfile
  fluent-bit-2.1.3.bb
  snap/snapcraft.yaml
  update_version.sh
Labels: ci

#7278 workflows: doc generation updates
  .github/workflows/staging-release.yaml
Labels: docs-required

#7280 workflows: ensure we increment the version for the new PR
  .github/workflows/staging-release.yaml
Labels: docs-required

#7288 workflows: reduce PR noise
  .github/workflows/pr-package-tests.yaml
Labels: ci, ok-package-test
