Repository fluent/fluent-bit, pull requests merged in 2024-11, with the labels that each got.

#9550 in_forward: fixed incorrect shared key length in authentication
  plugins/in_forward/fw_prot.c
Labels: docs-required

#9551 in_forward: fixed incorrect shared key length in authentication
  plugins/in_forward/fw_prot.c
Labels: docs-required

#9552 in_forward: fixed incorrect shared key length in authentication
  plugins/in_forward/fw_prot.c
Labels: docs-required

#9521 filter_multiline: Add functionality to use as processor
  plugins/filter_multiline/ml.c
Labels: docs-required

#9554 output: allow records size 0 on flb event type logs processor
  include/fluent-bit/flb_output.h
Labels: docs-required

#9561 in_calyptia_fleet: fleet id search by name must use exact name.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9515 in_calyptia_fleet: make the http client buffer size configurable.
  plugins/custom_calyptia/calyptia.c
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9516 in_calyptia_fleet: fix registering agent after first invocation.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9441 out_datadog: custom added ability ot set custom HTTP headers
  plugins/out_datadog/datadog.c
  plugins/out_datadog/datadog.h
Labels: docs-required

#9341 metrics_exporter: add support for filter metrics inside processors
  src/flb_metrics_exporter.c
  src/flb_processor.c
Labels: docs-required

#9574 network: use TCP_KEEPALIVE instead of TCP_KEEPIDLE in OSX
  src/flb_network.c
Labels: docs-required

#9576 in_ebpf: initial version of the plugin (experimental)
  .github/workflows/unit-tests.yaml
  .gitignore
  CMakeLists.txt
  cmake/plugins_options.cmake
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_ebpf/CMakeLists.txt
  plugins/in_ebpf/in_ebpf.c
  plugins/in_ebpf/in_ebpf.h
  plugins/in_ebpf/traces/bind/bpf.c
  plugins/in_ebpf/traces/bind/handler.c
  plugins/in_ebpf/traces/bind/handler.h
  plugins/in_ebpf/traces/includes/common/encoder.h
  plugins/in_ebpf/traces/includes/common/event_context.h
  plugins/in_ebpf/traces/includes/common/events.h
  plugins/in_ebpf/traces/includes/external/gadget/amd64/vmlinux.h
  plugins/in_ebpf/traces/includes/external/gadget/arm64/vmlinux.h
  plugins/in_ebpf/traces/includes/external/gadget/bits.bpf.h
  plugins/in_ebpf/traces/includes/external/gadget/buffer.h
  plugins/in_ebpf/traces/includes/external/gadget/core_fixes.bpf.h
  plugins/in_ebpf/traces/includes/external/gadget/filesystem.h
  plugins/in_ebpf/traces/includes/external/gadget/kernel_stack_map.h
  plugins/in_ebpf/traces/includes/external/gadget/macros.h
  plugins/in_ebpf/traces/includes/external/gadget/maps.bpf.h
  plugins/in_ebpf/traces/includes/external/gadget/mntns.h
  plugins/in_ebpf/traces/includes/external/gadget/mntns_filter.h
  plugins/in_ebpf/traces/includes/external/gadget/sockets-map.h
  plugins/in_ebpf/traces/includes/external/gadget/types.h
  plugins/in_ebpf/traces/includes/generated/trace_bind.skel.h
  plugins/in_ebpf/traces/includes/generated/trace_malloc.skel.h
  plugins/in_ebpf/traces/includes/generated/trace_signal.skel.h
  plugins/in_ebpf/traces/malloc/bpf.c
  plugins/in_ebpf/traces/malloc/handler.c
  plugins/in_ebpf/traces/malloc/handler.h
  plugins/in_ebpf/traces/signal/bpf.c
  plugins/in_ebpf/traces/signal/handler.c
  plugins/in_ebpf/traces/signal/handler.h
  plugins/in_ebpf/traces/traces.h
  tests/runtime/CMakeLists.txt
  tests/runtime/in_ebpf_bind_handler.c
  tests/runtime/in_ebpf_malloc_handler.c
  tests/runtime/in_ebpf_signal_handler.c
Labels: docs-required

#9586 lib: cprofiles: fixed incorrect check
  lib/cprofiles/src/cprof_encode_text.c
Labels: docs-required

#2783 Retrieve Kubernetes pod IP address if it is set in status.podIP
  plugins/filter_kubernetes/kube_meta.c
  tests/runtime/data/kubernetes/out/core/core_base_fluent-bit.out
  tests/runtime/data/kubernetes/out/kairosdb-914055854-b63vq.out
Labels: docs-required

#9592 in_ebpf: Prepare build directory for building eBPF objects
  plugins/in_ebpf/CMakeLists.txt
Labels: docs-required

#9518 in_splunk: splunk token validation must be case-insensitive
  plugins/in_splunk/splunk_prot.c
Labels: docs-required

#9519 in_splunk: splunk token validation must be case-insensitive. Backport of #9518
  plugins/in_splunk/splunk_prot.c
Labels: docs-required

#9596 in_ebpf: Handle debian like systems' signal probes
  plugins/in_ebpf/CMakeLists.txt
  plugins/in_ebpf/traces/includes/generated/trace_bind.skel.h
  plugins/in_ebpf/traces/includes/generated/trace_malloc.skel.h
  plugins/in_ebpf/traces/includes/generated/trace_signal.skel.h
  plugins/in_ebpf/traces/malloc/bpf.c.in
Labels: docs-required

#9594 security: supported versions now are 3.1.x and 3.2.x
  SECURITY.md
Labels: docs-required

#9599 tls: removed alpn selector requirement
  src/tls/openssl.c
Labels: ok-to-test, docs-required

#9606 signv4: added missing length calculation (CID 514601)
  src/flb_signv4_ng.c
Labels: docs-required

#9607 http_client: added missing exit path (CID 514596, 514571)
  src/flb_http_client.c
Labels: docs-required

#9608 http_common: added missing initializers (CID 514594, 514583)
  src/flb_http_common.c
Labels: docs-required

#9609 out_opentelemetry: added missing result checks and fixed leaks (CID 514593)
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#9611 http_client: fixed potential memory corruption (CID 514587)
  src/flb_http_client_http1.c
Labels: docs-required

#9612 http_client: added missing exit path (CID 514585)
  src/flb_http_client_http1.c
Labels: docs-required

#9630 ci: extended CI script to pass test for flb_utils_get_machine_id
  run_code_analysis.sh
Labels: docs-required

#9618 node_exporter_metrics: Use real_path for complaining on glob error
  plugins/in_node_exporter_metrics/ne_utils.c
Labels: docs-required

#9635 in_opentelemetry: Propogate tag in http2 metrics and trace handlers
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#9617 filter_lua: expose env variables in FLB_ENV Lua table
  plugins/filter_lua/lua.c
Labels: docs-required

#9404 network: fix IPV6 handling for accepting connections
  src/flb_network.c
Labels: docs-required

#9656 out_calyptia: retry agent registration on flush callback
  plugins/custom_calyptia/calyptia.c
  plugins/custom_calyptia/calyptia.h
  plugins/out_calyptia/calyptia.c
  plugins/out_calyptia/calyptia.h
  tests/runtime/CMakeLists.txt
  tests/runtime/custom_calyptia_registration_retry_test.c
Labels: ok-package-test
