Repository fluent/fluent-bit, pull requests merged in 2024-06, with the labels that each got.

#8883 in_splunk: Store HEC token on enabled HTTP2 and raw endpoints
  plugins/in_splunk/splunk_prot.c
Labels: docs-required

#8887 in_kubernetes_events: refactor time check to use struct flb_time.
  plugins/in_kubernetes_events/kubernetes_events.c
Labels: docs-required

#8917 in_systemd: Move one record back after skipping to the end
  plugins/in_systemd/systemd_config.c
Labels: docs-required

#8886 http_server: api: v1: traces: fix finding inputs by alias.
  src/http_server/api/v1/trace.c
Labels: docs-required

#8771 in_winevtlog: Fix threshold condition to avoid unnecessary warning
  plugins/in_winevtlog/in_winevtlog.c
Labels: docs-required

#8916 dockerfile: update to bookworm base image
  dockerfiles/Dockerfile
Labels: ok-to-test, ci/integration-docker-ok

#8922 lib: cmetrics: upgrade to v0.9.1
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_cat.h
  lib/cmetrics/include/cmetrics/cmt_filter.h
  lib/cmetrics/include/cmetrics/cmt_map.h
  lib/cmetrics/src/cmt_cat.c
  lib/cmetrics/src/cmt_filter.c
  lib/cmetrics/src/cmt_map.c
  lib/cmetrics/tests/filter.c
Labels: docs-required

#8924 dockerfiles: windows: Update to use vcpkg instead of chocolatey
  dockerfiles/Dockerfile.windows
Labels: docs-required

#8933 out_opentelemetry: fix handling of multiple scopes
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#8934 tls: Verify vhost when tls.verify is enabled
  src/tls/openssl.c
Labels: docs-required

#8948 workflows: remove AppVeyor from release workflow
  .github/workflows/staging-release.yaml
Labels: ci

#8945 lib: monkey: upgrade to v1.7.5
  lib/monkey/examples/list.c
  lib/monkey/examples/quiz.c
  lib/monkey/include/monkey/mk_api.h
  lib/monkey/include/monkey/monkey.h
  lib/monkey/monkey.spec
  lib/monkey/qa/checklog
Labels: docs-required

#8881 in_opentelemetry: attempt to fix tag_from_uri
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#8952 help: input: Handle listen to be a parameter for setting up listen address
  src/flb_help.c
Labels: docs-required

#8992 in_winevtlog: Retrieve actual user account's domain and name
  plugins/in_winevtlog/pack.c
Labels: docs-required, backport to v3.0.x

#8974 in_winevtlog: Permit absence of publisher metadata
  plugins/in_winevtlog/winevtlog.c
Labels: docs-required

#8989 processor_content_modifier: add support for OTel Logs Resource and Scopes
  plugins/processor_content_modifier/cm.c
  plugins/processor_content_modifier/cm.h
  plugins/processor_content_modifier/cm_config.c
  plugins/processor_content_modifier/cm_logs.c
Labels: docs-required

#8994 in_docker: fix memory leak caused by conversion error
  plugins/in_docker/cgroup_v2.c
Labels: docs-required

#8995 in_winevtlog: Retrieve actual user account's domain and name [Backport to 3.0]
  plugins/in_winevtlog/pack.c
Labels: docs-required

#8986 in_opentelemetry: handle missing or invalid content-type headers in metrics and traces handlers
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: backport to v3.0.x

#8814 out_loki: allow sending unquoted strings
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
  tests/runtime/out_loki.c
Labels: docs-required

#9005 processor_content_modifier: logs: do not fail if keys are not found
  plugins/processor_content_modifier/cm_logs.c
Labels: docs-required

#8988 out_datadog: Add support for setting a static hostname
  plugins/out_datadog/datadog.c
  plugins/out_datadog/datadog.h
Labels: docs-required

#8962 Improved OpenTelemetry OTLP error handling
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#8767 utils: floating-point number support in size-to-bytes conversion
  src/flb_utils.c
  tests/internal/utils.c
Labels: docs-required

#8778 Added parser for Linux kernel netfilter firewall log
  conf/parsers.conf
Labels: docs-required

#9008 workflows: update for 3.1 release
  .github/workflows/staging-release.yaml
Labels: docs-required

#8969 metrics: Allocate metrics' titles dynamically
  include/fluent-bit/flb_metrics.h
  src/flb_metrics.c
Labels: docs-required

#9011 in_winetvlog: Handle buffer allocation error and not mapped error
  plugins/in_winevtlog/pack.c
  plugins/in_winevtlog/winevtlog.c
Labels: docs-required
