Repository fluent/fluent-bit, pull requests merged in 2024-08, with the labels that each got.

#9157 workflows: Fix CentOS7 build failure for EPEL
  dockerfiles/Dockerfile.centos7
  packaging/distros/centos/Dockerfile
Labels: docs-required, ok-package-test

#9150 filter_log_to_metrics: add new option 'discard_logs'
  plugins/filter_log_to_metrics/log_to_metrics.c
  plugins/filter_log_to_metrics/log_to_metrics.h
Labels: docs-required

#9134 node_exporter_metrics: Align the collecting metrics of unit statuses
  plugins/in_node_exporter_metrics/ne_systemd_linux.c
Labels: docs-required

#7966 out_oracle_log_analytics: minor fixes
  plugins/out_oracle_log_analytics/oci_logan_conf.c
Labels: docs-required

#9168 workflows: update unstable nightly builds for 3.0
  .github/workflows/cron-unstable-build.yaml
Labels: docs-required

#9163 in_mqtt: added buffer size setting and fixed a leak
  plugins/in_mqtt/mqtt.c
  plugins/in_mqtt/mqtt.h
  plugins/in_mqtt/mqtt_conn.c
  plugins/in_mqtt/mqtt_conn.h
  plugins/in_mqtt/mqtt_prot.c
Labels: docs-required

#9128 aws_util: fix leading zeros in time_key strings
  src/aws/flb_aws_util.c
Labels: docs-required

#9158 out_opensearch: fixed wrong payload buffer usage for traces
  plugins/out_opensearch/opensearch.c
Labels: ok-to-test, docs-required

#9122 out_prometheus_exporter: Handle multiply concatenated metrics type of events
  plugins/out_prometheus_exporter/prom.c
Labels: docs-required

#9195 filter_parser: added debug message (CID 508252)
  plugins/filter_parser/filter_parser.c
Labels: docs-required

#9193 pack: do not multiply out_size by realloc_size
  src/flb_pack.c
Labels: docs-required

#9182 stackdriver: Add latency metric for write log entries HTTP request.
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#9199 in_forward: fixed two leaks
  plugins/in_forward/fw_prot.c
Labels: docs-required

#9211 in_kubernetes_events: Use time_t for time(NULL) returned value (CID 507947)
  plugins/in_kubernetes_events/kubernetes_events.h
Labels: docs-required

#9208 in_exec_wasi: Fix resource leak on exception (CID 508347)
  plugins/in_exec_wasi/in_exec_wasi.c
Labels: docs-required

#9209 in_forward: Plug a resource leak (CID 508219)
  plugins/in_forward/fw_conn.c
Labels: docs-required

#9190 in_http: Content-Type rejected for application/json when encoding value is present.
  plugins/in_http/http_prot.c
  tests/runtime/in_http.c
Labels: docs-required

#9219 tests: in_http: replaced the failure trigger mechanism
  tests/runtime/in_http.c
Labels: docs-required

#9220 filter_aws: fixed group metadata fetch issue and addressed (CID 507941)
  plugins/filter_aws/aws.c
Labels: docs-required

#9221 out_opensearch: fixed a wrong data type used for a boolean option
  plugins/out_opensearch/opensearch.h
Labels: docs-required

#9222 out_stackdriver: fixed a wrong data type used for two boolean options
  plugins/out_stackdriver/stackdriver.h
Labels: docs-required

#9224 filter_tensorflow: fixed a wrong data type used for a boolean option
  plugins/filter_tensorflow/tensorflow.h
Labels: docs-required

#9225 in_nginx_exporter_metrics: fixed a wrong data type used for an option
  plugins/in_nginx_exporter_metrics/nginx.h
Labels: docs-required

#9227 in_proc: fixed a wrong data type used for three options
  plugins/in_proc/in_proc.h
Labels: docs-required

#9228 out_es: fixed a wrong data type used for an option
  plugins/out_es/es.h
Labels: docs-required

#9229 network: fixed a wrong data type used for an option
  include/fluent-bit/flb_network.h
Labels: docs-required

#9210 in_elasticsearch: Store log_encoder pointer (CID 508245)
  plugins/in_elasticsearch/in_elasticsearch.h
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
  plugins/in_elasticsearch/in_elasticsearch_config.c
Labels: docs-required

#9233 out_opensearch: Plug a use-after-free issue (CID 508013)
  plugins/out_opensearch/opensearch.c
Labels: docs-required

#9235 in_event_type: Plug a resource leak on exception (CID 507968)
  plugins/in_event_type/event_type.c
Labels: docs-required

#9234 out_chronicle: Plug a resource leak on exception (CID 508008)
  plugins/out_chronicle/chronicle.c
Labels: docs-required

#8904 core: fix configuration type cast issue on big endian systems
  src/flb_config_map.c
  tests/internal/config_map.c
Labels: ok-to-test, docs-required

#9250 in_emitter: Plug a possible resource leak on exception (CID 508193)
  plugins/in_emitter/emitter.c
Labels: docs-required

#9252 filter_logs_to_metrics: fixed memory corruption issue
  plugins/filter_log_to_metrics/log_to_metrics.c
  plugins/filter_log_to_metrics/log_to_metrics.h
Labels: docs-required

#9255 upstream_ha: added environment variable support
  src/flb_upstream_ha.c
Labels: ok-to-test, docs-required

#9253 core: fixed the data type used for booleans
  include/fluent-bit/flb_config_map.h
Labels: docs-required

#9212 in_winevtlog: Skip to translate SID for capability SIDs
  plugins/in_winevtlog/pack.c
Labels: docs-required

#9266 in_process_exporter_metrics: Initialize with NULL for flb_sds_t pointer variables (CID 507975)
  plugins/in_process_exporter_metrics/pe_process.c
Labels: docs-required

#9280 output: Remove a needless calling of flb_output_instance_destroy() (CID 507809)
  src/flb_output.c
Labels: docs-required

#8051 out_logdna: refactored LogDNA URI formation to support configurable endpoints
  plugins/out_logdna/logdna.c
  plugins/out_logdna/logdna.h
Labels: docs-required

#9172 build: use the system provided LuaJIT on s390x
  README.md
  cmake/s390x.cmake
Labels: docs-required

#9196 engine:enhanced byte order handling for timestamps
  include/fluent-bit/flb_byteswap.h
  src/flb_log_event_decoder.c
  src/flb_log_event_encoder_primitives.c
Labels: docs-required

#9271 in_splunk: test: Handle 1.0 suffixed endpoints
  plugins/in_splunk/splunk_prot.c
  tests/runtime/in_splunk.c
Labels: docs-required

#9236 out_elasticsearch: Process error information properly
  plugins/out_es/es.c
  plugins/out_es/es.h
Labels: docs-required

#9296 out_azure_blob: fixed double free (CID 508656)
  plugins/out_azure_blob/azure_blob_http.c
Labels: docs-required

#9298 in_collectd: fixed out of bounds read
  plugins/in_collectd/netprot.c
Labels: docs-required

#9299 out_stackdriver: fixed a memory leak (CID 508244)
  plugins/out_stackdriver/stackdriver.c
Labels: docs-required

#9300 in_node_exporter_metrics: fixed possible invalid dereference (CID 508238)
  plugins/in_node_exporter_metrics/ne_meminfo_linux.c
Labels: docs-required

#9295 in_podman_metrics: Plug a resource leak on exception (CID 507805)
  plugins/in_podman_metrics/podman_metrics_data.c
Labels: docs-required

#9292 reload: added appropriate type cast (CID 508209)
  src/flb_reload.c
Labels: docs-required
