Repository fluent/fluent-bit, pull requests merged in 2024-03, with the labels that each got.

#8279 filter_kubernetes: add kubernetes_namespace metadata
  plugins/filter_kubernetes/kube_conf.c
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kube_meta.c
  plugins/filter_kubernetes/kube_meta.h
  plugins/filter_kubernetes/kubernetes.c
  tests/runtime/data/kubernetes/log/core/core_base-with-namespace-labels-and-annotations_fluent-bit.log
  tests/runtime/data/kubernetes/meta/core.namespace_meta
  tests/runtime/data/kubernetes/meta/core_base-with-namespace-labels-and-annotations.meta
  tests/runtime/data/kubernetes/out/core/core_base-with-namespace-labels-and-annotations_fluent-bit.out
  tests/runtime/filter_kubernetes.c
Labels: ok-to-test, ci/integration-docker-ok, ci/integration-test-ok, docs-required

#7667 Adds support for Content-Encoding: gzip to in_http
  include/fluent-bit/flb_gzip.h
  plugins/in_http/http_prot.c
  src/flb_gzip.c
Labels: docs-required

#8415 workflows: make 3.0 releases latest
  .github/workflows/staging-release.yaml
Labels: ci

#8493 out_http: default the output format to JSON.
  plugins/out_http/http.c
  plugins/out_http/http.h
  plugins/out_http/http_conf.c
  tests/runtime/out_http.c
Labels: docs-required

#8572 processor_content_modifier: fix cb_processor_logs callback arguments type
  plugins/processor_content_modifier/cm.c
Labels: docs-required

#8545 in_tail: flush multiline before exit on EOF
  plugins/in_tail/tail.c
Labels: docs-required

#8561 in_forward: Implement handshake protocol
  plugins/in_forward/fw.c
  plugins/in_forward/fw.h
  plugins/in_forward/fw_config.c
  plugins/in_forward/fw_conn.c
  plugins/in_forward/fw_conn.h
  plugins/in_forward/fw_prot.c
  plugins/in_forward/fw_prot.h
Labels: docs-required

#8526 processor: Implement native processor metrics_selector
  CMakeLists.txt
  include/fluent-bit/flb_lib.h
  include/fluent-bit/flb_metrics.h
  include/fluent-bit/flb_processor.h
  plugins/CMakeLists.txt
  plugins/processor_labels/labels.c
  plugins/processor_metrics_selector/CMakeLists.txt
  plugins/processor_metrics_selector/selector.c
  plugins/processor_metrics_selector/selector.h
  src/flb_input_metric.c
  src/flb_lib.c
  src/flb_processor.c
  tests/runtime/CMakeLists.txt
  tests/runtime/processor_metrics_selector.c
Labels: docs-required

#8544 in_winevtlog: Display error on invalid subscription state
  plugins/in_winevtlog/winevtlog.c
Labels: docs-required

#8573 in_http: Adds support for Content-Encoding: gzip [Backport to 2.2]
  include/fluent-bit/flb_gzip.h
  plugins/in_http/http_prot.c
  src/flb_gzip.c
Labels: docs-required

#8543 custom_calyptia: fix using after freed memory(#8530)
  plugins/custom_calyptia/calyptia.c
Labels: docs-required

#8589 pack: increase buffer reallocation for higher performance (fix #8492)
  src/flb_pack.c
Labels: docs-required

#8590 in_elasticsearch: include file to fix warnings
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.h
Labels: docs-required

#8454 filter_nest: define a new var to prevent pointer arithmetic
  plugins/filter_nest/nest.c
Labels: ok-to-test, ci/integration-docker-ok, docs-required, ok-package-test

#8594 processor_sql: Ensure jemalloc compiling before starting to build sql parser
  plugins/processor_sql/parser/CMakeLists.txt
Labels: docs-required

#8609 processor_sql: Remove a needless yywrap definition
  plugins/processor_sql/parser/sql-parser.y
Labels: docs-required, ok-package-test

#8605 http_server: removed deprecated code and added window update handling
  src/http_server/flb_http_server_http2.c
Labels: docs-required

#8612 packaging: build: Make to be able to replace docker cli via environment variable
  packaging/build.sh
Labels: docs-required

#8613 lib: nghttp2: Disable auto-detection for OpenSSL
  lib/nghttp2/CMakeLists.txt
Labels: docs-required, ok-package-test

#8582 workflows: windows: Add chain workflow for windows unit testing
  .github/workflows/call-windows-unit-tests.yaml
  .github/workflows/pr-windows-build.yaml
  tests/internal/file.c
Labels: docs-required

#8649 http_server: added parser reset code to prevent use after free
  src/http_server/flb_http_server_http1.c
Labels: docs-required

#8652 lib: cmetrics: upgrade to v0.7.1
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_encode_prometheus_remote_write.h
Labels: docs-required
