Repository fluent/fluent-bit, pull requests merged in 2024-09, with the labels that each got.

#9311 in_event_type: fixed two leaks (CID 508227)
  plugins/in_event_type/event_type.c
Labels: docs-required

#9310 core: fixed memory leaks (CID 508230)
  src/fluent-bit.c
Labels: docs-required

#9306 record_accessor: Plug a resource leak on exception (CID 508119)
  src/flb_record_accessor.c
Labels: docs-required

#9307 out_opentelemetry: Prevent null dereference on memcpy (CID 507910)
  plugins/out_opentelemetry/opentelemetry_utils.c
Labels: docs-required

#9314 filter_multiline: fixed memory leak (CID 508221)
  plugins/filter_multiline/ml.c
Labels: docs-required

#9315 sp: changed property type to prevent lossy cast (CID 508218)
  include/fluent-bit/stream_processor/flb_sp.h
Labels: docs-required

#9319 lib: cmetrics: upgrade to v0.9.5
  lib/cmetrics/.github/workflows/packages.yaml
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_prometheus.c
  lib/cmetrics/src/cmt_decode_prometheus_remote_write.c
  lib/cmetrics/src/cmt_decode_statsd.c
  lib/cmetrics/src/cmt_encode_influx.c
  lib/cmetrics/src/cmt_encode_opentelemetry.c
  lib/cmetrics/tests/data/issue_fluent_bit_9267.txt
  lib/cmetrics/tests/encoding.c
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#9316 filter_alter_size: fixed memory leak (CID 508216)
  plugins/filter_alter_size/alter_size.c
Labels: docs-required

#9322 build: bump to v3.2 series
  CMakeLists.txt
Labels: docs-required

#9313 workflows: linux: Compile and execute internal test on non-amd64 platforms Linux
  .github/workflows/unit-tests.yaml
Labels: docs-required

#9329 engine: added missing explicit cast (CID 508212)
  src/flb_engine.c
Labels: docs-required

#9330 engine: added missing explicit cast (CID 508212)
  src/flb_engine.c
Labels: docs-required

#9345 tests: internal: signv4: fixed leak (CID 508222)
  tests/internal/signv4.c
Labels: docs-required

#9349 tests: internal: signv4: uncommented code that caused a leak (CID 508181)
  tests/internal/signv4.c
Labels: docs-required

#9356 in_elasticsearch: fixed potential issue caused by ingored reallocation (CID 508180)
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
Labels: docs-required

#9357 in_elasticsearch: fixed potential issue caused by ingored reallocation (CID 508180)
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
Labels: docs-required

#9331 input: added missing initializer (CID 508207)
  include/fluent-bit/flb_input.h
Labels: docs-required

#9334 out_opentelemetry: fixed memory leaks (CID 508192)
  plugins/out_opentelemetry/opentelemetry.c
  plugins/out_opentelemetry/opentelemetry.h
  plugins/out_opentelemetry/opentelemetry_conf.c
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#9348 tests: internal: signv4: uncommented code that caused a leak (CID 508181)
  tests/internal/signv4.c
Labels: docs-required

#9358 in_elasticsearch: fixed memory leak (CID 507822)
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
Labels: docs-required

#9359 in_elasticsearch: fixed memory leak (CID 507822)
  plugins/in_elasticsearch/in_elasticsearch_bulk_prot.c
Labels: docs-required

#9335 out_opentelemetry: fixed memory leaks (CID 508192)
  plugins/out_opentelemetry/opentelemetry.c
  plugins/out_opentelemetry/opentelemetry.h
  plugins/out_opentelemetry/opentelemetry_conf.c
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#9346 in_calyptia_fleet: fixed memory leaks (CID 508187)
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9347 in_calyptia_fleet: fixed memory leaks (CID 508187)
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9377 out_http: Request timed out(408) to be treated as retry
  plugins/out_http/http.c
Labels: docs-required

#9380 out_splunk: Extend retrying HTTP status code [Backport 3.1]
  plugins/out_splunk/splunk.c
Labels: docs-required

#9379 out_http: Request timed out(408) to be treated as retry [Backport 3.1]
  plugins/out_http/http.c
Labels: docs-required

#9361 out_influxdb: Handle signed/unsigned integer as influx's integer of that representation [Backport 3.1]
  plugins/out_influxdb/influxdb.c
  plugins/out_influxdb/influxdb.h
  tests/runtime/CMakeLists.txt
  tests/runtime/out_influxdb.c
Labels: docs-required

#9344 tests: internal: signv4: fixed leak (CID 508222)
  tests/internal/signv4.c
Labels: docs-required

#9338 input: disable coroutines for custom events and input callbacks that do not support coroutines.
  src/flb_io.c
  src/tls/flb_tls.c
Labels: docs-required

#9251 filter_log_to_metrics: Add timer callback for emitting metrics
  plugins/filter_log_to_metrics/log_to_metrics.c
  plugins/filter_log_to_metrics/log_to_metrics.h
Labels: docs-required

#9392 lib: cmetrics: upgrade to v0.9.6
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_math.h
  lib/cmetrics/src/cmt_cat.c
  lib/cmetrics/tests/cat.c
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#9375 out_splunk: Extend retrying HTTP status code
  plugins/out_splunk/splunk.c
Labels: docs-required

#9393 3.1: lib: upgrade cmetrics to v0.9.6
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/include/cmetrics/cmt_math.h
  lib/cmetrics/src/cmt_cat.c
  lib/cmetrics/tests/cat.c
  lib/cmetrics/tests/prometheus_parser.c
Labels: docs-required

#9415 backport: resolve build failures for CentOS 7 and Windows on 3.0
  dockerfiles/Dockerfile.centos7
  packaging/distros/centos/Dockerfile
  plugins/in_winevtlog/pack.c
  plugins/out_s3/s3.c
Labels: docs-required, ok-package-test

#9421 workflows: Update scorecard workflow and remove Dockerfile warnings
  .github/workflows/cron-scorecards-analysis.yaml
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile.windows
Labels: ci

#8466 out_calyptia: register OS and architecture for agents.
  plugins/out_calyptia/calyptia.c
Labels: ok-package-test, backport to v3.1.x

#9430 lib: ctraces: upgrade to v0.5.6
  lib/ctraces/CMakeLists.txt
  lib/ctraces/src/ctr_encode_opentelemetry.c
  lib/ctraces/tests/decoding.c
Labels: backport to v3.1.x

#6842 upstream_conn: fix ordering of mk_event_inject and prepare_conn_destroy
  src/flb_upstream.c
Labels: backport to v3.1.x

#9410 in_calyptia_fleet: fix 'unable to find fleet by name'.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9411 in_calyptia_fleet: fix 'unable to find fleet by name'.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9412 in_calyptia_fleet: fix 'unable to find fleet by name'.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9425 filter_multiline: Reset group metadata buf on flush - Fixes 9262,8925,9337,8567
  src/multiline/flb_ml.c
Labels: backport to v3.1.x

#9432 reload: do not call flb_stop when flb_start fails to avoid crash on RHEL/CentOS.
  src/flb_reload.c
Labels: docs-required

#9435 reload: do not call flb_stop when flb_start fails and fix crash on RHEL
  src/flb_reload.c
Labels: docs-required

#9444 workflows: update for 3.1 branch
  .github/workflows/staging-release.yaml
Labels: ci

#9442 motd: v3.2
  include/fluent-bit/flb_motd.h
Labels: docs-required

#8963 in_opentelemetry: add tag_from_uri support to http2 codepath
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: backport to v3.1.x
