Repository fluent/fluent-bit, pull requests merged in 2024-10, with the labels that each got.

#9447 in_opentelemetry: add tag_from_uri support to http2 codepath
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#9467 in_http: fix parsing of root JSON object
  plugins/in_http/http_prot.c
Labels: docs-required

#9474 motd: add missing null character
  include/fluent-bit/flb_motd.h
Labels: docs-required

#9480 http_server: http1: always reset the parser context on pending status
  src/http_server/flb_http_server_http1.c
Labels: docs-required

#9493 out_azure_blob: fixed blob endpoint tracking
  plugins/out_azure_blob/azure_blob.c
  plugins/out_azure_blob/azure_blob_db.c
Labels: docs-required

#9527 tls: include X509 error string when verify result is not x509_V_OK.
  src/tls/openssl.c
Labels: docs-required

#9533 tls: improve debug information on the cause of the failure when loading system certificates on windows
  src/tls/openssl.c
Labels: docs-required

#9522 docs: DEVELOPER_GUIDE: add instructions for windows 2022.
  DEVELOPER_GUIDE.md
Labels: docs-required

#9487 input_chunk: fix input plugin metrics not counting records re-emitted by filters downstream
  src/flb_input_chunk.c
Labels: ok-package-test, backport to v3.1.x

#9540 lib: fluent-otel-proto: update files for latest profiles support
  lib/fluent-otel-proto/CMakeLists.txt
  lib/fluent-otel-proto/proto_c/opentelemetry/proto/metrics/v1/metrics.pb-c.h
  lib/fluent-otel-proto/proto_c/opentelemetry/proto/profiles/v1development/pprofextended.pb-c.c
  lib/fluent-otel-proto/proto_c/opentelemetry/proto/profiles/v1development/pprofextended.pb-c.h
  lib/fluent-otel-proto/proto_c/opentelemetry/proto/profiles/v1development/profiles.pb-c.c
  lib/fluent-otel-proto/proto_c/opentelemetry/proto/profiles/v1development/profiles.pb-c.h
  lib/fluent-otel-proto/src/CMakeLists.txt
Labels: docs-required

#9539 tls: macos load system certificates using security framework.
  src/CMakeLists.txt
  src/tls/openssl.c
Labels: docs-required, ok-package-test

#9457 out_blob: consider auto_create_container
  plugins/out_azure_blob/azure_blob.c
Labels: docs-required
