Repository fluent/fluent-bit, pull requests merged in 2024-07, with the labels that each got.

#9007 out_splunk: remove raw endpoint
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk.h
Labels: docs-required

#9039 tls: openssl: fix handling of noisy non TLS errors
  src/tls/openssl.c
Labels: docs-required

#9052 lib: nghttp2: backport upstream security fix
  lib/nghttp2/lib/includes/nghttp2/nghttp2.h
  lib/nghttp2/lib/nghttp2_helper.c
  lib/nghttp2/lib/nghttp2_session.c
  lib/nghttp2/lib/nghttp2_session.h
Labels: docs-required

#9031 out_gelf: test: Implement injecting tag capability
  plugins/out_gelf/gelf.c
  plugins/out_gelf/gelf.h
  tests/internal/gelf.c
Labels: docs-required

#9048 out_loki: add support for structured metadata
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: docs-required

#9056 http_server: Don't override keepalive for HTTP/2
  src/http_server/flb_http_server.c
Labels: docs-required

#8874 config_format: yaml: Support passing arbitrary objects to processors
  include/fluent-bit/flb_config_map.h
  include/fluent-bit/flb_processor.h
  src/config_format/flb_cf_yaml.c
  src/flb_config_map.c
  src/flb_processor.c
Labels: docs-required

#8976 in_syslog: Fix double free when no parser is set
  plugins/in_syslog/syslog_conf.c
Labels: docs-required

#8861 out_http: don't retry non retryable 4xx status codes
  plugins/out_http/http.c
Labels: docs-required

#6087 build: Set security flags for release builds
  CMakeLists.txt
Labels: packaging, ok-package-test

#8830 out_loki: Add http_buffer_max_size option and handle HTTP 5xx errors
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
Labels: docs-required

#9059 motd: v3.1
  include/fluent-bit/flb_motd.h
Labels: docs-required

#9065 luajit-cmake: Add git repository existence check
  lib/luajit-cmake/LuaJIT.cmake
Labels: docs-required, ok-package-test

#9066 cmake: build: Revive missing plugin definitions
  cmake/plugins_options.cmake
Labels: docs-required, ok-package-test

#9076 packaing: test: centos7: Fix packaging test
  packaging/centos7-repo.sh
  packaging/test-release-packages.sh
Labels: docs-required

#9078 docs: add user logos
  documentation/fluentbit_users.png
Labels: docs-required

#9070 cmake: Correctly fetch FLB_GIT_HASH from signed commit
  CMakeLists.txt
Labels: docs-required

#9074 out_opentelemetry: restore manual parsing for log record fields (fix #9071)
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#8422 in_tail: Add option file_cache_advise to reduce file cache usage
  plugins/in_tail/tail.c
  plugins/in_tail/tail_config.h
  plugins/in_tail/tail_file.c
Labels: docs-required

#8720 flb_input: Config parsing order fixed for storage.pause_on_chunks_overlimit
  src/flb_input.c
Labels: docs-required

#8829 in_forward: Add plugin pause/resume mechanism
  plugins/in_forward/fw.c
  plugins/in_forward/fw.h
Labels: docs-required

#9085 out_datadog: fix default message key remapping
  plugins/out_datadog/datadog.c
  plugins/out_datadog/datadog.h
Labels: docs-required

#9081 in_winevtlog: Retrieve messages of forwarded events correctly
  plugins/in_winevtlog/winevtlog.c
Labels: docs-required

#9090 lib: ctraces: upgrade to v0.5.2
  lib/ctraces/CMakeLists.txt
  lib/ctraces/include/ctraces/ctr_variant_utils.h
Labels: docs-required, ok-package-test

#9095 in_splunk: Fix handlings for content type when http2 is off
  plugins/in_splunk/splunk_prot.c
Labels: docs-required

#9118 out_stdout: Consume entire metrics type of buffers
  plugins/out_stdout/stdout.c
Labels: docs-required

#9101 log_to_metrics: allow custom namespace and subsystem
  plugins/filter_log_to_metrics/log_to_metrics.c
  plugins/filter_log_to_metrics/log_to_metrics.h
  tests/runtime/filter_log_to_metrics.c
Labels: docs-required

#9127 input_chunk: do not exit if cannot release old chunks
  src/flb_input_chunk.c
Labels: docs-required

#9143 out_s3: Plug memory leaks on gzipped buffers during the swapping contents
  plugins/out_s3/s3.c
Labels: docs-required
