Repository fluent/fluent-bit, pull requests merged in 2024-05, with the labels that each got.

#8765 workflows: macos: Use matrix for building Apple Silicon artefacts
  .github/workflows/call-build-macos.yaml
Labels: docs-required, ok-package-test

#8789 out_kafka: increase max kafka dynamic topic length to 249 characters
  plugins/out_kafka/kafka.c
Labels: docs-required

#8824 processor_labels: Remove a needless existence check for insert operation
  plugins/processor_labels/labels.c
Labels: ok-to-test, ci/integration-docker-ok, docs-required

#8797 Config: fix incorrect assignment of kernel version between major and minor
  src/flb_kernel.c
Labels: docs-required

#8793 fix: splunk output plugin correct record accessor key for hec_token
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk_conf.c
Labels: docs-required

#8725 in_premetheus_remote_write: Implement handler of payloads of prometheus remote write protocol
  CMakeLists.txt
  cmake/windows-setup.cmake
  plugins/CMakeLists.txt
  plugins/in_prometheus_remote_write/CMakeLists.txt
  plugins/in_prometheus_remote_write/prom_rw.c
  plugins/in_prometheus_remote_write/prom_rw.h
  plugins/in_prometheus_remote_write/prom_rw_config.c
  plugins/in_prometheus_remote_write/prom_rw_config.h
  plugins/in_prometheus_remote_write/prom_rw_conn.c
  plugins/in_prometheus_remote_write/prom_rw_conn.h
  plugins/in_prometheus_remote_write/prom_rw_prot.c
  plugins/in_prometheus_remote_write/prom_rw_prot.h
Labels: docs-required

#8845 in_kubernetes_events: update time check to use struct flb_time.
  plugins/in_kubernetes_events/kubernetes_events.c
Labels: docs-required

#8844 tests: in_podman_metrics: refactor iteration of counters to use cfl_list.
  tests/runtime/in_podman_metrics.c
Labels: docs-required

#8486 engine: free after log worker thread has been stopped
  src/flb_config.c
Labels: docs-required

#8864 out_splunk: reduce noise and fix hec_token handling (fix #8859)
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk.h
  plugins/out_splunk/splunk_conf.c
Labels: docs-required

#8853 winevtlog: change total_size_threshold to size_t
  plugins/in_winevtlog/winevtlog.h
Labels: docs-required

#8796 packaging: add build support for ubuntu 24.04 noble numbat
  packaging/build-config.json
  packaging/distros/ubuntu/Dockerfile
  packaging/update-repos.sh
Labels: docs-required, ok-package-test

#8850 out_stackdriver: Support writing to textPayload field of Cloud Logging LogEntry.
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  tests/runtime/data/stackdriver/stackdriver_test_payload.h
  tests/runtime/out_stackdriver.c
Labels: docs-required

#8873 out_splunk: fix metadata bug that affects splunk_token behavior (fix #8867)
  plugins/out_splunk/splunk.c
  plugins/out_splunk/splunk_conf.c
Labels: docs-required

#8872 core: Fix crash when running dry
  src/fluent-bit.c
Labels: docs-required

#8882 in_prometheus_scrape: add User-Agent HTTP header (#8880)
  plugins/in_prometheus_scrape/prom_scrape.c
Labels: docs-required

#8888 tests/runtime/in_podman_metrics: refactor iteration of counters to use cfl_list from #8844.
  tests/runtime/in_podman_metrics.c
Labels: docs-required

#8832 out_cloudwatch_logs: support log_group_class option
  plugins/out_cloudwatch_logs/cloudwatch_api.c
  plugins/out_cloudwatch_logs/cloudwatch_logs.c
  plugins/out_cloudwatch_logs/cloudwatch_logs.h
Labels: docs-required

#8897 tests: rutime: out_http: simplify and make the in_http test more robust.
  tests/runtime/out_http.c
Labels: docs-required
