Repository fluent/fluent-bit, pull requests merged in 2025-07, with the labels that each got.

#10526 gzip: Process boundary conditions strictly
  src/flb_gzip.c
Labels: docs-required

#10491 upstream: prioritize the reuse of connections instead of establishing new ones
  src/flb_upstream.c
Labels: docs-required

#10534 examples: wasi_serde_json: Follow Rustc target renaming from wasm32-wasi to wasm32-wasmp1
  examples/wasi_serde_json/README.md
Labels: docs-required

#10543 in_kmsg: use strtoull to fix timestamp parsing on 32-bit systems
  plugins/in_kmsg/in_kmsg.c
Labels: docs-required

#10500 out_opentelemetry: fix logic for grouping when using resource_id/scope_id
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: opentelemetry

#10452 out_cloudwatch_logs: fix strcasestr _GNU_SOURCE
  plugins/out_cloudwatch_logs/cloudwatch_api.c
Labels: docs-required

#10558 in_kafka: add enable_auto_commit option for Kafka consumer
  plugins/in_kafka/in_kafka.c
  plugins/in_kafka/in_kafka.h
Labels: docs-required

#10557 lib: cmetrics: upgrade to v1.0.4
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_msgpack.c
Labels: docs-required

#10572 workflows: fix windows check for container image
  .github/workflows/staging-release.yaml
Labels: docs-required, ok-package-test

#10579 out_file: Replace SHCreateDirectoryExA to work for recursive directories correctly
  plugins/out_file/file.c
Labels: docs-required

#10589 network: enable EDNS for DNS queries
  src/flb_network.c
Labels: docs-required

#10593 maintenance: new MAINTENANCE.md file (must read)
  MAINTENANCE.md
Labels: docs-required

#10634 in_syslog: do batching to reduce ring buffer pressure under load
  plugins/in_syslog/syslog_prot.c
Labels: docs-required

#10636 in_syslog: do batching to reduce ring buffer pressure under load [v4.0]
  plugins/in_syslog/syslog_prot.c
Labels: docs-required

#10654 filter_aws: send entity attributes for telemetry association [Backport 4.0]
  plugins/filter_aws/aws.c
  plugins/filter_aws/aws.h
Labels: docs-required

#10661 in_windows_exporter_metrics: Follow windows_exporter prom names correctly and support connection_state metrics
  plugins/in_windows_exporter_metrics/CMakeLists.txt
  plugins/in_windows_exporter_metrics/we.h
  plugins/in_windows_exporter_metrics/we_wmi_tcp.c
Labels: docs-required, backport to v4.0.x

#10628 in_winevtlog: Handle Daylight saving time by using newer functions
  plugins/in_winevtlog/pack.c
Labels: docs-required, ok-package-test
