Repository fluent/fluent-bit, pull requests merged in 2025-02, with the labels that each got.

#9918 log: added a new management signal to overcome a dedadlock
  include/fluent-bit/flb_log.h
  src/flb_log.c
Labels: backport to v3.2.x

#9931 workflows: remove qemu usage
  .github/workflows/call-build-images.yaml
  .github/workflows/call-build-linux-packages.yaml
Labels: docs-required, ok-package-test

#9930 out_opentelemetry: auto configure HTTP/2 protocol when gRPC is enabled
  plugins/out_opentelemetry/opentelemetry.c
  plugins/out_opentelemetry/opentelemetry.h
  plugins/out_opentelemetry/opentelemetry_conf.c
Labels: backport to v3.2.x

#9933 log: added a new management signal to overcome a deadlock
  include/fluent-bit/flb_log.h
  src/flb_log.c
Labels: docs-required

#9894 in_kubernetes_events: fix sqldb cleanup
  plugins/in_kubernetes_events/kubernetes_events.c
Labels: docs-required

#9955 stackdriver: add cloud_logging_base_url (#9779)
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#9960 internal: add NOT_REGEX operator to conditional processing
  include/fluent-bit/flb_conditionals.h
  src/flb_conditionals.c
  tests/internal/conditionals.c
Labels: docs-required

#9965 in_splunk: fix memory corruption by resetting parser after reallocation
  plugins/in_splunk/splunk_conn.c
Labels: docs-required

#9895 in_kubernetes_events: fix sqldb cleanup (backport to v3.2)
  plugins/in_kubernetes_events/kubernetes_events.c
Labels: docs-required

#9900 tests: in_kubernetes_events: backport flake test fix from #9877.
  tests/runtime/in_kubernetes_events.c
Labels: docs-required

#9977 in_http: add compression handling support for gzip, snappy and zstd
  plugins/in_http/http_prot.c
Labels: docs-required

#9926 bug-fix : Check for clang build dependency when building ebpf
  CMakeLists.txt
Labels: docs-required

#9978 in_http: add compression handling support for gzip, snappy and zstd (backport v3.2)
  plugins/in_http/http_prot.c
Labels: docs-required

#9951 CODEOWNERS: add AWS code-owners for AWS-related files
  CODEOWNERS
Labels: docs-required

#10005 workflows: pin QEMU version for Raspbian only
  .github/workflows/call-build-linux-packages.yaml
Labels: docs-required, ok-package-test

#9949 bug-fix: Set correct and unique repo meta data
  packaging/update-apt-repo.sh
Labels: packaging

#10018 in_opentelemetry: fix groups encoding by closing headers properly
  plugins/in_opentelemetry/opentelemetry_logs.c
Labels: docs-required, backport to v3.2.x

#10019 in_opentelemetry: fix groups encoding by closing headers properly
  plugins/in_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#9988 internal: test: conditional: Add Byte-Order-Mark(BOM) for non western Windows environments
  tests/internal/conditionals.c
Labels: docs-required

#9719 filter_kubernetes: add owner references information into record.
  plugins/filter_kubernetes/kube_conf.c
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kube_meta.c
  plugins/filter_kubernetes/kubernetes.c
  tests/runtime/data/kubernetes/log/core/core_base-with-owner-references_fluent-bit.log
  tests/runtime/data/kubernetes/meta/core_base-with-owner-references.meta
  tests/runtime/data/kubernetes/out/core/core_base-with-owner-references_fluent-bit.out
  tests/runtime/filter_kubernetes.c
Labels: docs-required, ok-package-test

#9849 filter_kubernetes: add owner references information into record.
  plugins/filter_kubernetes/kube_conf.c
  plugins/filter_kubernetes/kube_conf.h
  plugins/filter_kubernetes/kube_meta.c
  plugins/filter_kubernetes/kubernetes.c
  tests/runtime/data/kubernetes/log/core/core_base-with-owner-references_fluent-bit.log
  tests/runtime/data/kubernetes/meta/core_base-with-owner-references.meta
  tests/runtime/data/kubernetes/out/core/core_base-with-owner-references_fluent-bit.out
  tests/runtime/filter_kubernetes.c
Labels: docs-required

#10023 out_http: fix logic to handle status of compressed payloads (fix #10016)
  plugins/out_http/http.c
Labels: docs-required

#10024 out_http: fix logic to handle status of compressed payloads (fix #10016 - 3.2)
  plugins/out_http/http.c
Labels: docs-required
