Repository fluent/fluent-bit, pull requests merged in 2025-09, with the labels that each got.

#10806 engine: fix busy chunks on reload. [Backpoprt to 4.0]
  src/flb_engine.c
Labels: docs-required

#10810 http_client: fix incomplete error handling in flb_http_do()
  src/flb_http_client.c
Labels: backport to v4.0.x

#10812 http_client: fix incomplete error handling in flb_http_do() (backport v4.0)
  src/flb_http_client.c
Labels: docs-required

#10804 network: fix strerror_r detection for musl
  src/flb_network.c
Labels: docs-required, backport to v4.0.x

#10803 workflows: add librdkafka to the system libs workflow
  .github/workflows/pr-compile-check.yaml
Labels: docs-required

#10843 in_event_type: implement pause/resume to stop timed collector.
  plugins/in_event_type/event_type.c
Labels: docs-required

#10849 in_winevtlog: Plug possible SEGV occurrence paths
  plugins/in_winevtlog/pack.c
Labels: docs-required

#10858 workflows: Install NSIS via chocolatey
  .github/workflows/call-build-windows.yaml
Labels: docs-required

#10857 in_winevtlog: Plug possible SEGV occurrence paths [Backport to 4.0]
  plugins/in_winevtlog/pack.c
Labels: docs-required

#10864 simd: Handle older version of gcc such as CentOS 7
  include/fluent-bit/flb_simd.h
Labels: ok-package-test

#10886 upstream: Move clearing TLS session from prepare phase to destroy phase
  src/flb_upstream.c
Labels: docs-required

#10877 CODEOWNERS: add alecholmes to fleet.
  CODEOWNERS
Labels: docs-required

#10890 in_calyptia_fleet: create fleet file if not using fleet.
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#10895 upstream: Move clearing TLS session from prepare phase to destroy phase [Backport to 4.0]
  src/flb_upstream.c
Labels: docs-required

#10728 packaging: add debian trixie support
  packaging/README.md
  packaging/build-config.json
  packaging/distros/debian/Dockerfile
  packaging/testing/smoke/packages/Dockerfile.debian13
  packaging/update-apt-repo.sh
  packaging/update-repos.sh
Labels: docs-required, ok-package-test

#10578 input: update mem buf limit logging to include size info
  src/flb_input_chunk.c
Labels: docs-required

#10903 workflows: Use LLD that is LLVM based linker for riscv64 and s390x tasks
  .github/workflows/unit-tests.yaml
Labels: docs-required

#10915 config_format: yaml: fix state parameter for read_blob in Windows
  src/config_format/flb_cf_yaml.c
Labels: backport to v4.0.x

#10930 processor: internal: tests: Ensure to initialize Winsock2 stack
  tests/internal/processor.c
Labels: docs-required

#10931 workflows: windows: Add a testing flow with using ARM64 Windows runner
  .github/workflows/call-windows-unit-tests.yaml
Labels: docs-required

#10936 scripts: Handle two or more digits for patch version
  update_version.sh
Labels: docs-required
