Repository fluent/fluent-bit, pull requests merged in 2025-01, with the labels that each got.

#9760 packaging: raspbian: support raspbian bookworm package creation
  packaging/README.md
  packaging/build-config.json
  packaging/distros/raspbian/Dockerfile
Labels: docs-required, ok-package-test

#9779 stackdriver: add cloud_logging_base_url
  plugins/out_stackdriver/stackdriver.c
  plugins/out_stackdriver/stackdriver.h
  plugins/out_stackdriver/stackdriver_conf.c
Labels: docs-required

#9805 3.2: lib: monkey files
  lib/monkey/.github/workflows/build-pr.yaml
  lib/monkey/ARDUINO_YUN.md
  lib/monkey/cmake/arduino-yun.cmake
  lib/monkey/include/monkey/mk_core/mk_event_poll.h
  lib/monkey/mk_core/mk_event_poll.c
  lib/monkey/qa/put_test01.htt
  lib/monkey/test/CMakeLists.txt
  lib/monkey/test/event_timeout.c
  lib/monkey/test/lib/acutest/acutest.h
  lib/monkey/test/lib_server.c
  lib/monkey/test/mk_tests.h
Labels: docs-required

#9804 lib: monkey: add missing files
  lib/monkey/.github/workflows/build-pr.yaml
  lib/monkey/ARDUINO_YUN.md
  lib/monkey/cmake/arduino-yun.cmake
  lib/monkey/include/monkey/mk_core/mk_event_poll.h
  lib/monkey/mk_core/mk_event_poll.c
  lib/monkey/qa/put_test01.htt
  lib/monkey/test/CMakeLists.txt
  lib/monkey/test/event_timeout.c
  lib/monkey/test/lib/acutest/acutest.h
  lib/monkey/test/lib_server.c
  lib/monkey/test/mk_tests.h
Labels: docs-required

#9789 in_systemd: fix buffer over-read
  plugins/in_systemd/systemd.c
Labels: docs-required

#9809 readme: add swym logo to fluentbit_users.png
  documentation/fluentbit_users.png
Labels: docs-required

#9827 tests: runtime_shell: custom_calyptia prevent fail on macOS at cleanup
  .github/workflows/skipped-unit-tests.yaml
  .github/workflows/unit-tests.yaml
  tests/runtime_shell/custom_calyptia.sh
Labels: docs-required

#9834 workflows: macos: Build Intel Mac packages by macos-14-large runner
  .github/workflows/call-build-macos.yaml
Labels: docs-required, ok-package-test

#9856 in_ebpf: core: Prepare eBPF skeletons before starting to compile in_ebpf plugin properly
  plugins/in_ebpf/CMakeLists.txt
  src/CMakeLists.txt
Labels: docs-required

#9853 pack: fix missing scientific notation in JSON parser [Backport 3.2]
  src/flb_pack.c
Labels: docs-required

#9852 pack: fix missing scientific notation in JSON parser
  src/flb_pack.c
Labels: docs-required

#9866 workflows: update daily builds for 3.2
  .github/workflows/cron-unstable-build.yaml
Labels: docs-required

#9869 workflows: increase size of container builders
  .github/workflows/call-build-images.yaml
Labels: docs-required

#9870 workflows: increase size of container builders
  .github/workflows/call-build-images.yaml
Labels: docs-required

#9871 workflows: remove s390x and armv7 platforms for container builds
  .github/workflows/staging-build.yaml
Labels: docs-required

#9880 packaging: skip empty repos
  packaging/update-apt-repo.sh
Labels: ci

#9884 workflows: fix debug image manifest
  .github/workflows/call-build-images.yaml
Labels: ci

#9875 workflows: split container builds per-arch
  .github/workflows/call-build-images.yaml
  .github/workflows/pr-package-tests.yaml
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile.windows
  packaging/distros/raspbian/Dockerfile
Labels: ci, ok-package-test

#9883 in_opentelemetry: fix finalization of group for gRPC payload (backport for v3.2)
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#9882 in_opentelemetry: fix finalization of group for gRPC payload
  plugins/in_opentelemetry/opentelemetry_prot.c
Labels: docs-required

#9877 tests: in_kubernetes_events: try/wait for output to make tests less flakey, re #9570.
  tests/runtime/in_kubernetes_events.c
Labels: docs-required

#9892 in_calyptia_fleet: log info about config pulled from API
  plugins/in_calyptia_fleet/in_calyptia_fleet.c
Labels: docs-required

#9898 workflows: disable s390x container builds for release
  .github/workflows/call-build-images.yaml
  .github/workflows/call-test-images.yaml
Labels: ci, packaging
