Repository fluent/fluent-bit, pull requests merged in 2025-04, with the labels that each got.

#10179 plugin_proxy: fixed memory leak
  src/flb_plugin_proxy.c
Labels: docs-required

#9797 out_azure_kusto: added buffering fixes
  plugins/out_azure_kusto/CMakeLists.txt
  plugins/out_azure_kusto/azure_kusto.c
  plugins/out_azure_kusto/azure_kusto.h
  plugins/out_azure_kusto/azure_kusto_conf.c
  plugins/out_azure_kusto/azure_kusto_conf.h
  plugins/out_azure_kusto/azure_kusto_ingest.c
  plugins/out_azure_kusto/azure_kusto_ingest.h
  plugins/out_azure_kusto/azure_kusto_store.c
  plugins/out_azure_kusto/azure_kusto_store.h
Labels: docs-required

#10183 in_storage_backlog: added missing routing mask initialization
  plugins/in_storage_backlog/sb.c
Labels: docs-required

#10199 config: yaml: fix double-free from freeing state before cleanup on exit.
  src/config_format/flb_cf_yaml.c
Labels: docs-required

#10180 dockerfile: Windows Containers image Fluent Bit NMake build
  dockerfiles/Dockerfile.windows
Labels: docs-required

#10224 input_chunk: routes_mask is not initialized (#10223)
  src/flb_input_chunk.c
Labels: docs-required

#10234 pipeline: inputs: podman_metrics: use after free fix
  plugins/in_podman_metrics/podman_metrics.c
Labels: docs-required

#10235 out_azure_blob: fixed double free
  plugins/out_azure_blob/azure_blob.c
Labels: docs-required

#10237 in_tail: fix disposal order to prevent use after free
  plugins/in_tail/tail_file.c
Labels: docs-required

#10217 tests: internal: fuzzers: extend ctrace fuzzer
  tests/internal/fuzzers/ctrace_fuzzer.c
Labels: docs-required

#10189 out_oracle_log_analytics: fix use-after-free on flush failure
  plugins/out_oracle_log_analytics/oci_logan.c
Labels: docs-required

#10238 ci: CMake upgrade in code analysis script
  run_code_analysis.sh
Labels: docs-required

#10216 config_format: fix SEGV from missing return check
  src/config_format/flb_config_format.c
Labels: docs-required

#10203 conf: parsers: fix istio-envoy-proxy parser regex
  conf/parsers.conf
Labels: docs-required

#10246 packaging: remove older Ubuntu targets from smoke test
  packaging/test-release-packages.sh
Labels: docs-required, ok-package-test

#10252 out_azure_blob: fixed double free
  plugins/out_azure_blob/azure_blob.c
Labels: docs-required

#10251 in_tail: fix disposal order to prevent use after free
  plugins/in_tail/tail_file.c
Labels: docs-required

#10253 plugin_proxy: fixed memory leak
  src/flb_plugin_proxy.c
Labels: docs-required

#10266 security: update policy for 4.0 release series
  SECURITY.md
Labels: security

#10261 out_azure_kusto: fixed double free
  plugins/out_azure_kusto/azure_kusto_conf.c
Labels: docs-required

#10267 lib: ctraces: upgrade to v0.6.5
  lib/ctraces/.github/workflows/build.yaml
  lib/ctraces/.github/workflows/packages.yaml
  lib/ctraces/CMakeLists.txt
  lib/ctraces/src/ctr_decode_opentelemetry.c
Labels: docs-required
