Repository fluent/fluent-bit, pull requests merged in 2025-10, with the labels that each got.

#10968 reload: refactor watchdog to be preemptable on windows.
  src/flb_reload.c
Labels: docs-required

#10955 out_opentelemetry: add configurable log resource limits
  plugins/out_opentelemetry/opentelemetry.c
  plugins/out_opentelemetry/opentelemetry.h
  plugins/out_opentelemetry/opentelemetry_conf.c
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: opentelemetry, backport to v4.0.x

#10969 out_file: sanitize incoming Tag to prevent path traversal
  plugins/out_file/file.c
Labels: backport to v4.0.x

#10963 out_opentelemetry: no longer reallocates the http2 setting string [Backport to 4.0]
  plugins/out_opentelemetry/opentelemetry_conf.c
Labels: docs-required

#10983 out_file: sanitize incoming Tag to prevent path traversal [Backport to 4.0]
  plugins/out_file/file.c
Labels: docs-required

#10984 in_docker: add helper for container name parsing [Backport to 4.0]
  plugins/in_docker/cgroup_v1.c
  plugins/in_docker/cgroup_v2.c
  plugins/in_docker/docker.c
  plugins/in_docker/docker.h
Labels: docs-required

#10988 reload: refactor watchdog to be preemptable on windows. [Backport to 4.0]
  src/flb_reload.c
Labels: docs-required
