Repository fluent/fluent-bit, pull requests merged in 2025-03, with the labels that each got.

#10040 workflows: update release with minor fixes
  .github/workflows/staging-release.yaml
Labels: ci

#10045 packaging: revert apt repo origin/label info.
  packaging/update-apt-repo.sh
Labels: packaging

#10048 input_thread: added missing sanity check
  src/flb_input_thread.c
Labels: ok-package-test

#10049 input_thread: added missing sanity check (backport)
  src/flb_input_thread.c
Labels: docs-required

#10012 out_loki: add stuctured_metadata_map_keys (3.2.x Backport)
  docker_compose/loki-grafana-structured_metadata_map/README.md
  docker_compose/loki-grafana-structured_metadata_map/config/fluent-bit_loki_out-structured_metadata_map.yaml
  docker_compose/loki-grafana-structured_metadata_map/config/grafana/provisioning/datasources/datasource.yml
  docker_compose/loki-grafana-structured_metadata_map/config/loki-config.yaml
  docker_compose/loki-grafana-structured_metadata_map/docker-compose.yml
  plugins/out_loki/loki.c
  plugins/out_loki/loki.h
  tests/runtime/out_loki.c
Labels: ok-package-test

#10077 in_opentelemetry: logs: add missing checks for resource and scope
  plugins/in_opentelemetry/opentelemetry_logs.c
Labels: docs-required, ok-package-test

#10078 in_opentelemetry: logs: add missing checks for resource and scope (backport 3.2)
  plugins/in_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#10083 out_opentelemetry: restored old group meta record processing mechanism (backport)
  plugins/out_opentelemetry/opentelemetry_logs.c
Labels: docs-required

#10088 workflows: remove invalid sync directory
  .github/workflows/staging-release.yaml
Labels: ci

#10089 out_opentelemetry: switch config property 'http2' default to 'off'
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#10090 out_opentelemetry: switch config property 'http2' default to 'off' (backport 3.2)
  plugins/out_opentelemetry/opentelemetry.c
Labels: docs-required

#10106 workflows: support optional image pushing
  .github/workflows/call-build-images.yaml
  .github/workflows/pr-package-tests.yaml
Labels: docs-required, ok-package-test

#10105 record_accesor: fix return value for flb_ra_get_kv_pair when get_ra_parser fails.
  src/flb_record_accessor.c
Labels: ok-package-test

#10107 workflows: fix optional image pushing
  .github/workflows/call-build-images.yaml
Labels: ok-package-test

#10108 record_accesor: fix return value for flb_ra_get_kv_pair when get_ra_parser fails (Backport)
  src/flb_record_accessor.c
Labels: docs-required

#9921 input_chunk: check return values when calculating found chunks for new space.
  src/flb_input_chunk.c
Labels: docs-required

#10117 processor: fix missing read_groups flags for log event decoder
  src/flb_processor.c
Labels: docs-required

#10118 processor: fix missing read_groups flags for log event decoder (backport for 3.2)
  src/flb_processor.c
Labels: docs-required

#10119 out_splunk: when packing OTel metadata, include resource attributes
  plugins/out_splunk/splunk.c
Labels: docs-required

#10120 out_splunk: when packing OTel metadata, include resource attributes (backport 3.2)
  plugins/out_splunk/splunk.c
Labels: docs-required

#8621 out_exit: add time_count (seconds) and record_count parameters for out_exit.
  plugins/out_exit/exit.c
Labels: docs-required

#10135 workflows: update release promotion to correctly sync
  .github/workflows/staging-release.yaml
Labels: docs-required

#10136 windows: disable unused build targets and optimise container
  .github/workflows/call-build-images.yaml
  dockerfiles/Dockerfile.windows
Labels: ci, Windows, packaging, ok-package-test

#10122 in_kafka: optimize poll timeout handling for threaded and main event loop modes
  plugins/in_kafka/in_kafka.c
  plugins/in_kafka/in_kafka.h
Labels: docs-required

#10144 env: add support to set environment variable content from a file
  src/flb_env.c
Labels: docs-required

#9845 systemd: build: Add sethostname workaround for AmazonLinux2
  CMakeLists.txt
  init/az2-sethostname.in
  init/az2-systemd.in
  src/CMakeLists.txt
Labels: docs-required, ok-package-test

#9859 kafka: Display error messages on error for rd_kafka_conf_set()
  src/flb_kafka.c
Labels: docs-required

#10104 out_datadog: Fix formatting issue when setting a static hostname
  plugins/out_datadog/datadog_conf.c
Labels: docs-required

#10146 processor_content_modifier: fix and enhance data type conversion
  plugins/processor_content_modifier/cm_utils.c
Labels: docs-required

#10151 log_event_decoder: improved group metadata fields are availability
  src/flb_log_event_decoder.c
Labels: docs-required
