Repository fluent/fluent-bit, pull requests merged in 2025-05, with the labels that each got.

#10277 build: only compile simdutf if there is CXX support
  CMakeLists.txt
Labels: docs-required, ok-package-test

#10290 engine: added conditional to avoid re-scheduling conflict
  src/flb_engine.c
Labels: docs-required

#10291 engine: added conditional to avoid re-scheduling conflict
  src/flb_engine.c
Labels: docs-required

#10282 pack: add support for metadata and group info in JSON log
  src/flb_pack.c
Labels: docs-required

#10310 simd: Use __riscv_vsetvl_eXXm1 function to get the actual width of RVV instructions
  include/fluent-bit/flb_simd.h
Labels: docs-required

#10221 systemd: build: fix service startup failure when using IMDSv2
  init/az2-sethostname.in
Labels: docs-required

#10281 input: add missing options to input_global_properties.
  src/flb_input.c
Labels: docs-required

#10324 lib: cmetrics: upgrade to v1.0.2
  lib/cmetrics/CMakeLists.txt
  lib/cmetrics/src/cmt_decode_msgpack.c
Labels: docs-required

#10329 out_splunk: Change attaching priority for HEC token
  plugins/out_splunk/splunk.c
Labels: docs-required

#10336 packaging: add AlmaLinux and RockyLinux builds
  packaging/build-config.json
  packaging/distros/almalinux/Dockerfile
  packaging/distros/rockylinux/Dockerfile
  packaging/test-release-packages.sh
  packaging/update-repos.sh
Labels: packaging, ok-package-test

#10347 in_node_exporter: removed unnecessary optimization that caused crash
  plugins/in_node_exporter_metrics/ne_cpu_linux.c
Labels: docs-required

#10348 in_node_exporter: removed unnecessary optimization that caused crash
  plugins/in_node_exporter_metrics/ne_cpu_linux.c
Labels: docs-required

#9818 http_client: fix muti part http2 request not working
  src/flb_http_client_http2.c
Labels: docs-required

#10349 http_client_http2: fixed request body overwrite issue
  src/flb_http_client_http2.c
Labels: docs-required

#10361 wasm: Enable reference types feature on wasm
  src/wasm/CMakeLists.txt
Labels: docs-required

#10355 engine: fix segfault in flb_config_init error case
  src/flb_config.c
Labels: docs-required

#10368 in_winevtlog: Support remote access of winevtlog
  plugins/in_winevtlog/in_winevtlog.c
  plugins/in_winevtlog/pack.c
  plugins/in_winevtlog/winevtlog.c
  plugins/in_winevtlog/winevtlog.h
Labels: docs-required

#10365 out_opensearch: Prevent a SIGSEGV when ctx->index is NULL
  plugins/out_opensearch/opensearch.c
  tests/runtime/out_opensearch.c
Labels: docs-required

#10263 out_azure_blob: added buffering to azure blob
  plugins/out_azure_blob/CMakeLists.txt
  plugins/out_azure_blob/azure_blob.c
  plugins/out_azure_blob/azure_blob.h
  plugins/out_azure_blob/azure_blob_blockblob.c
  plugins/out_azure_blob/azure_blob_blockblob.h
  plugins/out_azure_blob/azure_blob_conf.c
  plugins/out_azure_blob/azure_blob_store.c
  plugins/out_azure_blob/azure_blob_store.h
Labels: docs-required

#10399 in_forward: Check return values from mutex functions
  plugins/in_forward/fw.c
Labels: docs-required

#10353 out_es: Prevent a SIGSEGV when ctx->index is NULL
  plugins/out_es/es.c
  tests/runtime/out_elasticsearch.c
Labels: docs-required

#10173 out_azure_kusto: support for otel log schema
  plugins/out_azure_kusto/azure_kusto.c
Labels: docs-required

#10385 in_tcp: fix parsed bytes to include separator length
  plugins/in_tcp/tcp_conn.c
Labels: docs-required

#10408 in_http: validate memory allocation and fix object type on tag key
  plugins/in_http/http_config.c
  plugins/in_http/http_prot.c
Labels: docs-required

#10409 out_azure_kusto: fix segfault when log level is debug or trace
  plugins/out_azure_kusto/azure_kusto.c
Labels: docs-required
